New post - Building an AWS Solution Architect Agent with Generative AI
build-on-aws/content pull request #392
Opened 2023-06-13 21:26 UTC by aws-banjo

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.

- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).

- [x] This pull request contains one piece of content (post or page).
- [x] My content resides in a folder named for the URL slug and the post file is named `index.md` (e.g. `posts/what-happens-when-you-type-a-url-into-your-browser/index.md`). If I have a series consisting of multiple pieces, I have followed the structure outlined in the [FAQ](https://github.com/build-on-aws/content/blob/main/FAQ.md#i-have-a-series-of-posts-how-do-i-link-them-together) and only including one of the posts in the PR.

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-14 18:59 UTC, riferrei requested changes

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +The advent of Generative AI has paved the way for new automation and efficiency possibilities. This technology allows builders to design intelligent agents capable of executing a wide range of tasks.
> Among the challenges encountered when building on AWS

I know what you tried to say here, but maybe we should phrase this differently. The way is said asks for some references to validate the statement. Phrase in a way that makes it clear that is not always the case, but more frequent than not.

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +## Agent AWS
I feel this blog post needs a little more story telling to help the reader with the "What/Why". I discovered later in the blog that this piece is about building a "virtual solution architect" to which I corroborated the assumption by looking back on the title. At this point, the blog post is going to abruptly to the how part without explaining the details about what is going to be built, and why. This is particularly important because during the build phase, you can go back to some of the points discussed here to explain why things are being built that way. For instance, you could provide a glimpse into what the solution architect role is supposed to look like, what are the knowledge patterns it often works with, and what are their challenges.

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +The GitHub repository with the code can be found [here](https://github.com/aws-banjo/building-aws-agent).
Any plans to move this code to BuildOnAWS?

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +Task: "Help customers understand best practices on building on AWS by using relevant context from the AWS Well-Architected Framework."
I think it may be useful to explain some of the programming constructs being used here. For instance, this is clearly using the wrapper pattern, to encapsulate the `well_architected_tool` function call response into a much larger, context rich question. Also, explain the Python stuff being used. I, for instance, don't know what the construct `{response}.` does.

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +Now that we have defined our agent, the next step is to create the tools for the agent to use. Tools are very simple: they’re a single function, with a name, and a description. The descriptions are u
> Tools are very simple

It should avoid claiming things are simple. Simplicity is an attribute of each person's understanding. What is easy for some it may be difficult for others. Someone reading this and not following your instructions may feel bad about themselves.

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +The first tool we built is capable of querying the AWS Well-Architected Framework. This tool utilizes a vector database to find relevant answers to user questions. For more details on how to build ve
It feels that knowing about the vector database is mandatory to continue with this blog. It doesn't feel optional. In this case, would be better to explicitly say to read your previous blog instead of suggesting?

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +3. inputs and outputs: These help the interpreter make educated choices about types. They are both a list of expected values, which can be text, image, or audio.
It would be nice if you could provide the reader examples of use cases for each data type. When, for instance, someone would use an audio instead of a text.

2023-06-14 18:59 UTC, riferrei commented on posts/building-agent-aws/index.md
> +After the tools and prompt have been configured, we can finally see what Agent AWS can do. To start the agent we select what LLM to use (StarcoderBase https://huggingface.co/bigcode/starcoderbase for
This paragraph reads a little odd. I got confused about what I am supposed to do here.

2023-06-14 20:09 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +The advent of Generative AI has paved the way for new automation and efficiency possibilities. This technology allows builders to design intelligent agents capable of executing a wide range of tasks.
Rewrote intro

2023-06-14 20:10 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +## Agent AWS
Rewrote intro, added a story about building a Solution Architect

2023-06-14 20:10 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +The GitHub repository with the code can be found [here](https://github.com/aws-banjo/building-aws-agent).
Submitted request, when repo up can update link

2023-06-14 20:10 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +Task: "Help customers understand best practices on building on AWS by using relevant context from the AWS Well-Architected Framework."
Added more details

2023-06-14 20:11 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +Now that we have defined our agent, the next step is to create the tools for the agent to use. Tools are very simple: they’re a single function, with a name, and a description. The descriptions are u
removed simple

2023-06-14 20:11 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +The first tool we built is capable of querying the AWS Well-Architected Framework. This tool utilizes a vector database to find relevant answers to user questions. For more details on how to build ve
added some text to explain you don't need to know about vector databases

2023-06-14 20:11 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +3. inputs and outputs: These help the interpreter make educated choices about types. They are both a list of expected values, which can be text, image, or audio.
added

2023-06-14 20:12 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +After the tools and prompt have been configured, we can finally see what Agent AWS can do. To start the agent we select what LLM to use (StarcoderBase https://huggingface.co/bigcode/starcoderbase for
rewrote

2023-06-15 18:17 UTC, damonk10 commented on posts/building-agent-aws/index.md
> +Remember, this is not an endpoint but a launchpad. The agent/tool framework is a wellspring of opportunities waiting to be tapped. Equipped with this knowledge, let's embrace this thrilling journey.
Some links for the curious reader would be good here.

2023-06-15 18:40 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +
removed

2023-06-15 18:40 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +Agent AWS is an automated, AI-powered agent that uses [HuggingFace Transformers](https://huggingface.co/docs/transformers/en/transformers_agents) paired with numerous different [foundation models](ht
added

2023-06-15 18:41 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +Remember, this is not an endpoint but a launchpad. The agent/tool framework is a wellspring of opportunities waiting to be tapped. Equipped with this knowledge, let's embrace this thrilling journey.
added

2023-06-16 20:05 UTC, aws-banjo commented on posts/building-agent-aws/index.md
> +The GitHub repository with the code can be found [here](https://github.com/aws-banjo/building-aws-agent).
repo created, links have been updated
https://github.com/build-on-aws/building-gen-ai-agent-on-aws

2023-06-20 15:48 UTC, riferrei approved these changes
LGTM

2023-06-20 16:04 UTC, merged