first commit - draft
build-on-aws/content pull request #403
Opened 2023-06-14 00:44 UTC by cherbk

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-23 00:30 UTC, lenadroid commented
@abhirockzz could you please take a look for technical review? thanks

2023-06-23 00:32 UTC, lenadroid commented
@franklinaws thanks so much for submitting your post! 

> Please ensure the file size is below 2000 Kb

Could you please reduce the size of the images to resolve validation errors? Thank you!

After you do, you should be able to see a nice preview link with what your post looks like on the website.

2023-06-26 05:42 UTC, abhirockzz requested changes
This is a nice article! However, the promise of "how to move to real time analytics" is not reflected in the content. It does a great job of talking about the primitives, concepts and best practices, but it does not give prescriptive guidance on "how to actually move". 

A better way to explain would be by demonstrating how to shift from a batch architecture to real-time streaming with an example (even a simple one would have been fine). An actual step-by-step architecture and demo would be ideal. If that's too much, at least a theoretical discussion is warranted.

If the above cannot be done, consider changing the title and abstract to better suit the actual content.

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Let’s take a step back and talk about the data structure that supports streaming data architectures. This data structure is the commit log. A commit log works like a persistent queue composed of an o
Not sure if this is accurate. I would consider re-thinking this. The ability to replay (and analyse) past data relies on persistence - it's not the other way around. These should be treated differently.  "data stored in a commit log" - this is good from a "mental model" point of view, but you need to mention the actual persistent store behind the commit log (disk, object store, etc.)

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream programming constructs
Please add a sentence right before this, to help with a logical transition from "stream store" discussion into "Stream programming constructs"

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream programming constructs
BTW, ddi you mean "stream processing" (not programming?). Please consider replacing "programming" with "processing"

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +There are different programming constructs when working with streaming architectures.
remove the word "programming". and perhaps replace "constructs" with "concepts". will that make sense?

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +* **Aggregations**: This is simply the summarization of data to query for particular values and allow you to perform operations like sum, average, min, max, etc.
I like this point. Do you think it makes sense to generalise it by stating "stateful computations" and aggregations being one of them?

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Leveraging these different programming constructs allows you to take advantage of what stream processing has to offer. These constructs can be used in isolation or in tandem to allow you to create si
reconsider removing this line. these concepts are core to stream processing, not an add-on. and one would "implicitly" take advantage of them if adopting a stream processing architecture

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream processing considerations
just like the previous suggestion. add a line before this heading to allow for a smooth logical transition

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream processing considerations
also, add a line after this as well (before jumping into the considerations)

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +### Transaction data into stream
consider changing this heading - it's unclear

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +One consideration for organizations moving into real-time streaming would be transforming existing transaction data into a stream of events. Most organizations have transactional data residing in rel
did you mean "transactional" data?

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +One consideration for organizations moving into real-time streaming would be transforming existing transaction data into a stream of events. Most organizations have transactional data residing in rel
"This allows database systems to read at the log level using the commit log." - please change/reword this sentence.

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In the beginning, we talked about the challenges of building a silo-based architecture where your datastores are isolated. A similar scenario can arise when organizations build isolated stream stores
consider changing to "In one of the previous section, we discussed the challenges...."

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
change to "In the beginning, we discussed..."

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
"three major criteria" - please make sure to highlight each one of them individually (just like you did for the first one)

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
change "from traditional data analytics" to "from a traditional approach..."

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
the first sentence can be made much more concise

2023-06-26 05:42 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
"How siloed architecture needed to be bridged together." - remove this or integrate this as part of another sentence.

2023-06-26 16:34 UTC, franklinaws commented
> 

Hi Abhishek!  Thanks for reviewing and comments on the blogonaws article
Would you recommend a title change to any of this?

Understand the evolution from batched processing to real-time streaming
What to consider when moving from batch to realtime data stream processing
6 things to consider when moving from batch to realtime data stream processing

2023-06-26 16:37 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +title: Understanding streaming data use cases and applications - how to move real time analytics
I made the changes, but would like to get your recommendation among these titles

Understand the evolution from batched processing to real-time streaming
What to consider when moving from batch to realtime data stream processing
6 things to consider when moving from batch to realtime data stream processing

2023-06-26 16:41 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +description: Learn how we evolved into using real-time streaming analytics.  We'll take a step back to deep-dive on streaming concepts and use cases, understand how to move your organization to lever
sorry,  where can i see the double space?

2023-06-26 16:48 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +description: Learn how we evolved into using real-time streaming analytics.  We'll take a step back to deep-dive on streaming concepts and use cases, understand how to move your organization to lever
reworded the description

2023-06-26 16:48 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +  - perishable-insights
Removed

2023-06-26 16:49 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +A lot of things have changed in the past few years in how we handle data, from introducing different ways to store it using data warehousing, Hadoop, and NoSQL databases to offering remote storage an
Rephrased

Advancements in networking and computing have pushed more processing to happen at the edge with Internet of Things and edge computing. Now we are seeing a diverse set of data sources sending data more often and at higher quality.

2023-06-26 16:49 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Perishable insights
Removed the heading.

2023-06-26 16:59 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +For most systems that start early on, they are designed using a siloed-based architecture.  Some start from small
Done

2023-06-26 17:13 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Real-time data streaming is the collection and ingestion of data from various sources and processing it in real time to gain meaning and insight.
Its similar, let me pick one.

2023-06-26 17:18 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Below are some of the common use cases for streaming
Thats a good catch.  I chose to simplify tackling the components into that paragraph.  Let me remove the components heading, add a use cases heading and rearrange the paragraphs a bit

2023-06-26 17:22 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Above are the components of a real-time data streaming pipeline. The sources are devices or applications producing high volumes of continuous data at high velocity, like mobile devices, web applicati
Thank you.  Don't mind if i do. :)

2023-06-26 17:32 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +One consideration for organizations moving into real-time streaming would be transforming existing transaction data into a stream of events. Most organizations have transactional data residing in rel
> did you mean "transactional" data?

Yes. changed.

2023-06-26 17:43 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +One consideration for organizations moving into real-time streaming would be transforming existing transaction data into a stream of events. Most organizations have transactional data residing in rel
> 

That sentence was not really helping this paragraph.  What i wanted to say is 
"This allows you to bring your transactional data into your streaming platform"

2023-06-26 17:44 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In the beginning, we talked about the challenges of building a silo-based architecture where your datastores are isolated. A similar scenario can arise when organizations build isolated stream stores
Changed

2023-06-26 17:45 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
> change to "In the beginning, we discussed..."
Changed.

2023-06-26 17:59 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
> "three major criteria" - please make sure to highlight each one of them individually (just like you did for the first one)

Good advice,  I modified it,

2023-06-26 18:06 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
> the first sentence can be made much more concise

changed into
"In this blog, I talked about how data analytics have evolved from traditional data approach dealing with data in hours, days, months, or years, into data in seconds and minutes and hours through real-time analytics."

2023-06-26 18:15 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
Incorporated into

"I looked at the current trends and how advancements in technology are ushering in real-time analytics to gain real-time insights that benefit the business and help break down data silos."

2023-06-28 03:50 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +title: Understanding streaming data use cases and applications - how to move real time analytics
Thanks. I would actually go with this title "Six Things to Consider When Moving From Batch to Real-time Data Stream Processing" (replace six with a number you think that makes sense in-line with the content).

description looks good. if possible, try to make the description a bit more concise if possible (think "one-liner").

2023-06-28 03:51 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +description: Learn how we evolved into using real-time streaming analytics.  We'll take a step back to deep-dive on streaming concepts and use cases, understand how to move your organization to lever
in the description - "analytics.  We'll"

2023-06-28 03:56 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +There are certain processes where batch processing works well. Some examples are processing hourly logs, weekly or monthly bills, daily website clickstreams, or daily fraud reports. Again, these are
hmmm. I would consider re-writing it as follows if possible "Batch processing excels at handling tasks like processing hourly logs, weekly or monthly bills, daily website clickstreams, or daily fraud reports. These involve data typically used in traditional analytics, where the age of the data spans from hours to days, months, or even years."

what do you think?

2023-06-28 03:59 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Let’s take a step back and talk about the data structure that supports streaming data architectures. This data structure is the commit log. A commit log works like a persistent queue composed of an o
@franklinaws did you get a chance to look into this?

2023-06-28 04:02 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data analytics, which deals with data in hours, days, months, or years, into real-time analytics, which deals with data i
I would consider changing to something like "In this blog, I discuss the evolution of data analytics from traditional methods, which handle data spanning hours, days, months, or years, to real-time analytics that process data within seconds, minutes, and hours."

Let me know what you think

2023-06-28 04:12 UTC, abhirockzz requested changes
Thanks for the updates! 

As far as the title is concerned, I would actually go with this title "Six Things to Consider When Moving From Batch to Real-time Data Stream Processing" (replace six with a number you think that makes sense in-line with the content).

The description looks good. if possible, try to make it a bit more concise if possible (think "one-liner").

Please take a look at some of pending review items you might have missed and let me know what you think. Once that's done, we should be good to go.

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
"Second is considering to buy.... " Can you update this to "Secondly, consider purchasing and outsourcing your stream source to a vendor." ?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data approach dealing with data in hours, days, months, or years, into data in seconds and minutes and hours through real
I would consider changing to something like "In this blog, I discuss the evolution of data analytics from traditional methods, which handle data spanning hours, days, months, or years, to real-time analytics that process data within seconds, minutes, and hours."

Let me know what you think

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +### Transaction data into stream
did you get a chance to take a look at this?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream processing considerations
did you get a chance to take a look at this?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Leveraging these different programming constructs allows you to take advantage of what stream processing has to offer. These constructs can be used in isolation or in tandem to allow you to create si
did you get a chance to take a look at this?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +* **Aggregations**: This is simply the summarization of data to query for particular values and allow you to perform operations like sum, average, min, max, etc.
did you get a chance to take a look at this?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +## Stream programming constructs
did you get a chance to take a look at this?

2023-06-28 04:12 UTC, abhirockzz commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Let’s take a step back and talk about the data structure that supports streaming data architectures. This data structure is the commit log. A commit log works like a persistent queue composed of an o
did you get a chance to take a look at this?

2023-07-04 06:05 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +title: Understanding streaming data use cases and applications - how to move real time analytics
I made the title change to what you recommended.  I also modified the description into "Learn how we evolved from batch into using real-time streaming analytics and understand what to consider when moving your organization to real-time streaming."

2023-07-04 06:06 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +description: Learn how we evolved into using real-time streaming analytics.  We'll take a step back to deep-dive on streaming concepts and use cases, understand how to move your organization to lever
I rewrote the description.  It should be just one sentence

2023-07-04 06:09 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +Last, but definitely not least, is understanding when it is best to build or buy. There are three major criteria to consider when deciding between building versus buying. First is competency. Is your
Done

2023-07-04 06:12 UTC, franklinaws commented on posts/understanding-streaming-data-uses-cases-and-applications-how-to-move-to-real-time-analytics/index.md
> +In this blog, I talked about how data analytics have evolved from traditional data approach dealing with data in hours, days, months, or years, into data in seconds and minutes and hours through real
Thanks! Done.

2023-07-11 09:03 UTC, riferrei approved these changes
Content ready

2023-07-12 15:55 UTC, cobusbernard commented
Thanks for the great post @franklinaws, we couldn't edit this PR, so we create a new one with some small fixes before we published - #531 , article is now published.

2023-07-12 15:55 UTC, closed without merging