New post: Practical cloud guide - We're Moving to the Cloud
build-on-aws/content pull request #414
Opened 2023-06-14 04:31 UTC by cobusbernard

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-14 04:32 UTC, cobusbernard commented
New PR from #349 , please continue review here. Due to making repo public.

@spara : I recreated the PR, the previous feed is still on the old PR (#349), but it looks like you addressed all of it. Just mentioning in case there were some still pending.

2023-06-19 17:52 UTC, spara requested changes
Adding link for CTA

2023-06-19 17:52 UTC, spara commented on posts/practical-cloud-guide/were-moving-to-the-cloud-a-practical-guide-to-cloud-migration/index.md
> +To start your journey, we’ll start with deploying web applications in Windows Server 2022 and Linux. These tutorials demonstrate how to create a cloud instance of a server. In addition, you will conf
This adds the link to the follow up post in the CTA that was missing.

2023-06-20 17:29 UTC, cherbk approved these changes

2023-06-21 23:08 UTC, merged