New Post: Set Up and Configure Microsoft PKI for Smart Card Authentication with Amazon WorkSpaces
build-on-aws/content pull request #417
Opened 2023-06-14 04:53 UTC by cobusbernard

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-14 04:53 UTC, cobusbernard commented
Please use this PR for review, from old #352. Due to making repo public.

2023-06-22 21:11 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +Amazon WorkSpaces provides customers with the ability to use Common Access Card (CAC) and Personal Identity Verification (PIV) smart cards for authentication into WorkSpaces. Amazon WorkSpaces suppor
Please expand OCSP atleast once in the beginning.

2023-06-22 21:11 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +![High-level architecture overview of the connectivity process to Amazon WorkSpaces using a smart card](./images/01_high-level-architecture-connectivity-process-amazon-workspaces-with-smart-card.png)
Please add more context to the architecture diagram, explaining what and why the recommended setup

2023-06-22 21:17 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +For this walkthrough, you should have the following prerequisites:
Can you please provide links to already existing documentation? The prerequisites list is a bit long and could be complicated.

2023-06-22 21:36 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +Amazon WorkSpaces provides customers with the ability to use Common Access Card (CAC) and Personal Identity Verification (PIV) smart cards for authentication into WorkSpaces. Amazon WorkSpaces suppor
fixed it

2023-06-23 17:27 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +5. [Manually domain join](https://docs.aws.amazon.com/directoryservice/latest/admin-guide/join_windows_instance.html?sc_channel=el&sc_campaign=devopswave&sc_content=microsoft-pki-smart-card-authentic
Should it be "Manually join the the OCSP instance to your AD domain"? The current sentence is seems weird to me -  "Manually domain join the OCSP instance to your AD domain"

2023-06-23 18:02 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +2. Specify the stack details as follows:
- Stack name is missing here. 
- Select any one of the private subnets?
- Can we add security group to the pre-req pls
- Is it same Keypair for the AD?
- Can we add a bit more details for what is One-Tier or Two-Tier? Or atleast a link to the explanation
- Same for S3 for CA CRL, a little more context will help the reader make the decision

2023-06-23 18:03 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    14. For **CA CRL S3 Bucket Name**, enter the name of the bucket created in Step 2: Set up S3 bucket to store certificate revocation lists (CRLs) and certificates.
I dont see a step 2 anywhere before this where we have create a S3 bucket.

2023-06-23 18:05 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +2. Select the AWS security group of your AWS Managed Microsoft AD directory or a different security group if using self-managed AD. When using AWS Managed Microsoft AD, the security group name is for
I used the launch wizard so the security group name was not formatted like this. Its name was: 
Security Group name: LaunchWizard-BuildOnBlo-DomainMemberSG-1PKZ0LT0S0O00
Name: DomainMembersSecurityGroup
Are we referring to this?

2023-06-23 18:08 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +   * Repeat steps a–c but change the **Port range** value for step b to 49152 – 65535.
made some changes for more clarity. Please verify

2023-06-23 18:12 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +1. Create or locate an existing group policy in your domain, right-click it, select **Edit…**
numbering is continued?

2023-06-23 20:13 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +8. Disconnect from the WorkSpace and _create a custom image_ from the WorkSpace.
can you provide a link to documentation for creating the custom image here

2023-06-23 20:16 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * The AD Connector’s service account does not have the correct Kerberos Constrained Delegation Settings. Ensure the service account is delegated access to the LDAP service on each DC that it can
are we referring to a link here? Sentence ends with "refer to this"

2023-06-23 20:17 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * OCSP validation is failing. Refer to the previous Section 5 Step 4 to test OCSP validation.
There is no "Section 5, step 4"

2023-06-23 20:31 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * _Launch a WSP **WorkSpace_ for your test user and wait for it to become available.
are we adding an external link here?

2023-06-23 20:32 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * Follow the steps to _Grant SSH access to Amazon Linux **WorkSpaces** administrators_.
Are we to add link for the steps to grant access?

2023-06-23 20:33 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * Open _Directory Services console_, view the details page of your AD Connector, scroll down to Smart card authentication.
are we referring to an external link here?

2023-06-23 20:34 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * Open _Amazon **WorkSpaces** console_, select any existing WorkSpaces and select **Delete**.
are we referring to an external link here?

2023-06-23 20:35 UTC, gaonkarr commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +    * Open _Amazon **WorkSpaces** console_ and select **Directories**.
are we referring to an external link here? can we check the same for all the points in Cleanup? Also we don't need it to be Italics.

2023-06-23 21:00 UTC, gaonkarr requested changes
I was unable to follow all the steps as I do not have a CAC or PIV card. I have been through entire blog, followed as many steps as I could and have left comments for the author to look at. I have also made many minor changes to indentation, sentences - please double check the same. Also, we have added Table of Content and Attributes table. Please update the attributes table appropriately.

2023-07-06 15:38 UTC, cobusbernard commented
@gaonkarr can you please sync with @austinwebber to check if all the feedback was implemented?

2023-07-06 21:59 UTC, scribwell commented
@damonk10 This article is ready for your editorial review.

2023-07-18 19:16 UTC, damonk10 commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +Amazon WorkSpaces provides customers with the ability to use Common Access Card (CAC) and Personal Identity Verification (PIV) smart cards for authentication into WorkSpaces. It supports smart cards
Is all of this info in the first paragraph necessary? I like your intro starting on line 19 "In this post, we will...". I don't like the detail in the first paragraph, though, because I feel like it's not telling me why I should care -- it's just stating information. Why is Amazon Workspaces helpful? What is the problem you're trying to solve here? I have to feel the problem before I desire a solution.

2023-07-18 19:16 UTC, damonk10 commented on tutorials/microsoft-pki-smart-card-authentication-amazon-workspaces/index.md
> +In this post, you learned how to set up and configure a new or existing Microsoft PKI environment for use with smart card authentication for Amazon WorkSpaces. Now your users are able to authenticate
Nice. But can you give some next steps for the curious reader? What else should they read if they want to dive deeper on this general topic? What are other projects they might enjoy trying? Give them some homework!

2023-07-19 14:07 UTC, damonk10 approved these changes

2023-07-19 14:13 UTC, gaonkarr approved these changes

2023-07-19 14:32 UTC, scribwell approved these changes

2023-07-19 14:33 UTC, merged