What Happened to my Car? Understanding Gray Failures
build-on-aws/content pull request #433
Opened 2023-06-16 14:57 UTC by crichey

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ X] The title of this pull request reflects the title of my content.
- [ X] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ X] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-16 20:43 UTC, scribwell commented
@setheliot This article is ready for your technical review.

2023-06-16 22:20 UTC, setheliot requested changes
Looks great!  Mostly minor comments.

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +# What Happened to my Car? Understanding Gray Failures
1. Please review title with @damonk10  -- he is our "Storyteller" and can really help coming up with compelling titles.

2. Please [use the template here](https://raw.githubusercontent.com/build-on-aws/content/main/templates/post.md) (essentially add the metadata front-matter)

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +I'm not a car guy but I am a tech guy, and more importantly, an expert in resilience! This failure in my car worried me because I didn't know what caused the problem, if it would happen again, etc. s
Rather than repeat the same text "I'm not a car guy", you should repeat the beat.  So consider changing to "While I'm not a car guy, I am  tech guy"

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +# What Happened to my Car? Understanding Gray Failures
3. Some pictures can really add visual appeal to this.  See https://w.amazon.com/bin/view/AdobeEnterpriseStock/ for images we have rights to. 

There are some funny ones
![image](https://github.com/build-on-aws/content/assets/3674210/57e0e580-05b3-4e05-9b22-f5fec8019317)

And ones you can make fun of
![image](https://github.com/build-on-aws/content/assets/3674210/17526977-6e67-4587-aca9-9456f5e2a2c8)

Or you can even use pictures of your own mini-van!

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +In my role at Amazon, I spend most of my time talking to people about resilience. One of the frequent topics in these discussions is gray failures. Gray failures come up a lot because they can be hig
can you link the word "resilience" to here? https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/resiliency-and-the-components-of-reliability.html

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +I'm not a car guy but I am a tech guy, and more importantly, an expert in resilience! This failure in my car worried me because I didn't know what caused the problem, if it would happen again, etc. s
@damonk10 will need to figure out what to do with ".)."

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +Ok, fine. Maybe I wasn't paying attention the first time and I caused the issue. Operator error is definitely an issue with software and driving. I get back on the road. I come to another red light a
> with software and driving.

with _both_ software and driving.

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +The car continues to run fine. Occasionally, when I'm feeling brave, I even attempt to reproduce the failure. I try to start suddenly while the engine is restarting or something similar. I can't repr
>  had implemented more health checks that looked deeper into parts of the system so that I could know what went wrong

was looking for this... nice!

2023-06-16 22:20 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +These improvements that I wish for in my car are things we, as engineers, can add to our software applications. We need to make sure we implement [deep health checks](https://aws.amazon.com/blogs/net
You are missing the key solution which is to implement differential observability - https://docs.aws.amazon.com/whitepapers/latest/advanced-multi-az-resilience-patterns/detecting-single-instance-and-availability-zone-isolated-failure.html

If you want, for shallow/deep health checks, consider linking to this lab: https://wellarchitectedlabs.com/reliability/300_labs/300_health_checks_and_dependencies/

2023-06-19 17:54 UTC, crichey commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +These improvements that I wish for in my car are things we, as engineers, can add to our software applications. We need to make sure we implement [deep health checks](https://aws.amazon.com/blogs/net
ON your first comment I believe I do address the issue by talking about canaries as a way to obtain differential observability to document the user's experience. Perhaps I'm misunderstanding your comment.

2023-06-19 18:15 UTC, setheliot commented on posts/what-happened-to-my-car/what-happened-to-my-car.md
> +These improvements that I wish for in my car are things we, as engineers, can add to our software applications. We need to make sure we implement [deep health checks](https://aws.amazon.com/blogs/net
yeah, you do, but I think for the reader it needs to be stated more explicitly.  Tie into what you said and briefly discuss why "all the layers" + "customer experience" is key here

2023-06-28 04:22 UTC, setheliot approved these changes

2023-07-06 15:42 UTC, cobusbernard commented
@setheliot I see you added the flag "ready for technical review", but also approved this, does that mean you completed the tech review?

2023-07-07 01:12 UTC, setheliot commented
@cobusbernard tech review is completed, including author responses

2023-07-07 14:39 UTC, scribwell commented
@damonk10 This post is ready for editorial review.

2023-07-12 16:06 UTC, merged