New Tutorial: Start an EC2 Mac instance
build-on-aws/content pull request #434
Opened 2023-06-16 19:36 UTC by cobusbernard

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-16 19:37 UTC, cobusbernard commented
Please use this PR going forward, old PR #380. Due to making repo public.

2023-06-16 20:00 UTC, bketelsen requested changes
small changes requested. Looks good!

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +This is a 11 parts article about EC2 Mac instances and advanced CLI usage on macOS, including command-line build, test, sign, archive and deploy.
```suggestion
This is a 11 part article about EC2 Mac instances and advanced CLI usage on macOS, including command-line build, test, sign, archive and deploy.
```

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +- This is the first part, you learn how to allocate a Mac mini host and start it.
```suggestion
- This is the first part, where you will learn how to allocate a Mac mini host and start it.
```

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +- When reading [part 2](), you will learn how to remotely connect to the EC2 Mac instance you just started.
```suggestion
- In [part 2](), you will learn how to remotely connect to the EC2 Mac instance you just started.
```

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +There is no virtualisation involved when running an EC2 Mac instance, you have the full Mac mini for you and macOS runs on bare metal. This design decision allows to comply with Apple macOS license t
This design decision allows *you* to comply...

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +When you want to use an EC2 Mac instance for your development workflow, the first step iswq to reserve a host for your own usage. You can use the [AWS Console](https://eu-central-1.console.aws.amazon
```suggestion
When you want to use an EC2 Mac instance for your development workflow, the first step is to reserve a host for your own usage. You can use the [AWS Console](https://eu-central-1.console.aws.amazon.com) or the [command line interface](https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html) to do so. The **Dedicated Hosts** section is available in the EC2 console.
```

2023-06-16 20:00 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +- We can create [EBS snapshots](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSSnapshots.html) of my volumes and create [Amazon Machine Image](https://docs.aws.amazon.com/AWSEC2/latest/UserGu
usefull --> useful

2023-06-18 07:52 UTC, sebsto commented
I am unable to edit this one - maybe I need to follow an advanced git course :-) 
So closing this one in favor of 
https://github.com/build-on-aws/content/pull/437

@bketelsen all your suggested changes have been included - thank you.

2023-06-18 07:52 UTC, closed without merging

2023-06-18 13:51 UTC, cobusbernard commented
@sebsto : Not your understanding of git :) This is due to making the repo public, it disconnected all private forks, so I recreated the PRs, but due the permissions, only maintainers of this `content` repo can make changes to a PR. Thanks for opening the new one.