Start an EC2 Mac instance
build-on-aws/content pull request #437
Opened 2023-06-18 07:51 UTC by sebsto

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X] The title of this pull request reflects the title of my content.
- [X] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X] This pull request contains one piece of content (post or page).

This is the replacement of 
https://github.com/build-on-aws/content/pull/434

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-23 16:37 UTC, scribwell commented
@bketelsen This article is ready for your technical review.

2023-06-23 20:22 UTC, bketelsen requested changes
small changes requested.  Pending those, approved.

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +    - devops
duplicate tag

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +When developing applications for Apple systems (iPhone, iPad, Watch, TV, or Vision Pro), you are require to use a macOS machine at some point of your development workflow. Either to provide remote de
require -> required

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +This series of tutorials takes you through the typical tasks required to start, connect, or configure macOS-based machines in the AWS cloud. Each tutorial is independent from each other, you don't ha
remove "from each other"

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +This is a 11 part article about EC2 Mac instances and advanced CLI usage on macOS, including command-line build, test, sign, archive and deploy.
This is part 2 in an eleven article series about ...

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +To check our [Saving Plans](https://aws.amazon.com/savingsplans/) pricing and options, go to [Saving Plans Compute Pricing page](https://aws.amazon.com/savingsplans/compute-pricing/), then select **E
[Savings Plans]

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +![Saving Plans](images/saving-plans.png)
again "Savings"

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +- Talking about networking, we can access other AWS services from macOS, using the same VPC routing mechanisms defined at network-level ([NAT Gateways](https://docs.aws.amazon.com/vpc/latest/userguid
Talking about --> Speaking of

2023-06-23 20:22 UTC, bketelsen commented on tutorials/ec2-mac/01-start-an-ec2-mac-instance/index.md
> +Terminating an instance is very different. It is a definitive action. Once an instance is terminated, it can not be restarted. By default, its associated disks (EBS volumes) are deleted upon terminat
definitive -> permanent

2023-06-24 11:51 UTC, sebsto commented
All changes are addressed. Thank you

2023-06-28 15:49 UTC, bketelsen approved these changes

2023-06-28 18:54 UTC, bketelsen approved these changes
LGTM

2023-06-28 21:36 UTC, merged