Protect rds data
build-on-aws/content pull request #442
Opened 2023-06-19 22:01 UTC by setheliot

# this is a replacement for https://github.com/build-on-aws/content/pull/407
(sorry, I was not able to append to the existing requesT)

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-21 15:39 UTC, damonk10 approved these changes

2023-06-30 16:59 UTC, cobusbernard requested changes
@setheliot looks good, only thing missing is the ToC, and tracking links, can you please add before publishing. Thanks!

2023-07-03 17:48 UTC, setheliot commented
@cobusbernard done!

2023-07-03 19:30 UTC, cobusbernard approved these changes

2023-07-03 19:31 UTC, merged