Practical cloud guide aspnetcore on lightsail
build-on-aws/content pull request #443
Opened 2023-06-19 22:05 UTC by spara

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ x] The title of this pull request reflects the title of my content.
- [ x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x ] This pull request contains one piece of content (post or page).

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-20 17:15 UTC, cherbk approved these changes

2023-06-23 19:44 UTC, cobusbernard requested changes

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +description: ""
@spara, can you please add a description for the piece that ties in with the title, but doesn't repeat it?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +For this task you will deploy an ASP.NET Core application on IIS in Windows Server. The application is simple web application, but requires installing and configuring IIS in addition to deploying it.
```suggestion
For this task you will deploy an ASP.NET Core application on IIS in Windows Server. The application is a simple web application, but requires installing and configuring IIS in addition to deploying the application to IIS. Let’s begin with a AWS Lightsail overview to familiarize working with this service.
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +For this task you will deploy an ASP.NET Core application on IIS in Windows Server. The application is simple web application, but requires installing and configuring IIS in addition to deploying it.
Can you also add a bit more of an overview of how the solution will use Lighsail, e.g. something like "We will use Lightsail to run a virtual server for us, compile and zip up the application we want to deploy, upload the zip to S3 to allow copying it easily to the server, configure IIS, and then deploy our application"?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +**Create an instance** has several options. First, choose the **Instance location**, you can leave the default, or choose the closest AWS Region. Second, choose either Linux or Windows Server for the
Can they choose Linux or Windows? I believe IIS only runs on Windows?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +You can choose the Instance plan. One of the advantages of Lightsail is a fixed monthly cost for a VPS.
```suggestion
There are multiple instance types to choose from, one of the advantages of Lightsail is a fixed monthly cost for a VPS. For this tutorial, we are going to use the <which size you picked> instance type.
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In this module, the software and deployment script is in a GitHub repository. You will clone the repository to copy the files to your local drive. The next step is to create an S3 bucket to store the
Please add in a bit of detail about S3 bucket names being globally unique, and state that for this tutorial, you will use the name X.

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In the **Create a new bucket** page choose the **5GB storage plan** and name the bucket `practical-cloud-guide`. Select **Create Bucket**.
Please add a comment here as well that the tutorial uses "practical-cloud-guide" as the bucket name, but they need to pick a different one.

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Select `app.zip` and `deploy_iis.ps1` from `./practical-cloud-guide-code/run-to-build/windows-app-deploy
I don't see the zip in the sample code repo, and it should not be added. Is there a step here missing on how to compile the application and zip it up?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Open the AWS Console in a browser and use the search bar to find AWS Light Sail.
Having gone through the rest of the tutorial, this section isn't clear that you are illustrating how you would spin up a Lightsail instance, but the reader should not follow the steps. Can you please add in a clear statement that this is to illustrate how to spin up a new instance, but that we are going to add in some automation to configure it for us and that the reader should *not* spin this one up?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In [DevOps](/concepts/devops-essentials), applications are typically built with Continuous Integration (CI) software. Code is pushed into the CI by developers where it is built and tested and release
Can you please expand here that we are going to use a powershell script to configure the server for us before showing the steps to allow the reader to understand the why before we get to the what?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Open a Powershell terminal from either the Windows menu bar or by searching for Powershell. The Lightsail Windows Server instances include [AWS Tools for Powershell](https://docs.aws.amazon.com/power
```suggestion
Open a Powershell terminal from either the Windows menu bar or by searching for Powershell. The Lightsail Windows Server instances include [AWS Tools for Powershell](https://docs.aws.amazon.com/powershell/?sc_channel=el&sc_campaign=community-aws&sc_content=deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail&sc_geo=mult&sc_country=mult&sc_outcome=acq), which are a set of Windows `cmdlets` for creating and managing AWS resources.  Set your AWS credentials with Powershell.
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +```powershell
Instead of using hard-coded API credentials, can you please update to use resource permissions that don't require the key/secret please? https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-configuring-bucket-resource-access

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +net stop was /y
Is this command correct? Should it be `was` or `w3svc` since I see that is used for the `start` command below?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +$YourBucketName = "practical-cloud-guide-3"
```suggestion
$YourBucketName = "practical-cloud-guide"
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In [DevOps](/concepts/devops-essentials), applications are typically built with Continuous Integration (CI) software. Code is pushed into the CI by developers where it is built and tested and release
Also, after finishing the tutorial, I realized we aren't setting up any kind of automated deployment here, can you please expand the intro to indicate this isn't going to set up a CI server, or update this line to indicate how the powershell script ties in with DevOps and remove the mention of a CI server? The way you phrase it on line 286 is great: 

"The `deploy_iis.ps1` Powershell script shows how you can use familiar scripting tools and commands to automate configuring Windows services such as IIS while interacting with AWS resources. Although a simple example, this shows how to implement a common DevOps workflow of deploying an application from an object store and automating the process with a script."

If you can adapt this to be forward looking - "we are going to use a Powershell script to help us with X, Y, and Z".

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +You can use an RDP client or **Use your browser** to log into the Windows server. You will download a deployment Powershell script and the ASP.NET Core application from the S3 bucket. Downloading fil
Can you please add instructions on how to RDP from the browser to the instance?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +The deploy_iis.ps1 Powershell script automates the process of installing IIS and its management tools., configuring a new website and deploying a ASP.NET Core Razor application. Let’s break down the
```suggestion
The 1deploy_iis.ps11 Powershell script automates the process of installing IIS and its management tools., configuring a new website and deploying a ASP.NET Core Razor application. Let’s break down the script before running it.
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Set-Variable $global:ProgressPreference SilentlyContinue
```suggestion
```powershell
Set-Variable $global:ProgressPreference SilentlyContinue
```
```
I don't seem to be able to include the closing triple back-tick here, can you please make sure to add it after the command?

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +The second part of the script creates an directory for the application. The script downloads app.zip from the S3 bucket created earlier and unzips it on the directory.
```suggestion
The second part of the script creates an directory for the application. The script downloads `app.zip` from the S3 bucket created earlier and unzips it on the directory.
```

2023-06-23 19:44 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +The first cloud resource you created was an S3 bucket to store files that are accessible to cloud services. S3 is an object storage which is different from a file system which supports file read and
This is a good place to link to your piece on understanding object/file/block storage.

2023-06-23 21:03 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +description: ""
added

2023-06-23 21:03 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +**Create an instance** has several options. First, choose the **Instance location**, you can leave the default, or choose the closest AWS Region. Second, choose either Linux or Windows Server for the
simplified to only Windows

2023-06-23 21:22 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In this module, the software and deployment script is in a GitHub repository. You will clone the repository to copy the files to your local drive. The next step is to create an S3 bucket to store the
addressed

2023-06-23 21:22 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In the **Create a new bucket** page choose the **5GB storage plan** and name the bucket `practical-cloud-guide`. Select **Create Bucket**.
addressed

2023-06-27 04:18 UTC, cobusbernard requested changes
@spara, can you please confirm you have pushed your changes? The only ones I see on the PR are from the suggested ones I made and you accepted. Thanks!

2023-06-27 04:18 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +description: ""
Can you confirm you pushed the commit? It still shows "" for the description on line 3.

2023-06-27 17:16 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Select `app.zip` and `deploy_iis.ps1` from `./practical-cloud-guide-code/run-to-build/windows-app-deploy
added instructions for compiling and packaging

2023-06-27 17:21 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +```powershell
I haven't covered IAM roles yet, it's in a later post. The idea behind this tutorial is to onboard an IT Pro quickly and successfully. I've changed it so that credentials are added when the Windows VPS is launched and deleted when IIS is configured with a note that it is best practice to not leave credentials on resources that no longer need them.

2023-06-27 17:49 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +Open the AWS Console in a browser and use the search bar to find AWS Light Sail.
added statement and anchor ref to go to Module 1 if they want to start the tutorial immediately

2023-06-27 18:04 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +net stop was /y
Windows Activation Service is the part than manages application pools for IIS, w3sc restarts IIS so that the IIS manager is forced to synchs up with the newly installed IIS. Basically a reboot to make sure that the IIS manager is talking to IIS.

2023-06-27 19:32 UTC, spara commented on tutorials/practical-cloud-guide/deploy-an-asp-net-core-application-on-windows-server-with-aws-lightsail/index.md
> +In [DevOps](/concepts/devops-essentials), applications are typically built with Continuous Integration (CI) software. Code is pushed into the CI by developers where it is built and tested and release
addressed

2023-06-27 20:35 UTC, spara commented
> @spara, can you please confirm you have pushed your changes? The only ones I see on the PR are from the suggested ones I made and you accepted. Thanks!

They should be pushed by now, had to rebase because of the move from posts to tutorials

2023-06-30 16:32 UTC, cobusbernard approved these changes

2023-06-30 16:32 UTC, merged