Practical cloud guide deploy a java application on linux
build-on-aws/content pull request #446
Opened 2023-06-20 05:02 UTC by spara

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- x[ ] The title of this pull request reflects the title of my content.
- [ x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-20 17:19 UTC, cherbk approved these changes

2023-06-22 16:03 UTC, bketelsen requested changes
Small changes requested. Article looks great thanks!
Article still pending links to part 1, do not merge without them!

2023-06-22 17:19 UTC, spara commented on posts/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +The [previous tutorial]() demonstrated how to create a Windows Server VPS and deploy an ASP.NET Core application. A common and similar task is deploying a Java application on a Linux server. While Ja
addressed

2023-06-22 17:53 UTC, bketelsen approved these changes

2023-06-27 04:38 UTC, cobusbernard requested changes
Please see inline comments.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +- An AWS account: If you don't already have an account, follow the [Setting Up Your Environment](https://aws.amazon.com/getting-started/guides/setup-environment/) tutorial. For a quick overview for c
Please ensure the tracking parameters are added here.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +- An AWS account: If you don't already have an account, follow the [Setting Up Your Environment](https://aws.amazon.com/getting-started/guides/setup-environment/) tutorial. For a quick overview for c
And correct the URL, `http://%20https://` doesn't look correct.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +- AWS credentials: Follow the instructions in [Access Your Security Credentials](https://aws.amazon.com/blogs/security/how-to-find-update-access-keys-password-mfa-aws-management-console/#:~:text=Acce
And another tracking link here please.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +| 🧩 Prerequisites    | - An AWS account: If you don't already have an account, follow the [Setting Up Your Environment](https://aws.amazon.com/getting-started/guides/setup-environment/) tutorial. For
Tracking links in the next few lines as well, and also the same `http://%20https` issue.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +| 💻 Code Sample         | [GitHub](<link if you have a code sample associated with the post, otherwise delete this line>)                             |
Please update with your link to github, and remove the `<>` brackets.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +Select `HelloBuilder.jar` from the `./practical-cloud-guide-code/run-to-build
Where does this `.jar` come from? I don't see any steps showing how to compile it, and we don't include binaries in our sample code repos.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +Step 3: Create an S3 bucket
Please ensure to add a short explination here about bucket names being unique, and that you will X for this tutorial.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +![Choose File](./images/lightsail-s3-bucket-linux-1.png)
There are 3 alt-texts in a row for "choose file", can you please expand them a bit to include which file you are uploading?

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +export AWS_ACCESS_KEY_ID=<your_access_key>
Can you confirm if it is possible to use Lightsail's bucket permission system here instead of hard-coding the credentials?

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +![Choose Networking.](./images/lightsail-linux-networking-7.png)
Same here agin for the alt-text, can you please be a bit more descriptive.

2023-06-27 04:38 UTC, cobusbernard commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +In this module you deployed a Linux VPS using Lightsail. The instance was configured by providing a script to download and install the jar file and a Java JDK to run the SpringBoot application. In a
Please link to the docs.aws.amazon.com user-guide here instead of the PDP page, and also add the tracking paramters please.

2023-06-28 16:13 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +- An AWS account: If you don't already have an account, follow the [Setting Up Your Environment](https://aws.amazon.com/getting-started/guides/setup-environment/) tutorial. For a quick overview for c
tracking link added / url fixed

2023-06-28 16:13 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +| 🧩 Prerequisites    | - An AWS account: If you don't already have an account, follow the [Setting Up Your Environment](https://aws.amazon.com/getting-started/guides/setup-environment/) tutorial. For
tracking link added / url fixed

2023-06-28 16:16 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +| 💻 Code Sample         | [GitHub](<link if you have a code sample associated with the post, otherwise delete this line>)                             |
updated - note the branch still has to be merged in the build-on-aws/practical-cloud-guide-code

2023-06-28 16:19 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +Step 3: Create an S3 bucket
added

2023-06-28 16:21 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +![Choose File](./images/lightsail-s3-bucket-linux-1.png)
updated

2023-06-28 16:26 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +In this module you deployed a Linux VPS using Lightsail. The instance was configured by providing a script to download and install the jar file and a Java JDK to run the SpringBoot application. In a
updated link

2023-06-28 18:37 UTC, spara commented on tutorials/practical-cloud-guide/deploy-a-java-application-on-linux/index.md
> +export AWS_ACCESS_KEY_ID=<your_access_key>
I looked at making the jar file public read but it looks like I would have to the bucket public as well, which seems to be a major sin of late.

2023-07-07 22:07 UTC, spara commented
Added app deployment with systemd as requested. Text and images updated to reflect the changes.

2023-07-10 15:58 UTC, bketelsen approved these changes
LGTM

2023-07-10 15:59 UTC, merged