A Gentle Introduction to Transformer Architecture and Relevance to Generative AI
build-on-aws/content pull request #460
Opened 2023-06-22 20:23 UTC by Xiaoyuao988

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X ] The title of this pull request reflects the title of my content.
- [X ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X ] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```
This post is Topic #34 on the Content Plan here:
https://quip-amazon.com/pKNoAdz3MEIy/Content-Plan-for-2023-Q2-Data-Eng-DataOps-ML

```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-30 06:02 UTC, LindaHaviv requested changes
Great article! Made some minor suggested edits. Awesome work.

2023-06-30 06:02 UTC, LindaHaviv commented on posts/a-gentle-intro-to-transformer-and-gen-ai/index.md
> +
```suggestion
n conclusion, customization of pre-trained LLM models to fit your specific needs is an evolving field with numerous ongoing research efforts; hopefully, the popular techniques shared here offer valuable guidance as you embark on this exciting journey.
```

2023-06-30 06:03 UTC, LindaHaviv commented on posts/a-gentle-intro-to-transformer-and-gen-ai/index.md
> +
Also this is just a suggested sentence. Anything that just ties in the summary would help flow.

2023-06-30 06:03 UTC, LindaHaviv commented on posts/a-gentle-intro-to-transformer-and-gen-ai/index.md
> +
Another suggestion is to add a conclusion sentence at the end of the entire article

2023-07-04 21:46 UTC, Xiaoyuao988 commented on posts/a-gentle-intro-to-transformer-and-gen-ai/index.md
> +
I have updated this part.

2023-07-05 03:31 UTC, LindaHaviv approved these changes

2023-07-10 16:28 UTC, merged