generative-ai-for-retail
build-on-aws/content pull request #473
Opened 2023-06-27 09:11 UTC by eric80116

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Content for https://app.asana.com/0/inbox/1204673693062435
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-07-11 08:37 UTC, cherbk approved these changes
lgtm

2023-07-12 18:00 UTC, cobusbernard submitted a review, later dismissed
Flagging with request changes until we have the legal review.

2023-07-19 23:36 UTC, LindaHaviv requested changes
This was a fascinating piece. great job! I added some edit requests. Please don't hesitate to ping me with any questions or if you need help brainstorming specifically the scenario 1 example swap. Thank you!

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +### Scenario: Lift the limit of location and model for product images
For this scenario, can we swap the detailed model example to be something about clothes, background, products. I think it's best we avoid the beautiful vs ugly prompts about a person on an AWS blog. We can mention at end being able to do the same with models without specific prompts (like you did with the clothes, background at the end of the section). Happy to help brainstorm what to swap this example with!

I also suggest we number the step so they are easier to follow.

When mentioning things like positive/negative prompts, i recommend adding a step with something that gives context to what this means. 

For example: (specifically # 2)
1. Select the 'img2img' tab from the menu options.
2. You'll find two fields: "Positive Prompt" and "Negative Prompt". In these fields, you can specify the attributes you want in your final image.
3. In the 'Positive Prompt' field, type:  "masterpiece, etc....
etc..

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +As the festivals coming, marketing team always be busy for designing the the advertising for sales and campaigns.  It requires a substantial effort to generate diverse advertising materials. Stable d
```suggestion
As a festival season approaches, marketing teams are always busy designing advertising campaigns for sales and special events.  It requires a substantial effort to generate diverse advertising materials. Stable diffusion is a great tool for generating materials in seconds to craft your unique advertisements.
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +Take an advertisement of windbreaker as example, we will need the materials like a forest scene, a model, a product photo and eye-catching words.
```suggestion
Consider an advertisement for a windbreaker as an example. We would need materials like a forest scene, a model, a product photo, and compelling text.
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +* Select the model and choose txt2img tab on the webUI
```suggestion
1. Select the model and choose txt2img tab on the webUI
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +* Generate the materials with prompts separately.
```suggestion
2. Generate the materials with prompts separately:
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +* Then easily assemble the materials to an advertisement
```suggestion
3. Then easily assemble the materials to an advertisement
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +In many cases, users require more than just image generation from Stable Diffusion. They often need to utilize the model to generate images that feature specific products or models. For instance, con
```suggestion
In many cases, users require more than just image generation from Stable Diffusion. They often need to utilize the model to generate images that feature specific products or models. For instance, consider a scenario where a retailer collaborates with Key Opinion Leaders (KOLs) to enable them to select endorsements online then employ Stable Diffusion model that can swiftly generate product photography for sales purposes. Therefore, users require a streamlined pipeline that automates the fine-tuning of the model using their own image data. The architecture is as follows:
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +### Step1. Create an SageMaker Notebook Instance for fine-tuning
```suggestion
### Step1. Create a SageMaker Notebook Instance for fine-tuning
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +#### Install depemdencies
```suggestion
#### Install dependencies
```

2023-07-19 23:36 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +Overall, SageMaker empowers retailers with a streamlined ML platform, enabling them to leverage AI capabilities effectively and drive innovation in the retail industry. By leveraging SageMaker's quic
```suggestion
Overall, SageMaker empowers retailers with a streamlined ML platform, enabling them to leverage AI capabilities effectively and drive innovation in the retail industry. By leveraging SageMaker's quick start capabilities, reducing infrastructure management overhead, and utilizing its autoscaling features, retailers can expedite their AI initiatives. This can help deliver exceptional customer experiences, and enable them to stay competitive in the evolving retail landscape.
```

2023-07-21 04:34 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +![Picture2](images/Picture2.png)
Great job updating the scenario! To play it safe, I think it might be best to remove the picture2 image or replace it with a different image that maybe is about the clothes. The ethnicity change in the image from right to left might get misinterpreted by readers.

2023-07-21 04:46 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +According to the market research, the price of hiring a model for product photography is around $200 per hour and would raise according to how many products you need to shot. Besides the cost of venu
```suggestion
According to the market research, the price of hiring a model for product photography is around $200+ per hour and would raise according to how many products you need to shot. Besides the cost of venue, equipments and makeup, it would be a pressure for smaller retailers. Stable Diffusion can help to lift the limit of location and model for product images in seconds.
```

2023-07-21 04:51 UTC, LindaHaviv requested changes

2023-07-21 04:51 UTC, LindaHaviv commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +Amazon SageMaker is an excellent service for users seeking to harness the power of generative AI in the retail industry. With its complete machine learning capabilities and user-friendly interface, S
```suggestion
Amazon SageMaker is an excellent service for users seeking to harness the power of generative AI in the retail industry. With its complete machine learning capabilities and user-friendly interface, SageMaker empowers retailers to leverage generative AI technologies without the need for complex infrastructure provisioning or extensive data science expertise. 

Let's explore 3 solutions using SageMaker:
```

2023-07-24 18:38 UTC, damonk10 commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +The convergence of artificial intelligence (AI) and the retail industry has introduced transformative technologies like GenAI and Stable Diffusion. GenAI utilizes machine learning algorithms to gener
This paragraph is a little confusing. When you reference "GenAI", I assume you're talking about generative AI. But the retail industry didn't introduce generative AI and stable diffusion (unless I'm mistaken).

2023-07-24 22:24 UTC, eric80116 commented on posts/the-power-of-generative-ai-in-retail-industry/index.md
> +The convergence of artificial intelligence (AI) and the retail industry has introduced transformative technologies like GenAI and Stable Diffusion. GenAI utilizes machine learning algorithms to gener
Thanks for suggestion David @damonk10 , let me rewrite the introduction part to make it more clear.

2023-07-25 05:40 UTC, cherbk approved these changes

2023-07-26 18:35 UTC, cherbk approved these changes

2023-07-28 13:25 UTC, cherbk approved these changes

2023-07-28 13:31 UTC, cherbk approved these changes

2023-07-28 13:32 UTC, merged