New Tutorial: Synchronous Request-Response with Amazon API Gateway and AWS Lambda
build-on-aws/content pull request #499
Opened 2023-06-30 14:25 UTC by DennisTraub

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-06-30 14:29 UTC, DennisTraub commented
Some images can't be found in the preview. I don't know why that is the case. I've double-checked and they are all part of the PR.

2023-06-30 14:34 UTC, caller79 commented
Some image paths are incorrect, such as (images\screen-new-stack.png).

URL's use / as path separator, not \

2023-06-30 14:44 UTC, DennisTraub commented
Oh, man Windows! Thanks @caller79, I'll fix...

2023-06-30 14:49 UTC, DennisTraub commented
Done. Learning: ➡ Don't drag and drop images into your file when using Windows

2023-06-30 15:07 UTC, scribwell commented
@bketelsen This article is ready for your technical review.

2023-07-07 20:03 UTC, bketelsen requested changes

2023-07-07 20:15 UTC, DennisTraub commented on tutorials/application-integration-patterns/01-request-response-with-api-gateway/index.md
> +![](images/diagram-api-gw-lambda.png)
Oops, I must have missed that one. Added 👍

2023-07-10 15:47 UTC, bketelsen approved these changes

2023-07-10 15:48 UTC, merged