New post: Can I run existing Go applications on AWS Lambda? (Part 2)
build-on-aws/content pull request #518
Opened 2023-07-07 07:35 UTC by abhirockzz

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-07-07 16:44 UTC, scribwell commented
@cobusbernard This blog post is ready for your one-step review.

2023-07-07 18:16 UTC, bketelsen commented
this needs to be relocated into the tutorials folder like part 1 @abhirockzz

2023-07-18 16:32 UTC, jennapederson requested changes
Waiting on github repo to be completed and for first post in series to be published.

2023-07-18 16:32 UTC, jennapederson commented on posts/golang-gin-app-on-aws-lambda/index.md
> +Although we will not be discussing the application code in detail, it's important to understand the basic structure. Here is the package structure for the URL shortener application (in the [function]
Some of these github links 404 as code does not yet exist (even in the currently private repo).

2023-07-18 16:32 UTC, jennapederson commented on posts/golang-gin-app-on-aws-lambda/index.md
> +git clone TODO
These TODOs need to be completed.

2023-07-18 16:32 UTC, jennapederson commented on posts/golang-gin-app-on-aws-lambda/index.md
> +[The first part of this series](https://community.aws/posts/golang-gin-app-on-aws-lambda) introduced you to the [AWS Lambda Go API Proxy](https://github.com/awslabs/aws-lambda-go-api-proxy), and how
Links to content on this site should not use the hardcoded domain. See [here](https://github.com/build-on-aws/content/blob/main/FAQ.md#how-do-i-link-to-other-posts-on-the-communityaws-site) for examples.

Also, these will need to be updated with the path to the series folder once that is published.

2023-07-31 05:53 UTC, cobusbernard approved these changes

2023-07-31 05:54 UTC, merged