New post: Stateless Isn’t Always the Answer. Building Stateful Actor Services on AWS
build-on-aws/content pull request #521
Opened 2023-07-07 20:13 UTC by bbgu1

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X] The title of this pull request reflects the title of my content.
- [X] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X] This pull request contains one piece of content (post or page).

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-07-07 23:42 UTC, cobusbernard requested changes

2023-07-07 23:42 UTC, cobusbernard commented on posts/building-stateful-actor-services-on-aws/index.md
> +Building a stateful application with traditional microservices architecture can be challenging, but an actor model and actor-based services can provide a better solution with high concurrency and rel
Copying @damonk10's feedback from the old PR:

We need one more paragraph after this with links for the curious reader. What should they read next if they want to dive deeper?

2023-07-09 19:17 UTC, bbgu1 commented on posts/building-stateful-actor-services-on-aws/index.md
> +Building a stateful application with traditional microservices architecture can be challenging, but an actor model and actor-based services can provide a better solution with high concurrency and rel
added links for further reading material

2023-07-19 19:09 UTC, damonk10 approved these changes

2023-07-21 21:14 UTC, cobusbernard approved these changes

2023-07-21 21:46 UTC, scribwell approved these changes

2023-07-21 21:46 UTC, merged