Zero data loss disaster recovery using amazon rds
build-on-aws/content pull request #601
Opened 2023-08-03 00:53 UTC by psammy-github

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-03 00:54 UTC, psammy-github commented
ready for review

2023-08-03 02:14 UTC, setheliot commented
This is content for the Resilience Wave

2023-08-03 03:15 UTC, setheliot requested changes

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +Cloud Enabled Databases capture all changes in logs also known as transaction, binary or redo logs depending on the database engine. These logs are generally write ahead logs (WAL) so all data manipu
This is great info.  Can you add a link or two inline for anyone who wants to learn more on these concepts?

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +![RDS crash recovery](images/pic5_recovery_rds.jpg "Figure 5. RDS crash recovery")
* There is no figure 4 (I think you need to renumber these)
* Please reference the figures, using the figure numbers, from the text. It is not clear to me which text refers to your figures 5 and 6

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +The industry standard term for the amount of data loss a system can tolerate is known as the Recovery Point Objective (RPO). This is measured as a unit of time it could be seconds, hours or even days
consider linking  Recovery Point Objective (RPO) to https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/disaster-recovery-dr-objectives.html -- since you do not define it here

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +High Availability is resilience to failure of individual services such as compute and storage. AWS by nature is highly available, if an EC2 fails due to an h/w issue this can be respawned on new h/w.
optional

consider changing 

> AWS by nature is highly available

to

> AWS by nature is highly available ([as long as best practices are followed](https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/shared-responsibility-model-for-resiliency.html))

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +High Availability is resilience to failure of individual services such as compute and storage. AWS by nature is highly available, if an EC2 fails due to an h/w issue this can be respawned on new h/w.
> If an RDS Database is setup to run as Multi AZ, RDS will automatically failover to a Disaster Recovery Site if one exists 

I am not sure I understand this.

If it is setup to run as Multi-AZ then the recovery AZ will exist.  So what do you man by "if one exists"?

Also maybe specify that the disaster recovery site in this case is the AZ, just to make it clear

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +Backups in Amazon RDS are based on EC2 Storage level Snapshots and for Cloud Enabled offerings this is coupled with transaction log backups every 5 minutes all automated when enabled and implicitly w
"EC2 instance storage level..." may be clearer

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +Cloud Enabled Databases run using similar infrastructure and setup as if they were running on premise. In a way they are databases designed for an on premise environment and tailored to run on the cl
ok, I see you use the cloud enabled and cloud native throughout the remainder of the article.  I do not want to cause a major disruption.  If you are happy with it, and cannot think of a replacement, then I am fine with it

2023-08-03 03:15 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +The Hybrid Cloud Native Amazon Aurora backups are continuous and based on its intelligent storage clustered setup and how data changes are recorded, due to this we should be able to restore an Aurora
would "persisted to disks across all 3 AZs mentioned earlier" (plural disks) be clearer?

2023-08-03 03:23 UTC, setheliot requested changes

2023-08-03 03:23 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +| Amazon Aurora MySQL          | Multi AZ Clustered | Implicit                                         | Yes                                                    | No
are you sure that Aurora Multi-AZ replication is synchronous?   This indicates it is asynchronous  https://aws.amazon.com/rds/features/read-replicas/

2023-08-04 02:01 UTC, setheliot approved these changes

2023-08-04 11:28 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +  - https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-options-in-the-cloud.htm
Fixed and all links are not MD compliant

2023-08-04 11:29 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> + Amazon RDS Disaster Recovery Data Loss scope is at the database level and measureable in time or database system change. We recovery the database and everything contained within to the same consiste
- It should be recover, updated
- I've added a sentence to explain what database system change is and it will be discussed later in blog

2023-08-04 11:31 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +![RDS Multi AZ Clustered](images/pic2_az_clustered.jpg "Figure 3. RDS Multi AZ Clustered")
Very good point, this has been updated in text and diagram, diagram will be show when I perform a new pull, for some  reason its not showing on the automated pull preview

2023-08-04 11:32 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +Cloud Enabled Databases capture all changes in logs also known as transaction, binary or redo logs depending on the database engine. These logs are generally write ahead logs (WAL) so all data manipu
added a link to wikipedia on WAL

2023-08-04 11:32 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +![RDS crash recovery](images/pic5_recovery_rds.jpg "Figure 5. RDS crash recovery")
images all relabelled to have an correct order with no gaps

2023-08-04 11:32 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +The industry standard term for the amount of data loss a system can tolerate is known as the Recovery Point Objective (RPO). This is measured as a unit of time it could be seconds, hours or even days
Done

2023-08-04 11:33 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +High Availability is resilience to failure of individual services such as compute and storage. AWS by nature is highly available, if an EC2 fails due to an h/w issue this can be respawned on new h/w.
- Added link for HA best practice and updated wording
- Agree the Multi AZ sentence is worded badly I've changed it

2023-08-04 11:34 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +The Hybrid Cloud Native Amazon Aurora backups are continuous and based on its intelligent storage clustered setup and how data changes are recorded, due to this we should be able to restore an Aurora
I've Updated text for same

2023-08-04 11:34 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +| Amazon Aurora MySQL          | Multi AZ Clustered | Implicit                                         | Yes                                                    | No
This came as a surprise to me, text and tables updated to reflect the same

2023-08-04 12:32 UTC, TimGustafson requested changes
I will send an e-mail with more details.

2023-08-04 13:02 UTC, psammy-github commented on posts/zero-dataloss-dr-using-rds/index.md
> +Backups in Amazon RDS are based on EC2 Storage level Snapshots and for Cloud Enabled offerings this is coupled with transaction log backups every 5 minutes all automated when enabled and implicitly w
updated

2023-08-10 15:55 UTC, damonk10 commented on posts/zero-dataloss-dr-using-rds/index.md
> +To restore an RDS hybrid cloud native database would need a restore of the full backup + incremental backup(s), there are no transaction logs to restore, we should expect an RPO of 0 under normal cir
This needs to be broken into at least 2 sentences (probably 3). It's just very hard to follow.

2023-08-10 15:55 UTC, damonk10 commented on posts/zero-dataloss-dr-using-rds/index.md
> +A replica in Amazon RDS or Amazon Aurora represents a database that also has the potential to be used as an additional read only copy of the live database while still being continually updated with a
Not tracking with this sentence: "Hence with this database engine we can also have the replica in recovery mode only not accessible for read only access where that license fee is then not required this is called a mounted replica." Probably break it into two simpler sentences.

2023-08-17 20:17 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +RDS Cloud Native databases, namely Amazon Aurora, use a clustered log structured distributed storage system. This means once a change has occurred in the database, the log records are sent to the sto
This sentence was removed in a subsequent edit

2023-08-17 20:17 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +To restore an RDS hybrid cloud native database would need a restore of the full backup + incremental backup(s), there are no transaction logs to restore, we should expect an RPO of 0 under normal cir
done

2023-08-17 20:18 UTC, setheliot commented on posts/zero-dataloss-dr-using-rds/index.md
> +A replica in Amazon RDS or Amazon Aurora represents a database that also has the potential to be used as an additional read only copy of the live database while still being continually updated with a
fixed

2023-08-17 22:11 UTC, lenadroid commented
Seems like PR is approved and can be merged @cherbk @setheliot

2023-08-18 14:50 UTC, merged