New Post: How to Use Proprietary Foundation Models with Amazon SageMaker JumpStart for Building Generative AI Applications
build-on-aws/content pull request #602
Opened 2023-08-03 05:14 UTC by channy

…ker JumpStart for Building Generative AI Applications

Amazon SageMaker JumpStart supports popular proprietary foundation models, such as AI21 Labs, Cohere, and LightOn. In this blog post, learn how to use a preview feature, a playground of AWS console and deploy to SageMaker Studio. You can test these models without writing a single line of code and easily evaluate models on your specific tasks.

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-03 10:44 UTC, mikegc-aws commented
Thanks for this post.  Here are some review feedback notes: 

- Please can you add your images into an ./images folder and reference them from there.
- [25] "you can simply create an image on the right by feeding the sentence" It does not show in the right in my view.  Its underneath.  Should we maybe just reference the image more generally? 
- [81] Code - Does that code run?  Looks like the ARN has a dummy account number in it.  Correct me if I'm wrong, but is that not supposed to be an account number for the SageMaker service account, and as such fine to be public.  In any case can we clarify if this is 'example code' that can't be run as is. 
- [81] Code - The sample code will spin up a `g5.xlarge` instance, which runs around $1 an hour.  Can we advise readers to investigate the costs, and include instructions on how to clean up afterwards and remove the endpoint.

2023-08-04 00:13 UTC, cobusbernard requested changes

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +![](https://d2908q01vomqb2.cloudfront.net/da4b9237bacccdf19c0760cab7aec4a8359010b0/2023/03/16/2023-generative-ai-sagemaker-1.jpg)
Can you please add alt-text in the `[]` please for all images @channy ?

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +  - generative-ai
```suggestion
  - gen-ai
```

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +![](https://d2908q01vomqb2.cloudfront.net/da4b9237bacccdf19c0760cab7aec4a8359010b0/2023/03/16/2023-generative-ai-sagemaker-1.jpg)
Also, can you please add the images to the `images` folder of you post?

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +Channy Yun is a Principal Developer Advocate for AWS, and passionate about helping developers to build modern applications on latest AWS services. A pragmatic developer and blogger at heart, he loves
Can you change your twitter handle to be a link to your profile on twitter please?

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +For a variety of tutorials and tips and tricks related to this language model, see [Cohere brings language AI to Amazon SageMaker](https://aws.amazon.com/ko/blogs/machine-learning/cohere-brings-langu
```suggestion
For a variety of tutorials and tips and tricks related to this language model, see [Cohere brings language AI to Amazon SageMaker](https://aws.amazon.com/blogs/machine-learning/cohere-brings-language-ai-to-amazon-sagemaker/) in the AWS Machine Learning Blog. You can also see an [example of automated quiz generation with AWS Certification exams](https://aws.amazon.com/blogs/machine-learning/accelerate-your-learning-towards-aws-certification-exams-with-automated-quiz-generation-using-amazon-sagemaker-foundations-models/) using AI21 Jurassic-2 Jumbo Instruct model.
```

2023-08-04 00:13 UTC, cobusbernard commented on posts/how-to-use-proprietary-foundation-models-with-amazon-sagemaker-jumpstart-for-building-generative-ai-applications/index.md
> +  - generative-ai
Can you also please add a tag for "sagemaker"?

2023-08-04 01:25 UTC, channy commented
Thanks mikegc-aws and cobusbernard! Incorporated your feedback.

2023-08-04 16:48 UTC, cobusbernard approved these changes

2023-08-04 16:54 UTC, cobusbernard approved these changes

2023-08-04 16:54 UTC, merged