Solving Problems You Can't See: Using AWS X-Ray and CloudWatch for user-level observability in your serverless microservices applications
build-on-aws/content pull request #603
Opened 2023-08-03 15:28 UTC by knizami

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x ] The title of this pull request reflects the title of my content.
- [x ] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-03 16:10 UTC, knizami commented
Quip version is here.  Reviewed by @bketelsen: 

https://quip-amazon.com/mEFvAjXX8MmX/How-to-group-measure-and-alarm-on-user-requests-in-a-serverless-microservices-architecture-using-X-Ray-and-CloudWatch-WORKING-DRAFT

2023-08-03 16:11 UTC, knizami commented
One question on the port.  I was highlighting parts of my code blocks in Quip but I don't see a way to do this in markdown.  Let me know your thoughts on this.

2023-08-03 16:16 UTC, knizami commented
Also, this may be more appropriate as a tutorial given its length, walkthrough guidance (reproducibility), and flow?

2023-08-17 21:07 UTC, scribwell commented
@bketelsen Would you please perform the technical review for this article? Also, we'll need to reformat this as a tutorial as it was incorrectly classified as a blog post. Please work with the author to ensure this article is using the correct format.

2023-08-21 16:09 UTC, bketelsen requested changes
This is an excellent and thorough article on X-ray and Cloudwatch. Left several comments, mostly related to code formatting.  Please remove all the `*`'s in the code blocks and annotate all the code blocks with the language used.

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +import ***CartButton* **from "@/components/CartButton.vue";
remove all the extraneous `*` symbols here. the syntax highlighter will highlight these appropriately if they're annotated with the `javascript` tag in the codeblock.

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
and remove all the extra `*`'s here too!

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +        headers => **API****.get("CartAPI", "/cart", {
remove extra `*`'s here too.

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**  computed: {
remove extra `*` here too

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**        name: "CartAPI",
remove these `*`

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**@tracer.capture_lambda_handler
remove these *

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +        headers => **API****.get("CartAPI", "/cart", {
remove these *

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**from aws_xray_sdk.core import xray_recorder
remove these `*`

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
add `python` tag here. like ```python

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**
remove all these `*`

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
add `python` annotation here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**@tracer.capture_method
remove * here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +fields *@log*, *@timestamp*, *@message*
remove the *'s here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +| filter *@message* like "05bf2f42-cd3b-4e4b-8876-f97b022525be" or @requestId = "c2eac3ec-d724-496c-9eb0-a112dc2c459d" or *@message* like "1-6470a77f-746c4b830dc79084524259da"
and here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +| sort *@timestamp*, *@message* desc
and here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**    for index, product in enumerate(product_list):
remove all these `*`

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
add python tag here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
add python tag here

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**    try:
remove **'s throughout

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**from time import sleep
remove **'s throughout

2023-08-21 16:09 UTC, bketelsen commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
add python annotation

2023-08-31 18:48 UTC, bketelsen commented
Needs to be moved to tutorials folder, use correct template.

2023-09-03 15:33 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
done.

2023-09-03 15:33 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
done.

2023-09-03 15:33 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +import ***CartButton* **from "@/components/CartButton.vue";
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +        headers => **API****.get("CartAPI", "/cart", {
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**  computed: {
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**    try:
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +**from time import sleep
done.

2023-09-03 15:34 UTC, knizami commented on posts/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +```
done.

2023-09-03 16:18 UTC, knizami commented
I've moved this to the tutorial section and cleaned up the content.  I'm going to do another dry run to make sure everything flows well and provide some additional minor edits.

2023-09-06 19:00 UTC, bketelsen commented
@knizami please remove the `.idea` folder that was committed, these are IDE specific files for your editor.

2023-09-06 19:10 UTC, bketelsen approved these changes

2023-09-06 19:33 UTC, scribwell commented
@damonk10 I've assigned this tutorial to 8112 for editorial review.

2023-09-08 16:00 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map-node-view.png
I can't see this image. It's unavailable.

2023-09-08 16:01 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-service-map.png
Screenshot of Service map with diagram of many possible scenarios starting from client icon to Application stage. From there, possible scenarios lead to Lambda content and Lambda Function and Dynamo.

2023-09-08 16:02 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-list.png
Image of Traces table showing OK status.

2023-09-08 16:03 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-map.png
Image of Trace Map with Legend and options box, highlighting Lambda Function.

2023-09-08 16:04 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-traces-view.png
Image of Traces table showing OK status.

2023-09-08 16:05 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-view-filtered-traces-select-segment-with-error.png
Image of Segments Timeline highlighting Lamda link with Error warning.

2023-09-08 16:05 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/x-ray-view-filtered-traces.png
Image showing segment details of shopping cart, highlighting Fault.

2023-09-08 16:13 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +title: Solving Problems You Can't See - Using AWS X-Ray and CloudWatch for user-level observability in your serverless microservices applications
```suggestion
title: Solve Problems You Can't See- How AWS X-Ray and CloudWatch Help You Save Stranded Users
```

2023-09-08 16:15 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +description: Learn how to use AWS X-Ray to trace and observe your user interactions in a serverless microservices application built on AWS.
```suggestion
description: Observe users in serverless microservices applications built on AWS.
```

2023-09-08 16:20 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +---
Hello! This is an excellent blog! Great job with the intro. You set up the scene nicely and it invites the reader. The structure is solid too. You have a friendly voice and conversational tone in the piece that plays well with the aphorisms. 

For my edits I added contractions here and there to make it more conversational. I tightened some sentences to eliminate overuse of "that", so it reads more fluidly. 

Since the links are embedded into the copy I removed the brackets ONLY when the links are part of a complete sentence. It makes the blog easier to read digitally. I also capitalized titles and proper nouns. 

Overall, well done!

2023-09-08 19:45 UTC, scribwell commented
@knizami Please review our our editor's suggestions/revisions and let us know when you've completed all revisions so we can send this through final review and get it published!

2023-09-11 01:09 UTC, knizami commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/images/aws-x-ray-cloudwatch-group-count-create-alarm-2.png
Hi not sure about this comment?

2023-09-11 01:28 UTC, knizami commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +title: Solving Problems You Can't See - Using AWS X-Ray and CloudWatch for user-level observability in your serverless microservices applications
Hi, I think its important that we include "observability" and "serverless microservices applications" as these statements provide specificity for the tutorial.   We could shorten it to:
Solving Problems You Can't See- How AWS X-Ray and CloudWatch for can provide observability in your serverless microservices applications
 
or something similar

2023-09-11 01:31 UTC, knizami commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +---
Thank you for all your edits.  The only concern I have is with making the title too general because then its harder for the reader to understand what they will learn.  Also I believe there were 2 images that you found that you said were unavailable?  I am not sure what the issue is there, these are showing up on my version.

2023-09-11 01:31 UTC, knizami commented
> 

editorial changes reviewed.

2023-09-13 15:53 UTC, DalM2023 reviewed
Second review done. Ready for review.

2023-09-13 15:53 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +You can see that the query is looking for either the API Gateway request id, AWS Lambda Function request id, or the AWS X-Ray trace id in the message.   When you log messages with the **aws_lambda_po
```suggestion
You can see that the query is looking for either the API Gateway request id, AWS Lambda Function request id, or the AWS X-Ray trace ID in the message.   When you log messages with the **aws_lambda_powertools** logger and you have also instrumented your function to use AWS X-Ray, it will automatically enrich the log messages with the AWS X-Ray trace ID.  However, the exception that was thrown was not logged using the logger and therefore didn’t include the X-Ray trace id.  You can confirm this by proceeding to the logs for the **aws-serverless-shopping-cart-shop-ListCartFunction-\<hash>** AWS Lambda function and viewing the exception message in the logs:  
```

2023-09-13 15:53 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +The exception was caused by incorrectly using the `remove()` python list function on the individual product dictionary.  Next, you will fix this error and also improve the exception handling for the
```suggestion
The exception was caused by incorrectly using the `remove()` python list function on the individual product dictionary.  Next, you will fix this error and also improve the exception handling for the function by wrapping the execution in a try / except block:
```
```suggestion
The exception was caused by incorrectly using the `remove()` Python list function on the individual product dictionary.  Next, you will fix this error and also improve the exception handling for the function by wrapping the execution in a try / except block:
```

2023-09-13 15:53 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +title: Solving Problems You Can't See - Using AWS X-Ray and CloudWatch for user-level observability in your serverless microservices applications
Got it. So, please rewrite the descriptor. The title and the descriptor don't need to repeat each other. 

Keep the title in AP Style: "Solving Problems You Can’t See- How AWS X-Ray and CloudWatch Provide Observability in Serverless Microservices Applications".

Then, rewrite the descriptor without the words "observability" and "serverless microservices applications". It should also be written at 60 characters. 

Something like: 
EX: Avoid blind spots by tracking users on apps built on AWS.

2023-09-13 15:53 UTC, DalM2023 commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +---
See my notes below on the title and descriptor. 

I still can't see all the images. No idea why. But I trust your end's technology more than mine.

2023-09-13 17:37 UTC, scribwell commented
@knizami We have a few more author revisions/edits for you to review before we can publish. Would you please review?

2023-09-13 18:24 UTC, knizami commented on tutorials/solving-problems-you-cant-see-using-aws-x-ray-and-cloudwatch-for-user-level-observability-in-your-serverless-microservices-applications/index.md
> +| ToC |
Hi, not sure @scribwell ?

2023-09-13 18:32 UTC, knizami commented
Thanks @DalM2023 for the excellent review / update.  I incorporated your changes for the title / descriptor.  @scribwell can we confirm that images that @DalM2023 is having problems viewing are not a problem in general?  I am able to see all the images load.

2023-09-18 15:21 UTC, scribwell commented
@damonk10 Please perform the final review and ensure there are no issues with the images before publishing.

2023-09-26 15:04 UTC, damonk10 approved these changes

2023-09-26 15:06 UTC, damonk10 approved these changes

2023-09-26 15:06 UTC, merged