Topic and queue workflow code examples
build-on-aws/content pull request #612
Opened 2023-08-08 12:57 UTC by meyertst-aws

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

This is the link to related Asana task generated by my content proposal.

https://app.asana.com/0/0/1205186474707246/f

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-09 17:53 UTC, riferrei requested changes

2023-08-09 17:53 UTC, riferrei commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +You can publish and subscribe using Amazon SNS alone. But combining Amazon SNS with Amazon SQS gives you greater flexibility in how the messages are consumed.
This paragraph may use additional context. It leaves the reader with a taste for more regarding what are the benefits. Could you explain with extra paragraphs what are the benefits, and what the reader could lose if not using both?

2023-08-09 17:53 UTC, riferrei commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +Also, the messages stay in the queue until you delete them. This gives you more flexibility in how the messages are processed.
> Also, the messages stay in the queue until you delete them

Maybe you can expand a bit more on this and share the benefits of this design? For example, giving consumers the ability to process messages way later than the writing occurs.

2023-08-09 17:53 UTC, riferrei commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +Below is a description of the application interface.
This sentence is a bit confusing in this blog post. Maybe this was supposed to be a header?

2023-08-09 17:53 UTC, riferrei commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +### Create an SNS topic
From this point on there is something crucial to change in this blog post. Although it's clear that the sample code is implemented in multiple programming languages, it is not clear from this blog post how to get things started. For instance, if I wanted to create a SNS topic using Go, which folder in the code sample I should go?

Note that this question may sound obvious, given that the README.md of the repo literally contains a table with the different programming languages and their folders. But the essence of the question is how the reader could follow up with the example without jumping out of the reading process to "look outside" the blog post. As much as possible, we want the reader to keep reading and consume the content without interruptions.

As a suggestion, pick one programming language to run all the examples, stick with it throughout the blog post, and explain that other programming languages are also supported. This will lead to a superior learning experience for the reader.

2023-08-09 17:53 UTC, riferrei commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +Deduplication is only available for FIFO topics. Deduplication prevents the subscriber from responding more than once to events that are determined to be duplicates.
May be useful to explain what deduplication means.

2023-08-11 20:12 UTC, cherbk approved these changes

2023-08-14 12:20 UTC, meyertst-aws commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +Also, the messages stay in the queue until you delete them. This gives you more flexibility in how the messages are processed.
I made some changes. Added sentences to bring some clarity.

2023-08-14 12:21 UTC, meyertst-aws commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +### Create an SNS topic
I added a section here explaining how to get started.

2023-08-14 12:22 UTC, meyertst-aws commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +### Create two SQS queues
I added some explanation.,

2023-08-14 12:22 UTC, meyertst-aws commented on posts/topics_and_queues_workflow_with_sdks/index.md
> +Below is a description of the application interface.
I tried to make this clearer, and made some changes.

2023-08-21 14:05 UTC, cherbk approved these changes

2023-08-21 14:07 UTC, merged