first draft for building-multi-region-disaster-recovery-for-amazon-appstream2.0
build-on-aws/content pull request #636
Opened 2023-08-16 16:24 UTC by Peter-John-M

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-16 19:33 UTC, scribwell commented
@setheliot This article is ready for your technical review.

2023-08-25 01:57 UTC, setheliot requested changes
I left some comments on the intro and outro, but I did NOT review the steps themselves other than to scan them for written clarity.

I would recommend that if possible you have a colleague in end user computing walk through the steps and tell you any difficulties our errors

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +  - disaster recovery
disaster-recovery

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +tags:
add "resilience"

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +  - appstream 2.0
this would be a new tag, but no spaces or dots allowed, would just "appstream" be ok?

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +  - end user computing
end-user-computing

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +description: "A step by step guide on how to build multi region disaster recovery environment for Amazon AppStream 2.0 using FSLogix CloudCache a user profile containerization and replication softwar
multi-region (like you did in the title).

Note that AWS convention is to capitalize "Region", so multi-Region, but it is optional if you want to follow that here

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +spaces:
delete the spaces and its value -- we do no have a space defined for end-user-computing.  We may in the future.  I may add this to the resilience space, but that is not yet configured

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +Figure 1 shows the components and traffic flow for the solution.
For all figures and captions you can do this instead

To show images in your post, you'll link to them using a relative path:

```
![Put your alt-text here](images/the-internet.jpg "Put your image title/caption here")
```

The caption will appear underneath the image and also on mouse over.

This and other shortcuts can be found here: https://github.com/build-on-aws/content/blob/bef4d1843d0eb67981cfb0e5e5ff6af8a106b679/FAQ.md

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +While these are excellent solutions, there are customers that require the user profile sizes to be larger than the 1GB limit of Amazon AppStream 2.0 App Settings Persistence feature and be able to dy
> While these are excellent solutions, there are customers that require t

Can give more detail why the above solutions do not work in these cases?

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +### Prerequisites
I think this should be `##` 

`##` is your top-level header (you should not use `#`)

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +# Deploy the solution
make this H2 `##`, and adjust the headers under it

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +# Conclusion
`##`

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +## Step 1: Setup file and folder permissions
all steps should be `###`

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +
add `## Introduction`

2023-08-25 01:57 UTC, setheliot commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +*Figure 11: EC2 Windows File Explorer Adding Documents to user profile*
is showing the desktop an artistic choice?  Can we trim to just the window for all of these?  your call

2023-08-27 14:16 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +  - appstream 2.0
Perfect, appstream can work.

2023-08-27 14:29 UTC, Peter-John-M commented
> 

Thanks, I have had a Snr Solutions Architect from EUC team run through steps and he gave some good feedback:
I followed the steps in order to test DR capabilities using FSLogix Cloud Cache. it performs well. Please find below some details to add:
-Step2 :
*Before cloning the ACLs, add a step to create the Profiles folder in DR FSx
*Missing ' in the Set-ACL
**Get-ACl -Path '\\fsxprimary.asx.local\D$\Profiles' | Set-ACL \\fsxdr.asx.local\D$\Profiles'
*We have to setup share permission as well into the DR fsx step 2.

-Step4:
*j. looks like it is called flip flop Profile directory Name in my case
*Add a note that this is important to disable the VHDLocations and use only CCDLocations.
---
I have added these changes prior to submitting my first draft here. Will work on the other comments and update you as soon as done.

Thanks for the review.

2023-08-27 15:02 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +*Figure 11: EC2 Windows File Explorer Adding Documents to user profile*
Yes, you are correct for image 10 and 12, I can trim them out but image 11 (this image) I would like to keep it for context because it shows the tool bar of AppStream instance at the top. Image 10 and 12, I will go ahead and trim it out, as its not needed here.

2023-08-27 15:13 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +*Figure 11: EC2 Windows File Explorer Adding Documents to user profile*
I trimmed image 11 to remove the desktop but but kept the AppStream toolbar at the top.

2023-08-27 15:33 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +  - end user computing
Done

2023-08-27 15:43 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +description: "A step by step guide on how to build multi region disaster recovery environment for Amazon AppStream 2.0 using FSLogix CloudCache a user profile containerization and replication softwar
I have made the title all caps on the first letter so that Region does not stand out too much.
Current:
"Building a Multi-Region Disaster Recovery Environment for Amazon AppStream 2.0"

Compared to:
"Building a multi-region disaster recovery environment for Amazon AppStream 2.0"

Added the capital R in multi-Region as per the AWS convention.
description: "A step by step guide on how to build a multi-Region disaster recovery environment for Amazon AppStream 2.0 using FSLogix CloudCache user profile containerization and replication software."

2023-08-27 15:46 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +# Deploy the solution
Added ## to Deploy the solution and changed all heading below to ### .

2023-08-27 15:47 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +# Conclusion
Added ## to conclusion.

2023-08-27 15:47 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +## Step 1: Setup file and folder permissions
Done

2023-08-27 15:48 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +
Added ## Introduction on line 17 after date.

2023-08-29 17:03 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +Figure 1 shows the components and traffic flow for the solution.
Mouse over and alt text is working now, thank you for catching this.

2023-08-30 16:41 UTC, setheliot approved these changes

2023-08-30 16:42 UTC, setheliot commented
@scribwell - all good - ready to merge.  Note it has been soft-failing preview builds, so be aware it may have build issues when we push to prod

2023-09-01 23:59 UTC, cobusbernard commented
@setheliot , I don't see an editorial review done for this one yet, have flagged to be reviewed.

2023-09-02 00:05 UTC, setheliot commented
> @setheliot , I don't see an editorial review done for this one yet, have flagged to be reviewed.

you are correct.  Sorry for the error

2023-09-06 14:25 UTC, scribwell commented
@damonk10 Technical review is complete and I've assigned to 8112 for editorial review.

2023-09-08 19:15 UTC, DalM2023 reviewed
First round edit. Ready for review.

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +5.  End the Amazon AppStream 2.0 streaming session
```suggestion
5.  End the Amazon AppStream 2.0 streaming session.
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +7.  Connect to your Okta DR application, in my example it the Okta
```suggestion
7.  Connect to your Okta DR application, in my example the Okta
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +    application would be called “AppStream 2.0 DR”
```suggestion
    application would be called “AppStream 2.0 DR”.
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +    region
```suggestion
    region.
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +    to your primary region
```suggestion
    to your primary region.
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +### Clean-up:
Clean-Up

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +resources and reverse changes you made, you can complete the following
```suggestion
resources and reverse changes you made, complete the following
```

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +
Consider adding a link or two to other blogs that speak to this topic.
EX: "Learn more about XYZ..."

2023-09-08 19:15 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +description: "A step by step guide on how to build a multi-Region disaster recovery environment for Amazon AppStream 2.0 using FSLogix CloudCache user profile containerization and replication softwar
```suggestion
Trimmed to accomodate less characters for easier "hook":
A guide on FSLogix CloudCache and replication software for resilience. 

```

2023-09-08 19:18 UTC, DalM2023 reviewed
Forgot to add personal note...

2023-09-08 19:18 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +---
Hello! This is a very important topic. It's got good structure and easy to follow steps. I made some suggestions on breaking up the intro. I corrected titles to match AP Style and made a couple of tweaks. Overall, it's pretty solid and didn't need much tinkering. 

Good job! 👏

2023-09-08 19:48 UTC, scribwell commented
@Peter-John-M Please review our our editor's suggestions/revisions and let us know when you've completed all revisions so we can send this through final review and get it published!

2023-09-10 15:11 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +---
Thank you very much! Appreciate your review, and I have completed all suggested revisions. 
I showed the architecture diagram to a friend who has an AWS cloud practitioner certification but does not work in AWS daily. 
He suggested I add some arrows and labels to make things more clear to a non AWS\wider audience. (done)
All is looking good now, looking forward to final review.

2023-09-11 16:17 UTC, DalM2023 reviewed
2nd edit done. Author needs to make updates to fit AP Style.

2023-09-11 16:17 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +title: "Building a multi-region disaster recovery environment for Amazon AppStream 2.0"
```suggestion
title: "Building a Multi-Region Disaster Recovery Environment for Amazon AppStream 2.0"
```

2023-09-11 16:17 UTC, DalM2023 commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +---
This is solid! The only thing is that I didn't see the titles updated to AP Style. That's part of Amazon's publishing guide.  Once those updates are done, this will be ready to publish.

2023-09-11 17:26 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/images/image4.png
Done!

2023-09-11 17:31 UTC, Peter-John-M reviewed
AP style changes complete.

2023-09-12 21:26 UTC, scribwell commented
@damonk10 This article is ready for your final review.

2023-09-19 15:17 UTC, Peter-John-M commented on tutorials/building-multi-region-disaster-recovery-for-amazon-appstream2.0/index.md
> +---
Done!

2023-09-25 14:31 UTC, damonk10 approved these changes

2023-09-25 14:32 UTC, merged