[New Tutorial] How to Setup Replication Lag Monitoring for Amazon DynamoDB GlobalTables
build-on-aws/content pull request #641
Opened 2023-08-16 22:20 UTC by crichey

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-17 18:21 UTC, scribwell commented
@setheliot This article is ready for your technical review.

2023-08-17 19:55 UTC, setheliot requested changes
Looks good!  There are some updates I would like to see -- let me know if you have any questions

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +date: 2023-07-05
update

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +![Picture of CloudWatch menu expanded, with All Metrics Circled](./ss1.png)
OPTIONAL: You can add captions to figures using the syntax shown here: https://github.com/build-on-aws/content/blob/main/FAQ.md#how-do-i-show-images-in-my-post

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +description: "A bad day with a car provides a better understanding of gray failures"
update description

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +[Amazon DynamoDB GlobalTables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html) provides a fully managed, multi-Region, and multi-active database option that delive
For all links to aws sites, please add tracking tags 

```
?sc_channel=el&sc_campaign=resiliencewave&sc_geo=mult&sc_country=mult&sc_outcome=acq&sc_content=ddb-globaltables-lag
```

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +# How to Setup Replication Lag Monitoring for Amazon DynamoDB GlobalTables
delete this line -- Title will be auto-generated from the one you put into the header

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +[Amazon DynamoDB GlobalTables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html) provides a fully managed, multi-Region, and multi-active database option that delive
> [disaster](https://aws.amazon.com/what-is/disaster-recovery/)

optional: that is generally a good definition on that site.  However it is a site created by the DRS team and as such ONLY mentions DRS.  The DR whitepaper here https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/what-is-a-disaster.html gives solutions using native technologies or using DRS

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +[Amazon DynamoDB GlobalTables](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GlobalTables.html) provides a fully managed, multi-Region, and multi-active database option that delive
Your Intro paragraph is clear and well-written.  But I think the post would benefit from putting the problem statement up-front.  What is the problem you will solve here and why is it important?  Something about why we want to minimize data loss and how increased latencies pose a threat to that

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +This tutorial assumes that you have already [created a DynamoDB GlobalTable](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/V2globaltables.tutorial.html). There are no other prerequ
why say "There are no other prerequisites."?

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +![Picture of CloudWatch menu expanded, with All Metrics Circled](./ss1.png)
for `ss1.png` please do the following
* crop the odd whitespace around your screen shot
* use something "neater" then freehand pen as a highlight (such as an oval,  square, or arrow)

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +**Important** Ensure you are in the same AWS Region as your GlobalTable!
do you mean "source table"?

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +![Zoomed in image of Filter By field populated with TableName =](./ss4.png)
add a CR after any image

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +## Step 4
should be H3 `###`

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +In the menu on the left side of the console screen empand the alarms section under CloudWatch and click on *All Alarms*. Next, click on the *Create Alarm* button on the top right of the screen. Then,
`[Step 2](#Step 2)` does not work.  Maybe try `[Step 2](#step-2)`, and test it

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable!
which is important why?

2023-08-17 19:55 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable!
> Use the same information you used in [Step 2]

This is not clear.  By same information do you mean using the metric you created in Step 2?

2023-08-17 20:50 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable!
3 minutes seems long -- can you reach out to the blog authors to understand why they chose that?

2023-08-22 17:51 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable!
3 min is a guideline that was put there because the feeling in the DB side of the house is that there isn't a lot you can do to change this....you could stand up a new table in another region which may or may not solve the problem and it will cost $. So, wait until things look really bad before acting

2023-08-22 18:53 UTC, setheliot requested changes
just some minor tweaks

2023-08-22 18:53 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +# How to Setup Replication Lag Monitoring for Amazon DynamoDB GlobalTables
please delete this line :-) 

> # How to Setup Replication Lag Monitoring for Amazon DynamoDB GlobalTables

2023-08-22 18:53 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +DynamoDB GlobalTables provide a fully managed, multi-Region, and multi-active database option that delivers fast and localized read and write performance for massively scaled global applications. Thi
please remove trailing `/` after tag, here anywhere else

> `&sc_content=ddb-globaltables-lag/`

2023-08-22 18:53 UTC, setheliot commented on tutorials/ddb-globaltables-lag/ddb-global-replication-lag.bak
> +# Monitoring Replication Lag with DynamoDB Global Tables #
delete backup file

2023-08-30 16:27 UTC, setheliot commented
> @setheliot Please review Clark's changes and let me know when this technical review is complete.

Ball is in @crichey 's court -- I had some final asks still pending -- see above

2023-08-30 18:05 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +**Important** Ensure you are in the same AWS Region as your GlobalTable!
source GlobalTable

2023-08-30 18:11 UTC, crichey commented
Oops. Fixed and pushed Sent from my iPhoneOn Aug 30, 2023, at 12:27, Seth Eliot ***@***.***> wrote:﻿

@setheliot Please review Clark's changes and let me know when this technical review is complete.

Ball is in @crichey 's court -- I had some final asks still pending -- see above

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-30 18:20 UTC, setheliot approved these changes

2023-08-30 19:21 UTC, scribwell commented
@damonk10 This tutorial is ready for 8112's editorial review. I've shared with them in Chime and updated the Asana task.

2023-09-11 18:34 UTC, DalM2023 reviewed
1st round edit. Please review.

2023-09-11 20:42 UTC, setheliot commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +authorGithubAlias: crichey
@crichey please add 
```
waves:
  - resilience
```

Do not add spaces yet

2023-09-12 14:12 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +In this case, you can see that the console is helpfully suggesting the name of an existing DynamoDB GlobalTable that I have setup. Choose one of the suggestions or simply type in your table name and
GlobalTable is the technical name for this special type of table. All one word, capitalized

2023-09-12 14:12 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable! Monitoring the replication latency will help to ensure that you are getting the lowest RPO possible in the eve
GlobalTable is the technical name, all one word

2023-09-12 14:19 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +description: "A step by step tutorial on how to setup replication lag monitoring for Amazon DynamoDB GlobalTables"
kept required description tag but implemented suggested description change

2023-09-12 14:24 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +---
agreed, good catch. I found several other instances in the post as well and fixed those.

2023-09-12 14:24 UTC, crichey commented on tutorials/ddb-globaltables-lag/configuring ddb replication metric.md
> +That's it! You've created a dashboard widget and an alarm for your DynamoDB GlobalTable! Monitoring the replication latency will help to ensure that you are getting the lowest RPO possible in the eve
done

2023-09-12 16:40 UTC, merged