Stress Testing in the Cloud
build-on-aws/content pull request #643
Opened 2023-08-17 10:26 UTC by aws-veliswaboya

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-17 13:37 UTC, scribwell commented
@setheliot This article is ready for your technical review.

2023-08-25 02:44 UTC, setheliot requested changes
I like how you open up this piece with an analogy -- it is a great way to get readers involved.

The technical content here however lacks almost any detail. Running a test is not "simply clicking “Run”.".   Your explanations of the different types of stress testing also lack detail. I could not follow what you were trying to explain there

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +description: Cloud technology is no longer being viewed as emerging. Factors that include agility, cost efficiency, resilience, and scalability have led to the wide adoption of cloud. With this, ensu
description needs to be in quotes

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> + Here you are testing across the whole server and all the clients. ![Communication](images\communication.jpeg) You are essentially **testing communication** between the stress server and the clients.
for all URLs that point to aws, please
* remove any trailing slash
* append the following `?sc_channel=el&sc_campaign=resiliencewave&sc_geo=mult&sc_country=mult&sc_outcome=acq&sc_content=stress-testing-cloud
* test that the link works

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +![A Bridge](images\bridge.jpeg) In the process of preparing to write this article, I learned a lot about load testing of bridges. Load testing a bridge is performed, among others, to verify satisfact
all of your image embeds appear to be broken. [see for yourself here](https://github.com/build-on-aws/content/blob/37d7b78b0bb34e75cd5e304ec07879e428d94647/posts/stress-testing-in-the-cloud/index.md).  To fix this
* use `/` forward slash

Also...

* Please put two CR before and after each image embed 
* Use the following format for images and captions as [documented here](https://github.com/build-on-aws/content/blob/37d7b78b0bb34e75cd5e304ec07879e428d94647/FAQ.md#how-do-i-show-images-in-my-post) - use of captions is optional

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +![A Bridge](images\bridge.jpeg) In the process of preparing to write this article, I learned a lot about load testing of bridges. Load testing a bridge is performed, among others, to verify satisfact
IMPORTANT: Do you have rights to all the images you used?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +  - cloudworkloads
is `cloudworkloads` a meaningful tag?  That is all we talk about here 😃

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +  - stresstesting
instead of `stresstesting` and `performancetesting` might I suggest
```
- testing
- performance
- stress
```

`testing` is an [existing tag](https://community.aws/sitemaps/tags.xml), so you might benefit from using it

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Cloud technology is no longer being viewed as emerging. Factors that include agility, cost efficiency, resilience, and scalability have led to the wide adoption of cloud. However, factors such as the
maybe reword so that "ensuring testing " starts a new sentence... this one is kind of unwieldy

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Cloud technology is no longer being viewed as emerging. Factors that include agility, cost efficiency, resilience, and scalability have led to the wide adoption of cloud. However, factors such as the
> traditional methods being proved to be unsuitable

Some example or a link to some would be helpful

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Performance testing is an “umbrella” term used to define the practice of evaluating how your system responds and its stability under a particular workload. Types of performance testing include load,
> Types of performance testing include load, latency, stress, soak, spike, scalability, just to name a few.

please link to where reader could learn more about these

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Performance testing is an “umbrella” term used to define the practice of evaluating how your system responds and its stability under a particular workload. Types of performance testing include load,
> and its stability under a particular workload

["workload" in AWS ](https://docs.aws.amazon.com/wellarchitected/latest/userguide/workloads.html)refers to "a collection of resources and code that delivers business value, such as a customer-facing application or a backend process."  Therefore you should find a different term to refer to what you mean here

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +[In an old interview by InfoQ](https://www.infoq.com/articles/cockcroft-high-availability/), Adrian Cockroft states that the problem with dependencies between services is that it rapidly gets complic
is "old" really needed here?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +[In an old interview by InfoQ](https://www.infoq.com/articles/cockcroft-high-availability/), Adrian Cockroft states that the problem with dependencies between services is that it rapidly gets complic
# IMPORTANT

> Stress testing is just one of the ways to test these dependencies 

No!  You never want to use load-based stress testing to find issues with your dependencies _unless_ you working with those dependencies as part of the test. Subjecting your dependencies to stress level loads without their knowledge is called an _attack_

Note that Adrian says the following

> To test that everything works properly under stress, we use Latency Monkey to inject failures and high latency into dependent service calls. This makes sure we have the timeouts and circuit breakers calibrated properly, and uncovers any "unsafe" dependencies that are being called directly, since those can still cause cascading failures.

This is a different kind of stress testing (not using load).  They are adding latency to the calls their client (system under test) makes to the dependencies.  This should have no (or little) effect on the dependencies.  This is not subjecting dependencies to high load

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +![A Bridge](images\bridge.jpeg) In the process of preparing to write this article, I learned a lot about load testing of bridges. Load testing a bridge is performed, among others, to verify satisfact
Fun starting paragraph 😃

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +[In an old interview by InfoQ](https://www.infoq.com/articles/cockcroft-high-availability/), Adrian Cockroft states that the problem with dependencies between services is that it rapidly gets complic
"include:" --> "include the following"

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> + Here you are testing across the whole server and all the clients. ![Communication](images\communication.jpeg) You are essentially **testing communication** between the stress server and the clients.
> [Disaster recovery is different in the cloud][https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-is-different-in-the-cloud.html]

This does not render as a link.  [see for yourself here](https://github.com/build-on-aws/content/blob/37d7b78b0bb34e75cd5e304ec07879e428d94647/posts/stress-testing-in-the-cloud/index.md).  To fix this

```
[Disaster recovery is different in the cloud](https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/disaster-recovery-is-different-in-the-cloud.html)
```

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> + Here you are testing across the whole server and all the clients. ![Communication](images\communication.jpeg) You are essentially **testing communication** between the stress server and the clients.
>  Right now, you’re probably wondering how off-peak hours look in the cloud? One of the advantages of deploying your workloads in the cloud is the ability to cost-effectively procure disaster recovery resources.

It is not clear to me how "the ability to cost-effectively procure disaster recovery resources" is related to "off-peak hours look in the cloud"

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> + Here you are testing across the whole server and all the clients. ![Communication](images\communication.jpeg) You are essentially **testing communication** between the stress server and the clients.
what does "whole server" mean?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> + Here you are testing across the whole server and all the clients. ![Communication](images\communication.jpeg) You are essentially **testing communication** between the stress server and the clients.
>  stress server and the clients.

What does "stress server" mean?   Client of what?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +### 1. Distributed client-server
I do not understand the explanation here

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +### 2. Application
his explanation is insufficient

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +The main focus during application stress testing is **on any defects in data locking and performance issues that may be a blocker**. During application stress testing you look at defects that can occ
> During application stress testing you look at defects that can occur during simultaneous access of the same data by multiple users

is this related to "stress testing measures how your system performs under unexpected load volumes" or not? it is not clear

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +The main focus during application stress testing is **on any defects in data locking and performance issues that may be a blocker**. During application stress testing you look at defects that can occ
>  The main goal of application stress testing is to ensure that you deliver a product that is reliable and of high quality.

Isn't that the goal of all the techniques you present?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +With transactional stress testing, you’re essentially testing that **the integrity of the data is maintained during an exchange from one application to another**. In addition, you are testing for res
This is insufficient.  What is being done?  how?  examples?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Running stress testing in the cloud involves a number of steps. Before we look at the steps, it is important to note that stress testing should be repeated as often as possible to get the most accura
> as often as possible 

Every minute?  Every second?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Running stress testing in the cloud involves a number of steps. Before we look at the steps, it is important to note that stress testing should be repeated as often as possible to get the most accura
> (or any form of testing)

test professionals do not believe _all_ testing can be automated

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Running stress testing in the cloud involves a number of steps. Before we look at the steps, it is important to note that stress testing should be repeated as often as possible to get the most accura
> Deploying your application in the cloud through the use of containers 

links to more info on what this means and how to do it?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +This is where you decide on the metrics you want to test. To arrive at these metrics, you work backwards by looking at the business needs or product requirements. Stress testing looks at variations i
You previously said stress testing is "when the system is pushed to its limits".  But testing to known peak that occurs regularly is not in my understanding stress testing, that is just an expected load that the system is already designed to accommodate.  Stress testing is about finding the breaking point and understanding how the system recovers

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +A key consideration with any form of testing is to start small. With this, you select only one test scenario as a start. If we look at an example of an e-commerce site, you could start by stress test
> stress testing the **Adding to Cart** workflow

What does this mean?  Does it mean a high load of items added to cart by all users?  Does it mean a given user adding many items to cart?  Does it many transactions that add and remove items from cart?  You lack details that readers need to understand the concepts

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +[Apache JMeter is an open source load testing tool][https://www.blazemeter.com/solutions/jmeter] which when used together with its contributor, BlazeMeter, lets you effortlessly run many parallel tes
> together with its contributor, BlazeMeter,

This is not self-explanatory

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Once you’ve decided on the testing tool, you build the script in the testing tool. While doing this, you can also create your test data.
> you can also create your test data.

This is a huge topic.  synthetic data?  real data that has been sanitized?

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Probably the easiest step of them all, most tools let you do this by simply clicking “Run”.
you yourself talked about integration with pipelines.  Running manually and running programmatically are different options.  Knowing when and where to run is important too

2023-08-25 02:44 UTC, setheliot commented on posts/stress-testing-in-the-cloud/index.md
> +Once the test has completed, analyze the test results to identify any bottlenecks, latency issues, or any other issues based on the metric you decided on earlier during preparation.
how?  what does this look like?  What might one find?

2023-09-18 18:48 UTC, but-cpu commented
Follow with complete hardware compliance and testing review and study before training/ tracking in business with family emphasis.

2023-09-18 18:49 UTC, but-cpu commented
Follow with complete hardware compliance and testing review and study before training/ tracking in business with family emphasis.

2023-10-02 16:45 UTC, closed without merging

2023-10-02 16:45 UTC, cobusbernard commented
@veliswaan / @scribwell closing this one as the newer PR with updates was merged.

2023-10-04 22:08 UTC, setheliot commented
This PR was deprecated and replaced with https://github.com/build-on-aws/content/pull/805