Egress-controls-for-cloud-workloads
build-on-aws/content pull request #644
Opened 2023-08-17 20:39 UTC by 8carroll

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [X ] The title of this pull request reflects the title of my content.
- [X] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [X] This pull request contains one piece of content (post or page).

Content for https://app.asana.com/0/1202294465414476/1205146327627895/f

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-17 20:53 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/index.md
> +| 🧩 Prerequisites    | - [AWS Account](https://aws.amazon.com/resources/create-account/?sc_channel=el&sc_campaign=devopswave&sc_content=cicdetlsprkaws&sc_geo=mult&sc_country=mult&sc_outcome=acq)|
the tracking link has to be updated. Add following to all links that goto .aws domain. feel free to modify the sc_content parameter, but it keep it consistent throughout this blog.

`?sc_channel=el&sc_campaign=costwave&sc_content=egress-controls-1&sc_geo=mult&sc_country=mult&sc_outcome=acq`

2023-08-17 20:54 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/index.md
> +tags:
Please add following in the fontmatter, we are in process of building spaces for cost-optimization and would love to have this post in the feed

```
spaces:
  - cost-optimization
waves:
  - cost-optimization
```

2023-08-17 20:58 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/index.md
> +What we have seen here is just one aspect of controlling egress traffic.  Implementing this simple approach to filtering DNS traffic can improve our security posture and minimizing costs incurred wit
feel free to add teaser to what is coming up or expected in part 2. once have it published you can then quickly link it.

2023-08-17 21:05 UTC, gaonkarr commented
@reviewers 
Please only review the **Egress-controls-for-cloud-workloads** tutorial. The other posts are not yet ready for review.

2023-08-18 16:16 UTC, gaonkarr commented
Will continue tech review after the cloudformation template is uploaded to https://github.com/build-on-aws/testing-egress-controls-for-cloud-workloads

2023-08-24 19:27 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +1. Modify the current architecture to use a centralized inspection VPC.
I am changing this to point 3, please correct if I am mistaken

2023-08-25 19:11 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +Once you have the CloudFormation Template deployed, we will check the baseline posture of the environment.  We are checking to see that certain traffic is allowed out of the environment.  Once verifi
do we want to give estimates? It took me around 7-8 mins for it to deploy

2023-08-25 19:13 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +8. Clone the [git repo](https://github.com/build-on-aws/testing-egress-controls-for-cloud-workloads/tree/main) into the ssm-user home directory using the `git clone https://github.com/build-on-aws/te
interestingly I got error: 
```
sh-4.2$ git clone https://github.com/build-on-aws/testing-egress-controls-for-cloud-workloads.git
sh: git: command not found
```

2023-08-25 19:21 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Select **OVERRIDE** in the response for Block action and enter :code[dns-firewall-block]{showCopyAction=true} as the custom response and `CNAME` as record type.
the image shows `dns-firewall-block`.. but the text here is confusing. Please edit it out.

2023-08-25 19:22 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- You can set the priority for the rules in this page which controls the order in which rules are evaluated.  The first rule that matches a domain query will determine the action taken.  If we were c
you will have to ask the user to click on Next after the rule is added to goto priority section

2023-08-25 19:29 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Select `Block` as Action, `OVERRIDE` as response, and give :code[dns-firewall-block]{showCopyAction=true} as the record value. Select `CNAME` as Record type, leave `0` as TTL and click on `Add rule
same issue here for `dns-firewall-block`

2023-08-25 19:33 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +10. Run the test-egress script using the command `sh test-egress.sh` command.  This should show that nothing is currently being blocked.
also the filename is `egress-check.sh` and it is referred same later.. change the filename pls

2023-08-25 19:36 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Enter a name for this configuration. You can save these logs to CloudWatch logs, S3 buckets, or a Kinesis Data Firehose delivery stream. Select CloudWatch Logs, log group, and send the logs to a ne
can you provide the log group name so user can copy-paste `/aws/route53/egress-wf-query-logging`

2023-08-25 19:38 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![Complete Query Logging](images/Query-Logging-5.JPG "Complete Query Logging")
hide account number if possible

2023-08-25 19:38 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![Verify the Query logging](images/Query-Logging-6.JPG "Verify the Query logging")
hide account number if possible

2023-08-25 19:40 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +  > **Note:** If you used a different block response of NXDOMAIN or NODATA you will see this instead.
please clarify this line.

2023-08-25 20:07 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![CloudWatch log groups delete](/images/cleanup-7.png)
I am a bit confused here. There is only that one log group we created and we should delete it right? The image shows 4 log groups and text also implies there are multiple log groups.

2023-08-25 20:09 UTC, gaonkarr commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +#### Delete the CloudWatch logs
we should also delete the Route 53 -> Resolver -> Query logging right? Looks like we are missing that here

2023-08-25 20:11 UTC, gaonkarr requested changes
@8carroll I made some changes and left comments as part of the technical review. Please do double check everything. 

@scribwell technical review complete

2023-08-25 20:16 UTC, gaonkarr commented
@8carroll please try to reduce filesize of images :)

2023-08-28 19:37 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +8. Clone the [git repo](https://github.com/build-on-aws/testing-egress-controls-for-cloud-workloads/tree/main) into the ssm-user home directory using the `git clone https://github.com/build-on-aws/te
Should work now that the repo is public right?

```
Documents/repos/test  main ✗                                      1y66d ✖ ⚑ ◒  
▶ git clone https://github.com/build-on-aws/testing-egress-controls-for-cloud-workloads.git
Cloning into 'testing-egress-controls-for-cloud-workloads'...
remote: Enumerating objects: 19, done.
remote: Counting objects: 100% (19/19), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 19 (delta 5), reused 12 (delta 2), pack-reused 0
Receiving objects: 100% (19/19), 14.05 KiB | 378.00 KiB/s, done.
Resolving deltas: 100% (5/5), done.

Documents/repos/test  main ✗                                      1y66d ✖ ⚑ ◒  
▶ ls
testing-egress-controls-for-cloud-workloads

Documents/repos/test  main ✗                                      1y66d ✖ ⚑ ◒  
▶ cd testing-egress-controls-for-cloud-workloads 

repos/test/testing-egress-controls-for-cloud-workloads  main ✔          2d21h  
▶ ls
CODE_OF_CONDUCT.md            LICENSE
CONTRIBUTING.md               README.md
Egress-Controls-Tutorial.yaml egress-check.sh

repos/test/testing-egress-controls-for-cloud-workloads  main ✔          2d21h  
▶ 
```

2023-08-28 19:40 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Select **OVERRIDE** in the response for Block action and enter :code[dns-firewall-block]{showCopyAction=true} as the custom response and `CNAME` as record type.
looks like formatting from Workshop studio was left over.  Fixed it.

2023-08-28 19:40 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- You can set the priority for the rules in this page which controls the order in which rules are evaluated.  The first rule that matches a domain query will determine the action taken.  If we were c
added the instruction

2023-08-28 19:41 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Select `Block` as Action, `OVERRIDE` as response, and give :code[dns-firewall-block]{showCopyAction=true} as the record value. Select `CNAME` as Record type, leave `0` as TTL and click on `Add rule
fixed.

2023-08-28 19:43 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +10. Run the test-egress script using the command `sh test-egress.sh` command.  This should show that nothing is currently being blocked.
Done

2023-08-28 19:48 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Enter a name for this configuration. You can save these logs to CloudWatch logs, S3 buckets, or a Kinesis Data Firehose delivery stream. Select CloudWatch Logs, log group, and send the logs to a ne
Done

2023-08-28 19:51 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![Complete Query Logging](images/Query-Logging-5.JPG "Complete Query Logging")
Done.

2023-08-28 19:51 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![Verify the Query logging](images/Query-Logging-6.JPG "Verify the Query logging")
Done

2023-08-28 19:56 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +  > **Note:** If you used a different block response of NXDOMAIN or NODATA you will see this instead.
I removed the note as I will probably only add confusion.

2023-08-28 19:59 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +![CloudWatch log groups delete](/images/cleanup-7.png)
added some clarification.

2023-08-28 21:38 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +#### Delete the CloudWatch logs
Added with a few screenshots.

2023-09-05 18:38 UTC, gaonkarr approved these changes
changes fixed

2023-09-05 18:55 UTC, scribwell commented
@damonk10 The technical review is complete and I've tagged 8112 for editorial review here, in Asana, and in Chime.

2023-09-11 23:38 UTC, DalM2023 reviewed
1st round edit done. Ready for review.

2023-09-12 21:41 UTC, scribwell commented
@8carroll Please address edits/suggestions from the editorial review.

2023-09-13 17:38 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +
Done

2023-09-13 17:41 UTC, 8carroll commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +As we progressed through this tutorial we saw how to configure a custom list of TLDs that we do not want our cloud resources communicating with.  By blocking resolution to these TLDs we not only prot
Done

2023-09-19 17:55 UTC, DalM2023 reviewed
2nd edit finished. Please review.

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +### Step 1 - Set up query logging
```suggestion
### Step 1 - Set Up Query Logging
```

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +### Step 2 - Verify DNS query logs in CloudWatch
```suggestion
### Step 2 - Verify DNS Query Logs in CloudWatch
```

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +- Navigate to the EC2 session and execute the command `nslookup google.cn`. Since dns queries resolving this domain name are blocked you can see that the server cannot find the domain.
```suggestion
- Navigate to the EC2 session and execute the command `nslookup google.cn`. Since DNS queries resolving this domain name are blocked you can see that the server cannot find the domain.
```

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +### Delete the DNS Firewall rules
```suggestion
### Delete the DNS Firewall Rules
```

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +### Delete the CloudFormation template
```suggestion
### Delete the CloudFormation Template
```

2023-09-19 17:55 UTC, DalM2023 commented on tutorials/egress-controls-for-cloud-workloads/egress-controls-with-route53-dns-resolver-firewall/index.md
> +### Delete the CloudWatch logs
```suggestion
### Delete the CloudWatch Logs
```

2023-09-20 13:32 UTC, scribwell commented
@damonk10 Would you please review @DalM2023's edits as part of your final review? Most of the edits seem to correct typos so I think we can just accept those when you do the final edit and publish this piece if everything looks good.

2023-09-28 14:47 UTC, merged