The ultimate guideline for running Spark on AWS in maintainable, reliable and cost-effective way
build-on-aws/content pull request #651
Opened 2023-08-18 20:37 UTC by debnsuma

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-18 20:42 UTC, debnsuma commented
> ## Automated Validation Results
> * `/posts/ultimate-guideline-for-running-spark-on-aws/images/why-aws.png`: passed with warnings ⚠️
>   
>   * ⚠️ File Validation
>     
>     * ⚠️ File size of 281 Kb is quite large. Consider using a smaller file below 250 Kb.
> 
> ## Preview results
> Your pull request contains some content that can be previewed:
> 
> * 👁️‍🗨️ [/posts/ultimate-guideline-for-running-spark-on-aws](https://community.aws/preview/pr-651/posts/ultimate-guideline-for-running-spark-on-aws)

compressed the image and pushed the change.

2023-08-21 18:37 UTC, riferrei requested changes

2023-08-21 18:37 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +description: "Embark on a comprehensive exploration of how to effectively run Apache Spark applications on AWS. This guide unravels the myriad of AWS services that integrate with Spark, offering insi
If possible, this blog post could benefit from having a shorter quick intro. I would leave just with this:

>From understanding the power of AWS Glue for beginners to delving deep into specialized services like SageMaker and Redshift, this post aims to provide clarity for developers seeking optimal performance, scalability, and cost-effectiveness in their Apache Spark workloads.

2023-08-21 18:37 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +AWS provides the perfect environment for running Apache Spark, as it allows organizations to harness the power of Spark's distributed computing capabilities without the need for upfront infrastructur
> AWS provides the perfect environment

Not untrue, but I think this claim can be read with the wrong eyes. Maybe just:

> AWS provides the environment for running Apache Spark, as it allows organizations to harness the power of Spark's...

2023-08-21 18:37 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +### <span style="color:orange">Traditional and Serverless Spark Clusters</span>
Would be possible to provide examples in which the traditional method can provide value? Like, an example where the user may need to fine tune an specific aspect of the infrastructure, then in turn will allow the Spark app to execute better/faster/reliably?

2023-08-21 18:37 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +#### [🔗 Gettings started with SageMaker with Apache Spark](https://docs.aws.amazon.com/sagemaker/latest/dg/apache-spark.html)
There are some interesting blog posts and tutorials published in the community.aws website. Would it help to list them here?

2023-08-21 18:37 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The ultimate guideline for running Apache Spark on AWS in maintainable, reliable and cost-effective way"
Overall, I enjoyed reading this blog post. But something about the title bugged me during the reading. It gave the impression that somewhere down the line I would be presented with tips about cost savings. I didn't find any. Maybe we should remove this part of the title? Or if I failed to find them, maybe this is a hint to improve their readability?

2023-08-21 18:38 UTC, riferrei commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The ultimate guideline for running Apache Spark on AWS in maintainable, reliable and cost-effective way"
Hi @debnsuma,

Nice job writing this piece about Spark. I have left some comments above mostly to improve the readability, but overall I think it is great.

2023-08-21 18:40 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The ultimate guideline for running Apache Spark on AWS in maintainable, reliable and cost-effective way"
Thanks so much @riferrei. All are great inputs and are absolutely correct. Shall edit the post and shall push the change tomorrow. Thank you once again!

2023-08-22 19:01 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +#### [🔗 Gettings started with SageMaker with Apache Spark](https://docs.aws.amazon.com/sagemaker/latest/dg/apache-spark.html)
done

2023-08-22 19:01 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +### <span style="color:orange">Traditional and Serverless Spark Clusters</span>
thanks, good point. Fixed.

2023-08-22 19:01 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +AWS provides the perfect environment for running Apache Spark, as it allows organizations to harness the power of Spark's distributed computing capabilities without the need for upfront infrastructur
fixed

2023-08-22 19:01 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +description: "Embark on a comprehensive exploration of how to effectively run Apache Spark applications on AWS. This guide unravels the myriad of AWS services that integrate with Spark, offering insi
fixed

2023-08-22 19:02 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The ultimate guideline for running Apache Spark on AWS in maintainable, reliable and cost-effective way"
Yes, I agree, changed the time.

2023-08-23 13:48 UTC, cherbk approved these changes

2023-08-25 16:55 UTC, damonk10 commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The Ultimate Guide to Running Apache Spark on AWS at Scale With Maintainability and Reliability"
I would suggest cutting the end of the title off for the sake of efficiency: "The Ultimate Guide to Running Apache Spark on AWS"

2023-08-25 16:55 UTC, damonk10 commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +Apache Spark on AWS integrates effortlessly with various AWS data services. This allows organizations to utilize their existing data infrastructure. Spark can interact with services like Amazon S3, A
Throughout the piece, you reference many aws services. Make sure you link to them following the directions here: https://w.amazon.com/bin/view/AWS/Hands-On_Builders_Hub/Content/Tracking-Links

2023-08-25 17:53 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +As we conclude this guide, it's evident that the intersection of Spark and AWS is where scalability meets efficiency. By aligning your requirements with the right AWS service, you can harness the com
thanks fixed

2023-08-25 17:53 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +Apache Spark on AWS integrates effortlessly with various AWS data services. This allows organizations to utilize their existing data infrastructure. Spark can interact with services like Amazon S3, A
fixed. shall keep this in mind for future write-ups :) thank you.

2023-08-25 17:53 UTC, debnsuma commented on posts/ultimate-guideline-for-running-spark-on-aws/index.md
> +title: "The Ultimate Guide to Running Apache Spark on AWS at Scale With Maintainability and Reliability"
fixed.

2023-08-30 17:26 UTC, cherbk approved these changes

2023-08-30 20:08 UTC, cherbk approved these changes

2023-08-30 20:09 UTC, merged