Build Your Own translator app in 30 min or less
build-on-aws/content pull request #663
Opened 2023-08-22 21:21 UTC by elizabethfuentes12

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-05 20:21 UTC, LindaHaviv requested changes
Love this piece! Great job per usual. I did a technical review and all looks good. Added some minor changes. Once addressed this will go to editorial review.

2023-09-05 20:21 UTC, LindaHaviv commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +| 💰 Cost to complete | [AWS Free Tear](https://aws.amazon.com/free/)      |
```suggestion
| 💰 Cost to complete | [AWS Free Tier](https://aws.amazon.com/free/)      |
```

2023-09-05 20:21 UTC, LindaHaviv commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +- How to use Artificial Intelligence service to converts text into lifelike speech.
```suggestion
- How to use Artificial Intelligence service to convert text into lifelike speech. 
```

2023-09-05 20:21 UTC, LindaHaviv commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +In this blog you are going to create a translator chatbot app, with [Amazon Lex](https://aws.amazon.com/lex/) that will handle the frontend interaction with the user, and the backend will be in charg
```suggestion
In this blog you are going to create a translator chatbot app, with [Amazon Lex](https://aws.amazon.com/lex/) that will handle the frontend interaction with the user, and the backend will be in charge of an [AWS Lambda Function](https://aws.amazon.com/lambda/) with the [AWS SDK for Python library Boto3](https://aws.amazon.com/sdk-for-python/) code using the following AWS services:
```

2023-09-05 20:21 UTC, LindaHaviv commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +### You will build it in five parts:
```suggestion
### You will build it in seven parts:
```

2023-09-06 00:35 UTC, cherbk approved these changes

2023-09-06 00:41 UTC, cherbk approved these changes

2023-09-06 18:44 UTC, scribwell commented
@damonk10 This editorial review has been assigned to 8112.

2023-09-12 19:36 UTC, DalM2023 reviewed
First round edit complete. Ready for review.

2023-09-12 21:46 UTC, scribwell commented
@elizabethfuentes12 Please review the edits/suggestions from the editorial review and make any necessary revisions by September 19.

2023-09-14 23:17 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +---
Thanks! :) I will review it and follow your comments

2023-09-15 15:32 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +| <ul><li>**OutputFormat(string)**: The format in which the returned output will be encoded. For audio stream, this will be mp3, ogg_vorbis, or pcm. For speech marks, this will be json. <li>**OutputS
Resolved: 
|StartSpeechSynthesisTask Parameters | GetSpeechSynthesisTask Parameter|
| ------------------- | -------------------------------------- |
| <ul><li>**OutputFormat(string)**: the value at which the result will be returned and it can be: *json*,*mp3*, *ogg_vorbis* or *pcm*. <li>**OutputS3BucketName (string)**: It's the [Amazon S3](https://aws.amazon.com/s3/) bucket name to which the output file will be saved. <li>**Text (string)**: The input text to synthesize. <li>**Engine (string)**: It specifies the engine (standard or neural) for Amazon Polly to use when processing input text for speech synthesis. <li>**VoiceId (string)**: [Voice ID](https://docs.aws.amazon.com/polly/latest/dg/voicelist.html) is used for the synthesis.</li></ul>|  <ul><li>**TaskId (string)**: This is the Amazon Polly generated identifier for a speech synthesis task.</li></ul>|
|||

2023-09-15 15:42 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +For this Lambda Function have permissions to invoke AWS services and resources, it is necessary to create an execution role that has the necessary permissions, to do this, follow the following steps:
To allow the Lambda function to invoke AWS services and resources, an execution role with the required permissions must be created. Follow these steps to create it:

2023-09-15 15:44 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +🥳 Ok, you have all the code ready, now let's get it to work!
done

2023-09-15 15:54 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +To trigger the Lambda Function when a user interacts with Amazon Lex like a Dialog code hook, Lambda Function its attaching to a bot alias [following these steps](https://docs.aws.amazon.com/lexv2/la
To trigger a Lambda function when a user interacts with Amazon Lex, you attach the function to a bot alias by [following these steps](https://docs.aws.amazon.com/lexv2/latest/dg/lambda-attach.html)

2023-09-15 15:55 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +The takeaway is if you can imagine it, you can build it with AWS. This project expanded you skills while creating something meaningful.
done

2023-09-15 18:48 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +tags:
Changed to this: Use Amazon Translate, Amazon Comprehend, Amazon Lambda, Amazon Polly, and Amazon Lex to bring a translation application to life and test it in 30 minutes or less.

2023-09-15 18:50 UTC, elizabethfuentes12 commented on tutorials/build-your-own-translator-app-in-less-30-min/index.md
> +### Test and inspect the bot you have created so far follow the instructions in [this link](https://docs.aws.amazon.com/lexv2/latest/dg/test-bot.html).
done

2023-09-15 18:54 UTC, closed without merging