AI-Powered Development: Creating Secure and Resilient Apps with CodeWhisperer and CodeGuru
build-on-aws/content pull request #682
Opened 2023-08-23 20:28 UTC by samfarber

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Content for Wave 3 - Resilient Cloud Architecture for Developer Relations/Hands-on Builder Hub - https://w.amazon.com/bin/view/AWS/Hands-On_Builders_Hub/Content/Dashboard/
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-24 02:34 UTC, setheliot requested changes

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +Nowadays, users expect the applications that they use to have 100% uptime and be available 24/7. However, it can be a complex endeavor for developers building to also keep in mind best practices for
We like to start off with the problem we are solving for the builder, which you do, but I think that an be strengthened here.  Also "new and exciting" is too market-y (as as I said, removing "new" can make the piece more timeless)

I would say to replace this and the next paragraph.   You do NOT need to use what I have written (or you can, or feel free to modify) -- it is just to give you an idea of the layout I suggest

> Nowadays, users expect the applications that they use to have 100% uptime and be available 24/7. However, it can be a complex endeavor for developers building these applications to understand and apply all the best practices for designing highly available systems. Fortunately, advances in AI now enable developers to use AI-powered tools to analyze source code, detect anomalies, suggest fixes, and monitor system health to boost reliability. Here I will share with your how this combination of AI and software development is enabling a new generation of highly available applications established around proven and optimal methodologies in security and resilience..

> In this post, I will share how you can use developer tools such as Amazon CodeWhisperer and Amazon CodeGuru Security to assist you in creating resilient applications. 

feel free to beef up the second paragraph and add more details about the tools

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +Nowadays, users expect the applications that they use to have 100% uptime and be available 24/7. However, it can be a complex endeavor for developers building to also keep in mind best practices for
Note I changed "optimal methodologies in security" to "optimal methodologies in security and resilience" - since this is resilience-wave article, it should have strong resilience focus.  It also seemed strange to say highly available applications and then only mention security methodologies.  Feel free to re-write to reflect what your message is, if I did not get it right

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +## CodeWhisperer
Instead of leading with product names, lead with either the problem, or the solution to the problem, that they solve.  You can still mention the product name, but as part of such a statement

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +## CodeGuru
same comment as for `## CodeWhisperer` above

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +[Amazon CodeWhisperer](https://aws.amazon.com/codewhisperer/) is an AI coding companion that generates whole line and full function code suggestions in your IDE to help boost productivity as well as
[optional] so many references to "best practices" and never a mention of AWS Well-Architected, the official repository of AWS best practices?  Seems like you should reference the [Security pillar ](https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html)and [Reliability pillar ](https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html)

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +[Amazon CodeWhisperer](https://aws.amazon.com/codewhisperer/) is an AI coding companion that generates whole line and full function code suggestions in your IDE to help boost productivity as well as
please add the following to every URL that links back to an AWS site (remove any trailing `/` before appending it).  Then please test all links with the added parameters

```
?sc_channel=el&sc_campaign=resiliencewave&sc_geo=mult&sc_country=mult&sc_outcome=acq&sc_content=ai-powered-development
```

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +[Amazon CodeWhisperer](https://aws.amazon.com/codewhisperer/) is an AI coding companion that generates whole line and full function code suggestions in your IDE to help boost productivity as well as
> Among these best practices include secure and resilient application code designs.

Please share some examples of resilience best practices that it  adheres to, here or later in the piece

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +In order to help developers build more secure applications, CodeWhisperer is able to assist in enhancing the security of code that’s being written. You can scan your code to detect hard-to-find vulne
> CodeWhisperer is able to assist in enhancing the security of code that’s being written.

This is a piece on resilience, please focus more on that

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +These findings aid in keeping your code secure as well as increasing the application’s resistance to attacks. And rather than going through line by line, you, as a developer, can expedite the generat
>  Resilience isn’t always top of mind for developers, with tools like CodeWhisperer and CodeGuru, you can have more assurance that you’re coding with security best practices at the ready

The Resilience message, or examples, is no really coming through

2023-08-24 02:34 UTC, setheliot commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +
**The entire CodeWhisperer section seems like just excerpts from the product page and AWS documentation. It reads like a [launch blog](https://aws.amazon.com/blogs/aws/amazon-codewhisperer-free-for-individual-use-is-now-generally-available/), and we already have one of those. The resilience message is not clear, and it lacks examples**

2023-08-29 20:07 UTC, crichey commented on posts/ai-powered-development-creating-secure-and-resilient-apps-with-codewhisperer-and-codeguru/index.md
> +[Amazon CodeWhisperer](https://aws.amazon.com/codewhisperer/) is an AI coding companion that generates whole line and full function code suggestions in your IDE to help boost productivity as well as
Let's remove reference to resilient code deigns here.

2023-08-31 15:45 UTC, scribwell commented
@cobusbernard @bketelsen I've relabled this post as a blog and it is ready for one-step review.

2023-08-31 18:10 UTC, merged