tidy-your-bedroom-identify-unused-resources
build-on-aws/content pull request #690
Opened 2023-08-28 13:03 UTC by srhowell

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-08-28 14:18 UTC, gaonkarr commented
@srhowell added this to incorrect folder, helping him to move to tutorial.

2023-08-29 19:20 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +1. The default view opens, and this may show a banner at the top stating *You can start searching immediately while we begin indexing the resources in your account. You might see incomplete results u
we are missing step here that they should go to AWS Resource Explorer ->
Resource search.

2023-08-29 19:20 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +1. Select AWS Resource Explorer
feel free to provide direct link AWS Resource Explorer https://resource-explorer.console.aws.amazon.com/resource-explorer/home)

2023-08-29 19:23 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +1. From AWS Console, search for AWS Resource Explorer using the search bar or the shortcut *Alt + S*
same suggestion, feel free to reduce this. In the [AWS Console for Resource Explorer](https://resource-explorer.console.aws.amazon.com/resource-explorer/home), navigate to Views.

2023-08-29 20:47 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +Soon after this, I created an [Amazon SageMaker Studio](https://docs.aws.amazon.com/sagemaker/) domain for a student demo. I had finished the demo, and no longer needed the Amazon SageMaker Studio do
we typically love to give links to proper documentation pages that give more information. for example, would suggest providing link like https://docs.aws.amazon.com/sagemaker/latest/dg/sm-domain.html instead of generic documentation

2023-08-29 20:48 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +Recently I was using [**AWS Amplify**](https://docs.amplify.aws/) to make a workshop for students learning serverless app development. Every time I tested an iteration of the workshop, I created an I
same here, something like https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html or https://docs.amplify.aws/start/

2023-08-29 20:59 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +Recently I was using [**AWS Amplify**](https://docs.amplify.aws/) to make a workshop for students learning serverless app development. Every time I tested an iteration of the workshop, I created an I
I will modify it for now, feel free to replace it

2023-08-29 21:27 UTC, gaonkarr requested changes
@srhowell I made some minor changes to the tutorial. PLEASE do synk fork, and do git pull to your local branch. 

Please do verify the changes. 

One missing element is after Creative the custom views, please direct the user on how they can view the filtered resources. Either they go back to `resource search` or open the view and click on `explore resources`.

Overall it is a good tutorial, simple for beginners and easy to follow. Please do check if you want to add any images to make it a bit more fun

2023-08-29 21:29 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +Soon after this, I created an [Amazon SageMaker Studio](https://docs.aws.amazon.com/sagemaker/) domain for a student demo. I had finished the demo, and no longer needed the Amazon SageMaker Studio do
I will modify it for now, feel free to replace it

2023-08-29 21:29 UTC, gaonkarr commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +1. From AWS Console, search for AWS Resource Explorer using the search bar or the shortcut *Alt + S*
I will modify it for now, feel free to replace it

2023-08-29 21:31 UTC, gaonkarr commented
@scribwell tech review completed. Changes requested before editorial review.

2023-08-30 14:57 UTC, gaonkarr commented
@srhowell LOVE the images! 👯

2023-09-05 16:06 UTC, gaonkarr approved these changes
Stephen has made the requested changes

2023-09-05 21:45 UTC, scribwell commented
@damonk10 I've assigned this tutorial to Dalia for editorial review and notified her on chime.

2023-09-13 18:01 UTC, scribwell commented
@srhowell Would you please review our editor's revisions and make any necessary changes?

2023-09-15 14:29 UTC, srhowell commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +tags:
According to https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md:

Tags: Tags in a post are limited to 5 that will displayed in the feed, so ensure the most important 5 are first in the list, using the kebab-case convention (all lowercase, with - between words).

So 5 is a limit, but if we need 5, it's a target.

2023-09-15 14:39 UTC, srhowell commented on tutorials/tidy-your-bedroom-identify-unused-resources/index.md
> +---
Thanks for the review @DalM2023!

2023-09-18 14:26 UTC, gaonkarr commented
@srhowell are all the changes done?

CC: @scribwell

2023-09-18 20:49 UTC, gaonkarr commented
@scribwell 
@srhowell pinged me that he has done all the changes

2023-09-18 21:00 UTC, scribwell commented
@damonk10 Would you please do a final review and then publish?

2023-09-19 18:40 UTC, damonk10 approved these changes

2023-09-19 18:46 UTC, merged