Blogpost: The Grad Project (to be published 9/12)
build-on-aws/content pull request #723
Opened 2023-09-07 20:44 UTC by jlooper

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-07 22:57 UTC, cobusbernard commented on posts/the-grad-project/index.md
> +# Announcing The Grad Project: Showcasing Innovative Student Research
```suggestion
## Announcing The Grad Project: Showcasing Innovative Student Research
```
The H1 tag is reserved for the title of the piece.

2023-09-07 22:58 UTC, cobusbernard commented on posts/the-grad-project/index.md
> +<iframe width="492" height="875" src="https://www.youtube.com/embed/vHfCu0due0g" title="Ben Jessie OD Promo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscop
```suggestion
https://www.youtube.com/embed/vHfCu0due0g
```
Youtube videos can be embedded by adding the URL on a line with an empty line above and below it, don't need to embed an iframe.

2023-09-07 22:58 UTC, cobusbernard commented on posts/the-grad-project/index.md
> +<iframe width="492" height="875" src="https://www.youtube.com/embed/kMVxu-3BkK4" title="Vince LI Promo" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; pi
```suggestion
https://www.youtube.com/embed/kMVxu-3BkK4
```
Same here for the youtube video.

2023-09-07 23:00 UTC, cobusbernard commented on posts/the-grad-project/index.md
> +>Taping begins in Seattle with Adam, Curtis, and Vince. Image by Tricia Gallagher
```suggestion
![Taping The Grad Project](./images/tgp-1.jpg "Taping begins in Seattle with Adam, Curtis, and Vince. Image by Tricia Gallagher")
```
You can add a title below an image with this change instead of adding a quote.

2023-09-07 23:01 UTC, cobusbernard requested changes
Flagging as "changes requested" to keep it blocked until 9/12, please do not approve this PR until this date.

2023-09-07 23:46 UTC, jlooper commented on posts/the-grad-project/index.md
> +>Taping begins in Seattle with Adam, Curtis, and Vince. Image by Tricia Gallagher
ooh, nice! Did not know this.

2023-09-11 21:35 UTC, jlooper reviewed
I wanted to add a section at the end about us with a CTA to go to the Student Hub

2023-09-12 16:40 UTC, cobusbernard commented
Closing in favour of #739 .

2023-09-12 16:40 UTC, closed without merging