Initial Draft of Content for Build On AWS Tutorial  - "Unlock the power of Unstructured Data: From Embeddings to In Context Learning – Build a Full stack Q&A Chatbot with Langchain, and LLM Models on Sagemaker"
build-on-aws/content pull request #737
Opened 2023-09-12 01:12 UTC by pkamra

# Content Pull Request Checklist
Initial Draft of Content for Build On AWS Tutorial  - "Unlock the power of Unstructured Data: From Embeddings to In Context Learning – Build a Full stack Q&A Chatbot with Langchain, and LLM Models on Sagemaker"
The Approved Asana Ticket for this tutorial is https://app.asana.com/0/1204199791673171/1205326498728997

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ Y] The title of this pull request reflects the title of my content.
- [ Y] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [Y ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-19 17:08 UTC, abhirockzz requested changes
This is good topic and shows an end-to-end solution. However, I have the following concerns:

- At this point, it's not fit to be published as a tutorial - it does not provide step-by-step instructions. A tutorial is something that reader can complete.
- Lot of missing context. Concepts and services have not been introduced.
- Way too many diagrams. It's partly because they are not being used properly e.g. don't explain code using screenshots - refer to the GitHub repo and explain it in the content itself

This piece needs to be significantly overhauled to qualify as a tutorial. Also needs improvement in terms of readability and structure

2023-09-19 17:08 UTC, abhirockzz commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +Next we move on to the last step for our full stack pipeline, which is integrating the API with our Open Source embedded chatbot using Open Source botkit in a HTML website. For this website and the e
fix "node based application" - Nodejs application

2023-09-19 20:22 UTC, pkamra commented
Need clarification on the below comment since it doesnt tell me what to fix ?
>> At this point, it's not fit to be published as a tutorial - it does not provide step-by-step instructions. A tutorial is something that reader can complete.

I have provided a Step by Step instruction to build ? Which part was not reproducible or which part do I need to change ?

2023-09-19 20:24 UTC, pkamra commented
Need clarification on this. Let me know which service needs explanation or if you could give me an example taht woudl help.
>> Lot of missing context. Concepts and services have not been introduced.

2023-09-19 20:25 UTC, pkamra commented
I will remove the screen shots showing the code explanation to the code repo.
>> Way too many diagrams. It's partly because they are not being used properly e.g. don't explain code using screenshots - refer to the GitHub repo and explain it in the content itself

2023-09-20 00:56 UTC, pkamra commented
working on the feedback.

2023-09-20 08:48 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +title: "Unlock the power of Unstructured Data: From Embeddings to In Context Learning – Build a Full stack Q&A Chatbot with Langchain, and LLM Models on Sagemaker"
Updated

2023-09-20 09:02 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +Now that we have our text embeddings in the Vector Database powered by AWS OpenSearch, let us move to the next step where we will utilize the T5 Flan XXL Large Language Model (LLM) to respond to inqu
Updated Step 5  and Step 6 with detailed steps.

2023-09-20 09:06 UTC, pkamra commented
@abhirockzz  have updated the content. Removed screen shots, added detailed steps where missing, Please review.

2023-09-21 04:12 UTC, abhirockzz commented
Thanks for incorporating the feedback. I do have concerns about the diagrams. Please fix them and we should be good to go:

General comment on diagrams - Most of the them need to be cleaned up 

- Use proper/complete service names and updated logos (refer to https://aws.amazon.com/architecture/icons/),
- arrows are overlapping with text
- inconsistent services logos have been used (e.g. in some cases I see Fargate with a black background, and in some cases its different). 
- Lambda pipeline diagram - pls remove text from the diagram. Use appropriate logo/icons
- pls don't include too much text in the diagram (it's distracting). Leave that for the article/content
- not sure why a green background has been chosen for diagrams. It's not suitable both from readability and aesthetic point of view
- some of the diagrams are not clear. For e.g. in the SageMaker studio diagram, I can hardly see anything (I am familiar with SageMaker studio, but a new reader might have a tough time). Not sure if this is a platform issue or something to do with the image(s)

Also:

- Clean up section - remove the manual steps and provide CLI instructions.
- Add a "Prerequisites" section with all the tooling required to complete the tutorial (e.g. AWS CLI, Docker etc.)

2023-09-21 16:23 UTC, cherbk commented
> Working on fixing the diagrams

I will submit it for editorial review while you work on the diagrams. Thanks Piyali

2023-09-21 22:24 UTC, pkamra commented
@abhirockzz and @cherbk, Have incorporated the feedback for diagrams, added additional details in Prerequisites under the Attributes table on top and  CLI Instructions in the Cleanup section.

2023-09-22 02:56 UTC, abhirockzz approved these changes

2023-09-22 02:56 UTC, abhirockzz commented
> @abhirockzz and @cherbk, Have incorporated the feedback for diagrams, added additional details in Prerequisites under the Attributes table on top and CLI Instructions in the Cleanup section.

Thank you @pkamra !

2023-09-27 15:00 UTC, scribwell commented
@DalM2023 This tutorial is ready for editorial review.

2023-09-27 19:24 UTC, DalM2023 reviewed
1st round edit done. Please review.

2023-09-27 19:24 UTC, DalM2023 commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +---
Hello! 

This blog has good structure, a friendly tone and what a fun project!! 

Please consider a few thing to keep in mind: 

- Please rake through the piece and uniform the spaces between sections, paragraphs and between paragraphs and instructions. Sometimes I saw one space, sometimes there's an extra space and sometimes there are no spaces. I tried to flag them but please do a double check so the spacing is uniform throughout the piece. 

- I made changes on the titles to AP Style, which is what Amazon uses. 

-  The capitalization of techniques and tools isn't uniform. Please be mindful of these. 
pdf = PDF
"in-context learning" has variations like "In-context learning". 
"vector database" is capitalized in some places and not in others.
I flagged as many as I could but please read through it to make sure they're uniform. 

- RE: LLM use. At the beginning of the piece you introduce LLM as a concept, title and acronym. So, there's no need to keep writing it as "Large Language Models (LLMs)" throughout the piece. You can simply use LLM. Also the M is model, so it's redundant to write "LLM model" and in plural it's LLMs not LLM's. 

Please see my notes below for other editorial suggestions. 

Overall, I enjoyed reading this blog. Well done! 👍

2023-09-27 19:24 UTC, DalM2023 commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +[Amazon OpenSearch](https://aws.amazon.com/opensearch-service/) is a search and analytics engine that can search for nearest neighbors of points in a vector space, making it suitable as a Vector Data
Does vector database need capitalization here?

2023-09-28 14:13 UTC, scribwell commented
@pkamra We've finished the first pass of our editorial review. Please either accept our editor's changes or provide a reason for rejecting them and make any additional necessary edits by October 2. Thank you!

2023-10-01 16:13 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +## What are we going to build
Done

2023-10-01 16:20 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +
Fixed

2023-10-01 16:21 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +In this example, we want to mimic the problem that is faced by many enterprises. Most of the data today is not structured but is rather unstructured in the form of audio and video transcripts, pdf an
Done

2023-10-01 16:32 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +
Fixed remaining white spaces between lines as well

2023-10-01 16:41 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +In today’s data-driven landscape, extracting meaningful insights from unstructured documents remains a challenge, inhibiting decision-making and innovation. Imagine being able to converse with your u
Done

2023-10-01 16:43 UTC, pkamra commented on tutorials/fullstack-llm-langchain-chatbot-on-aws/index.md
> +[Amazon OpenSearch](https://aws.amazon.com/opensearch-service/) is a search and analytics engine that can search for nearest neighbors of points in a vector space, making it suitable as a Vector Data
fixed

2023-10-01 18:15 UTC, pkamra commented
@scribwell @cherbk @DalM2023. Accepted and updated as per review comments.

2023-10-05 15:30 UTC, DalM2023 reviewed
@damonk10 Ready for review.

2023-10-05 22:50 UTC, merged