How-to-design-and-implement-an-effective-incident-response-strategy
build-on-aws/content pull request #747
Opened 2023-09-15 03:57 UTC by joshinik

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-18 19:56 UTC, scribwell commented
@setheliot Please work with @joshinik to revise this draft to better fit our fundamentals concept as part of your technical review. We'll want to add more topics and links to additional resources throughout.

2023-09-19 20:05 UTC, setheliot commented
@joshinik hi, I think this is a great piece, and there are some things I need from you before we publish it. 
1. Please move much of what you have under "description" out of that section, and as an intro to the main doc as an intro, for example see https://community.aws/concepts/should-know-resilience
1. add links to resources throughout.  your piece covers everything at a high level, so give the reader links where they can learn more about each of the 4 steps

2023-09-19 20:14 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +authorName: Nikhil Joshi
please add
```
waves:
  - resilience
```

2023-09-19 20:14 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +showInHomeFeed: false
`true`

2023-10-09 20:01 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +tags:
add tag `resilience`

2023-10-10 03:19 UTC, setheliot requested changes

2023-10-10 03:19 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +authorName: Nikhil Joshi
please add this

2023-10-10 03:19 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +## Preparation
[optional] you can put the same numbers (1, 2, 3, 4) in front of each section header that you use to enumerate them in the introduction

2023-10-10 03:19 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +An important aspect of detection and analysis is understanding gray failures. Gray failures are a type of failure that are not immediately detected or flagged as an error in an IT system. Gray failur
I liked that you add "see here for more info" links, but you can also add in-line links.  For example, "gray failure" should link to https://docs.aws.amazon.com/whitepapers/latest/advanced-multi-az-resilience-patterns/gray-failures.html

2023-10-10 03:19 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +An important aspect of detection and analysis is understanding gray failures. Gray failures are a type of failure that are not immediately detected or flagged as an error in an IT system. Gray failur
> Regular monitoring and testing of IT systems are essential to identify and resolve gray failures before they become major issues.

That is NOT sufficient (or actionable) for monitoring gray failures -- instead it requires [differential observability](https://docs.aws.amazon.com/whitepapers/latest/advanced-multi-az-resilience-patterns/gray-failures.html)

2023-10-10 23:36 UTC, setheliot approved these changes

2023-10-11 14:19 UTC, scribwell commented
@DalM2023 This fundamentals post is ready for your editorial review.

2023-10-12 18:09 UTC, DalM2023 reviewed
1st round edit done. Ready for review.

2023-10-12 18:09 UTC, DalM2023 commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +description: "In this blog, we will go through the key steps in designing and implementing an incident management strategy covering the 4 steps of incident response as defined by NIST, namely 1/prepa
These descriptors have to be super pithy: 60 characters. (I know!) They don't need to repeat words mentioned in the title and they need to focus on what the user gets from reading the blog. Please rewrite. It could be something like this: "Respond quickly to incidents and minimize damage on operations."

```suggestion
description: "In this blog, we will go through the key steps in designing and implementing an incident management strategy covering the 4 steps of incident response as defined by NIST, namely 1/preparation, 2/detection and analysis, 3/containment & recovery, and 4/correction of errors & continuous improvement."
```

2023-10-12 18:09 UTC, DalM2023 commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +---
Hello! 

This is a great blog for businesses! I enjoyed reading it. You have good structure, pleasant voice and tone. 

I made editorial suggestions throughout the piece and edited things like mission colons and capitalization in title to match AP Stylebook. Please see below for details. 

But, well done! 👍

2023-10-12 18:25 UTC, setheliot commented on concepts/concepts/how-to-design-and-implement-an-effective-incident-response-strategy/index.md
> +# How to design and implement an effective incident response strategy
good catch.  This is NOT optional.. ..please delete this redundant title

2023-10-20 18:24 UTC, damonk10 approved these changes

2023-10-20 18:25 UTC, merged