[New Post] Shift Cloud Costs Left
build-on-aws/content pull request #755
Opened 2023-09-18 18:28 UTC by hassankhosseini

Add a new blog article for the AWS Livestream - working with Steph and Darko;

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I tell this story because I’ve been deeply embedded in cloud costs and the different methods and attempts companies have made to reduce cloud costs, which ones work and which ones don’t. I want to ma
Put bullets below on the title of your 3 points

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +If your [FinOps practice](https://www.infracost.io/finops/) is not engineering-led, it’s missing the main point. The cloud is priced based on usage, and only engineers can impact what is used. Let’s
What does engineering-led mean? Needs a little more

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +The usage component of this formula is fully within engineering control. Engineering choose which services to use, how they are configured, set up, and even how the usage of those resources scale.
Can you capitalize and bold so we know it related to the calculation clearly

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +The unit price component can be a financial decision. However, it is important to optimize this after the usage has been optimized. A thought exercise: If an instance is not being used at all, it doe
Can you capitalize and bold so we know it related to the calculation clearly. Define what Unit price and Usage is

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +When people talk about shifting cloud costs left, and go on to say the way they achieve it is by alerting engineers when a cost spike or anomaly happens—that’s not shifting left, that’s just marketin
Very long sentence, please split in two.

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I asked AI to tell me what “shifting left” means: “Shifting left in computing means moving processes or tasks earlier in the development cycle to catch and address issues earlier, rather than waiting
Does it really have to AI? Would rather its be a definition that can be linked

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +When we talk about shifting FinOps left, it means showing how much the cloud costs <u>before</u> we spend the money, it means checking for the right tags and values <u>before</u> we merge the pull re
too long a sentence

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +Cloud costs should be shifted left — proactive, not reactive, and done so with tooling. I don’t even mind if you don’t use [Infracost (it’s free and open source, so why not)](https://www.infracost.io
Can you be more explicit for the call to action?

2023-09-19 07:16 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I have some pretty strong beliefs when it comes to cloud costs, how they should be looked at, and who should be responsible for what.
Great story at the top but as a reader i dont know why i should read this blog? what will i get out of it? 
Also, who is the audience? you talk about devs so I assume it not them but this is a technical blog domain so it may need to adjusted to speak to them

2023-09-19 16:41 UTC, gaonkarr commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +<img src="/posts/shifting-cloud-costs-left-what-it-really-means/images/infracost-cost-optimization-formula.png" alt="Cloud cost optimization formula" width="60%" />
Please update this to following format:

`![This is the alt text for the image](images/where-this-image-is-stored.png)`

Example:

`![Cloud cost optimization formula](images/infracost-cost-optimization-formula.png)`

![Cloud cost optimization formula](images/infracost-cost-optimization-formula.png)

2023-09-20 02:06 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I asked AI to tell me what “shifting left” means: “Shifting left in computing means moving processes or tasks earlier in the development cycle to catch and address issues earlier, rather than waiting
I thought it might be fun ☺️ I worded it a little softer and added a confirmation from GitLab too.

2023-09-20 02:09 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I have some pretty strong beliefs when it comes to cloud costs, how they should be looked at, and who should be responsible for what.
Great point! Let me give it another go

2023-09-20 02:49 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +If your [FinOps practice](https://www.infracost.io/finops/) is not engineering-led, it’s missing the main point. The cloud is priced based on usage, and only engineers can impact what is used. Let’s
Great point - I moved the text around, and explained it first, then concluded. Does that look better?

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I want to make three points in this blog. These points are what you, as engineers can take to your management team to push for engineering led FinOps practice. I will also show you what tool you shou
comma after engineers

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I want to make three points in this blog. These points are what you, as engineers can take to your management team to push for engineering led FinOps practice. I will also show you what tool you shou
for **a** engineering led ...

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +I want to make three points in this blog. These points are what you, as engineers can take to your management team to push for engineering led FinOps practice. I will also show you what tool you shou
_I will also show you want tool is available as a first step...._

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +This is why the [FinOps practice](https://www.infracost.io/finops/) should be engineering-led. The core work that needs to be done under the FinOps umbrella requires engineering effort. Engineering i
Add a sentence at the end on what you want them to do with this information 
e.g. try working out your unit cost ...

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +Hey Chat GPT, define “shifting left”: “Shifting left in computing means moving processes or tasks earlier in the development cycle to catch and address issues earlier, rather than waiting until later
Please remove the chat GPT stuff and say the defintion. 
I would reorder to be 
Many companies discuss the concept of shifting cloud costs left, but what they actually do is not shifting left. Setting up alerting when a cost spike or anomaly happens is great, but that's not shifting left.
shifting left is defined as.... 
Setting up alerting when a cost spike or anomaly happens is great, but that's not shifting left. When you receive a production alert and quickly address the issue, that's not shifting left, the same concept applies to costs.

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +When we talk about shifting FinOps left, it means knowing how much the cloud costs <u>before</u> we spend the money. It means checking for the right tags and values <u>before</u> we merge the pull re
Again, what do you want them to do after

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +In the great words of Gwen Stefani, “this sh*t is bananas”: [cloud costs are complex](https://www.infracost.io/blog/why-are-cloud-costs-so-complex/). Here at [Infracost](https://www.infracost.io), we
Just say multi cloud, don't list

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +In the great words of Gwen Stefani, “this sh*t is bananas”: [cloud costs are complex](https://www.infracost.io/blog/why-are-cloud-costs-so-complex/). Here at [Infracost](https://www.infracost.io), we
Typo doesn't't

2023-09-20 10:27 UTC, awssteph commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +In the great words of Gwen Stefani, “this sh*t is bananas”: [cloud costs are complex](https://www.infracost.io/blog/why-are-cloud-costs-so-complex/). Here at [Infracost](https://www.infracost.io), we
Add at the end something like
thats why, us at infra cost want to make this information easier for you to see ...

2023-09-21 09:59 UTC, awssteph commented
Looks good @gaonkarr please review :)

2023-09-25 15:56 UTC, gaonkarr commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +In the great words of Gwen Stefani, *“this sh!t is bananas”*: [cloud costs are complex](https://www.infracost.io/blog/why-are-cloud-costs-so-complex/). Here at [Infracost](https://www.infracost.io),
I am a bit lost on this sentence formation. 
_Here at Infracost, we have a multi-cloud database of all resource prices from the major cloud providers, and it comes to 4 million prices!_

Should we make it something like:

_At Infracost, we maintain a comprehensive multi-cloud database comprising all resource prices from major cloud providers, totalling over 4 million prices!_

2023-09-25 15:57 UTC, gaonkarr commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +This is why the [FinOps practice](https://www.infracost.io/finops/) should be engineering-led. The core work that needs to be done under the FinOps umbrella requires engineering effort. Engineering i
We have right sizing article published, in case you want to link to it

https://community.aws/posts/rightsizing-the-right-way

2023-09-25 19:23 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +In the great words of Gwen Stefani, *“this sh!t is bananas”*: [cloud costs are complex](https://www.infracost.io/blog/why-are-cloud-costs-so-complex/). Here at [Infracost](https://www.infracost.io),
I like it! Will update

2023-09-25 19:24 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +This is why the [FinOps practice](https://www.infracost.io/finops/) should be engineering-led. The core work that needs to be done under the FinOps umbrella requires engineering effort. Engineering i
Also great link - will update!

2023-09-25 19:38 UTC, gaonkarr commented
Thanks @hassankhosseini Moving to one-step review! Will be published soon!

2023-09-25 19:41 UTC, gaonkarr commented
@scribwell this is one of the blogs for the BuildOn Live show. Ready for one-step review

2023-09-26 15:55 UTC, cobusbernard requested changes

2023-09-26 15:55 UTC, cobusbernard commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +Here is the first step to take: [Infracost is free and open source](https://www.infracost.io/), install it into your GitHub or GitLab now.
```suggestion
If you wanted to get started managing your costs, you can install [Infracost](https://www.infracost.io/) into your GitHub or GitLab accounts.
```

2023-09-26 15:55 UTC, cobusbernard commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +Here is the first step to take: [Infracost is free and open source](https://www.infracost.io/), install it into your GitHub or GitLab now.
@hassankhosseini : Suggesting this change, the previous version is too strong of a product pitch, please review.

2023-09-26 18:14 UTC, hassankhosseini commented on posts/shifting-cloud-costs-left-what-it-really-means/index.md
> +Here is the first step to take: [Infracost is free and open source](https://www.infracost.io/), install it into your GitHub or GitLab now.
Looks good - changes committed.

2023-09-26 20:54 UTC, cobusbernard approved these changes

2023-09-26 20:54 UTC, merged