New Post: Lost in AI Ethics? The Shared Responsibility Model Offers Clarity
build-on-aws/content pull request #760
Opened 2023-09-19 19:10 UTC by aws-banjo

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
N/A
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-09-19 20:13 UTC, cobusbernard commented
Thanks @aws-banjo, I'll get @mikegc-aws to take a look at this one. In the mean time, can you please look at the validation results and reduce the images sizes so long?

2023-09-19 20:14 UTC, cobusbernard requested changes
Adding flag for changes requested.

2023-09-21 15:19 UTC, damonk10 commented on posts/shared_resp_gen_ai/index.md
> +But, as history often does, it provides us with solutions. The [AWS Shared Responsibility Model](https://aws.amazon.com/compliance/shared-responsibility-model/), which once brought clarity to the wor
```suggestion
But as usual, history provides us with solutions. The [AWS Shared Responsibility Model](https://aws.amazon.com/compliance/shared-responsibility-model/), which once brought clarity to the world of cloud computing, can be our guiding light. Drawing inspiration from it, I suggest a structured model for Generative AI, aiming to define the roles and responsibilities from the core model providers to the end-users. 
```

2023-09-21 15:19 UTC, damonk10 commented on posts/shared_resp_gen_ai/index.md
> +However, the very power that makes Generative AI transformative also poses risks when misused or misunderstood:
I think one of the biggest challenges, which you don't touch on here, is that of ownership. Data ownership is a tricky question BEFORE you introduce model training (who, for instance, owns a conversation?). But add in the fact that art and design models only function by consuming and synthesizing countless human creations (usually without any compensation or acknowledgement), and it gets even more complicated, ethically.

2023-09-21 15:19 UTC, damonk10 commented on posts/shared_resp_gen_ai/index.md
> +For further reading I recommend you check out the Amazon Science blog on [responsible AI](https://www.amazon.science/blog/responsible-ai-in-the-generative-era?sc_channel=el&sc_campaign=genaiwave&sc_g
```suggestion
For further reading I recommend you check out the Amazon Science blog on [responsible AI](https://www.amazon.science/blog/responsible-ai-in-the-generative-era?sc_channel=el&sc_campaign=genaiwave&sc_geo=mult&sc_country=mult&sc_outcome=acq&sc_content=shared_resp_gen_ai),[Ethan Mollick's Substack](https://www.oneusefulthing.org/) on how to leverage AI, and [Amazon's Generative AI Hub](https://aws.amazon.com/generative-ai/?sc_channel=el&sc_campaign=genaiwave&sc_geo=mult&sc_country=mult&sc_outcome=acq&sc_content=shared_resp_gen_ai).
```

2023-09-27 05:02 UTC, mikegc-aws commented
If we have not already done so, can we run this by @diyaw pls.

2023-10-02 20:36 UTC, setheliot approved these changes

2023-10-02 20:36 UTC, setheliot commented on posts/shared_resp_gen_ai/index.md
> +But as usual, history provides us with solutions. The [AWS Shared Responsibility Model](https://aws.amazon.com/compliance/shared-responsibility-model/), which once brought clarity to the world of clo
This is specifically the shared responsibility model for security and compliance -- you should make that clear, and below where you share the diagram.   There are other shared responsibility models such as the [one for resilience](https://docs.aws.amazon.com/whitepapers/latest/disaster-recovery-workloads-on-aws/shared-responsibility-model-for-resiliency.html)

2023-11-01 20:46 UTC, merged