[New post] Generative AI apps with Amazon Bedrock - A getting started guide for Go developers
build-on-aws/content pull request #828
Opened 2023-10-05 17:34 UTC by abhirockzz

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE).**

2023-10-06 14:28 UTC, cherbk commented
@mikegc-aws please indicate if you have bandwidth to review this piece. thanks

2023-10-12 02:54 UTC, mikegc-aws requested changes
Made notes and sent via Slack.

2023-10-13 17:05 UTC, cherbk approved these changes

2023-10-18 19:55 UTC, damonk10 commented on concepts/amazon-bedrock-golang-getting-started/index.md
> +## Closing thoughts
```suggestion
## Closing Thoughts
```

2023-10-18 19:55 UTC, damonk10 commented on concepts/amazon-bedrock-golang-getting-started/index.md
> +I hope this proves useful for Go developers as a starting point on how to use Foundation models on Amazon Bedrock to power GenAI applications.
Please add two or three links to other pieces on next steps for the curious reader. What should they try next? What other information would be worth learning?

2023-10-19 17:56 UTC, abhirockzz commented on concepts/amazon-bedrock-golang-getting-started/index.md
> +I hope this proves useful for Go developers as a starting point on how to use Foundation models on Amazon Bedrock to power GenAI applications.
done

2023-10-19 18:02 UTC, damonk10 approved these changes

2023-10-19 18:18 UTC, merged