Adding new post: Five Ways to Accelerate Product Development for Deve…
build-on-aws/content pull request #854
Opened 2023-10-17 11:52 UTC by tierfour

…lopers

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the MIT-0 license.**

2023-10-17 17:18 UTC, alejtraws requested changes

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +Tech moves too quickly. I think it high time we all pumped the brakes a bit and took a little breather. Customers are patient. They’ll wait if you ask nicely. If your product manager is breathing dow
Not sure if we should say "breathing down your neck" or "tell'em"

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +Whether you’re a startup or a large enterprise, product teams are increasingly under pressure to innovate and release faster. Development on the cloud moves quickly and if you’re the one doing the de
oooooh I see, I like the change of tone, although, I still think (maybe just me) the first one may be a bit too informal (but will leave that to the blog owners to decide :D )

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +📣 **Shameless plug**: If you’re attending re:Invent 2023, I’ll be there showing you exactly how to get value out of the AWS Solutions Library. In the [ARC203 “Solve everyday challenges faster with AW
Can we add also we would be on the floor at the expo, in the solutions lounge, if they want to stop by and say hi?

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +* [Amazon CodeCatalyst](https://aws.amazon.com/codecatalyst/) - A fully managed unified development service that enables you to plan, execute and deliver applications faster.
Hmmmm I would consider AppRunner rather than code catalyst, I think it flows better and it helps developers deploy containers a lot faster

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +1. **Recognize two-way doors.** While some decisions are one-way doors, others are two-way doors, meaning they are reversible, and you can correct mistakes quickly.
This is amazon linguo, I would include an explanation before we use it. If that's too much, I would change to "take time to plan and make decisions on things that you can't easily modify, like pick containers vs traditional compute, and make quick decisions on topics that you can easily reverse and correct, like EKS vs ECS

2023-10-17 17:18 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +* [Application Monitoring with Amazon CloudWatch](https://aws.amazon.com/solutions/implementations/application-monitoring-with-cloudwatch/?did=sl_card&trk=sl_card)
Deprecating - Point to the OpenSearch one instead? https://aws.amazon.com/solutions/implementations/centralized-logging-with-opensearch/

2023-10-17 20:15 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +Tech moves too quickly. I think it high time we all pumped the brakes a bit and took a little breather. Customers are patient. They’ll wait if you ask nicely. If your product manager is breathing dow
checked and this is fine :D

2023-10-17 20:16 UTC, alejtraws commented on posts/five-ways-to-accelerate-product-development-for-developers/index.md
> +Whether you’re a startup or a large enterprise, product teams are increasingly under pressure to innovate and release faster. Development on the cloud moves quickly and if you’re the one doing the de
Checked and this is fine! :D

2023-10-18 18:06 UTC, alejtraws approved these changes

2023-10-18 21:24 UTC, cobusbernard approved these changes

2023-10-18 21:25 UTC, merged