[Post] 5 things i wish i knew when i was new to aws
build-on-aws/content pull request #859
Opened 2023-10-20 02:52 UTC by alejtraws

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the MIT-0 license.**

2023-10-22 10:55 UTC, tierfour requested changes
@alejtraws Made a few suggestion to improve readability. Overall, I like the tips and you have a good opinion. Just needs a little polish on a few of the sentences.

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +description: Here are 5 tips I wish I ad know when I started building on AWS. These tips will help you plan your journey to build on AWS and carry.
"... I wish I **had** ..."

Not sure what "... and carry" means?

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +I remember when I started building on AWS, the joy of infinite possibilities, the cloud at my fingertips to build anything I wanted. I hadn't decided what was going to be my first project yet, but I
```suggestion
I remember when I started building on AWS. The joy of infinite possibilities. The cloud at my fingertips to build anything I wanted. I hadn't decided what was going to be my first project yet but I was eager to start! But wait... start where?
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +I had been building traditional applications on prem, that was easy or at least something I was used to doing. But I found myself navigating through new services, features, and those infinite possibi
```suggestion
I had been building traditional applications on prem. That was easy or at least something I was used to doing. But I found myself navigating through many AWS services and features and those infinite possibilities started to feel a little too infinite!
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +I am sure that if you are new to AWS you may have felt the same way at some point of your AWS journey, so I wanted to share with you a few tricks that I have learned over the few years, that I wish I
```suggestion
I am sure that, if you are new to AWS, you may have felt the same way at some point of your AWS journey. So I wanted to share with you a few tricks that I have learned over the few years that I wish I had when I was new to AWS.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +AWS provides a broad set of services that are powerful enablers for anything you want to build, any type of application, and there is a lot to learn. Getting familiar with some of the basic concepts
```suggestion
AWS provides a broad set of services that are powerful enablers for anything you want to build, including any type of application. There is a lot to learn. Getting familiar with some of the basic concepts for permission management, networking on the cloud, and different compute options (EC2, Containers, Lambda) will help tremendously before you adventure into the AWS world.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +If you are building in a team, it helps to create a table that maps the different technologies to what others are familiar with, and then it will help new people that join your project to select the
```suggestion
If you are building in a team, it helps to create a table that maps the different technologies to what others are familiar with. Then it will help new people that join your project to select the right technology and AWS service.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +When starting to build on AWS there is always new things that need to be done, new things that you want to explore, new things to learn. Sometimes, it is good to stop, take a deep breath and just sim
```suggestion
When starting to build on AWS, there is always new things that need to be done, new things that you want to explore, and new things to learn. Sometimes it is good to stop, take a deep breath and simplify, focus, and just find a fun project you want to work on.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +First pick if you are going to either bring to AWS, a.k.a., a migration, or develop brand new and deploy it into AWS. Once you have picked the application, ensure it will be fun, something that can b
```suggestion
First, pick if you are going to either bring an existing application to AWS (a.k.a. a migration) or develop a brand new workload and deploy it into AWS. Once you have picked the application, ensure it will be fun, something that can be done relatively quickly, and then build a business case around it! Define success, key takeaways, decide on your technology, and have fun! This takes us to our next tip...
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +And yes, the list goes on and on... So as you build your application, plan with your application, do not forget to plan your [cloud foundation](https://aws.amazon.com/architecture/cloud-foundations/)
```suggestion
The list goes on and on... 

So as you build your application, plan with your application, do not forget to plan your [cloud foundation](https://aws.amazon.com/architecture/cloud-foundations/), the little things that you need to have into account that you will need along your journey, like Identity, or Network connectivity, or how to isolate workloads from one another.
```

This sentence reads a little confusing to me. Not sure what you're trying to say.

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +At the end of the day... who would buy a house without electric wiring, water supply, windows or doors, right? Think about your cloud foundation the same way, it allows you to actually run things smo
```suggestion
At the end of the day, who would buy a house without electric wiring, water supply, windows or doors, right? Think about your cloud foundation the same way. It allows you to run things smoothly.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +If you create a project plan to build your environment along with your workload you can make you have the tools needed in your environment to scale your workload according to your needs, like the key
```suggestion
If you create a project plan to build your environment along with your workload, make sure you have the tools needed in your environment to scale your workload according to your needs, like the key to unlock your house.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +If you create a project plan to build your environment along with your workload you can make you have the tools needed in your environment to scale your workload according to your needs, like the key
I'm not sure I follow the analogy here.

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +Sometimes we set goals for ourselves that are very large, or far away. A couple years ago... I set a goal for myself to build a IoT farm for my garden beds. I knew everything I wanted to do, but I ju
```suggestion
Sometimes we set goals for ourselves that are very large or far away. A couple of years ago I set a goal for myself to build a IoT farm for my garden beds. I knew everything I wanted to do but I just focused on the big picture. 
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +So, I pivoted, I set small victories for myself, buy the sensors, buy the new soil, configure it all in my raspberry pi, and send the data to the cloud for processing and build a small application. Y
```suggestion
So, I pivoted. I set small victories for myself such as buy the sensors, buy the new soil, configure it all in my raspberry pi, send the data to the cloud for processing and build a small application. You should see my tomato plant this year. I have been getting 15 tomatoes a week on average! 🍅🍅🍅
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +Celebrate small wins, with your peers, with your teammates, with your leadership, it will definitely keep the morale up, and it will also help you to pivot quickly if anything in your project needs t
```suggestion
Celebrate small wins with your peers, your teammates, and with your leadership. It will definitely keep the morale up and it will also help you to pivot quickly if anything in your project needs to be adjusted!
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +Unlimited resources is amazing, if you don't use the resources, you don't have to pay for them. AWS provides with the tools to ensure you keep your cost to a minimum when needed, but without the righ
```suggestion
Unlimited resources is amazing. If you don't use the resources, you don't have to pay for them. AWS provides you with the tools to ensure you keep your cost to a minimum. But without the right planning, optimization for resources can get expensive.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +Unlimited resources is amazing, if you don't use the resources, you don't have to pay for them. AWS provides with the tools to ensure you keep your cost to a minimum when needed, but without the righ
Again the sentence is a bit confusing. Not sure what you're trying to say at the end there.

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +I like to think about the cost about a profit center rather than a cost center. Wait... don't you pay for the resources? How is it generating profit for my business? Think about all the infrastructur
```suggestion
I like to think about the cost as a profit center rather than a cost center. Wait... don't you pay for the resources? How is it generating profit for my business? Think about all the infrastructure (or services) that you don't need to maintain. Operational hours can be shifted to build new features for your customers quicker, improving their experience.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +I hear all the questions often when working with new organizations moving to AWS... And the answer sometimes is yes and sometimes is not. Finding the right balance, between what stays on prem, what c
```suggestion
I hear these questions often when working with new organizations moving to AWS. The answer is sometimes yes and sometimes not when finding the right balance between what stays on prem and what comes to the cloud.
```

2023-10-22 10:55 UTC, tierfour commented on posts/5-tips-I-wish-I-had-when-I-was-New-to-AWS/index.md
> +And do not try to build everything from scratch yourself, AWS and AWS Partners build solutions that are ready to use, ready to deploy directly into your environment, that can help you with operating
```suggestion
Here's a bonus tip. Do not try to build everything from scratch yourself. AWS and AWS Partners build solutions that are ready to use and ready to deploy directly into your environment. Solutions can help you with operating your environment easier or even deploying your applications to AWS. Check some of this solutions in the [AWS Solutions Library](https://aws.amazon.com/solutions/)! There is a lot of good stuff in there!
```

2023-10-23 15:40 UTC, tierfour approved these changes
Nice updates. Easier to read.

2023-10-23 18:13 UTC, nivtrips commented
Couple of comments: we can rephrase this better for more clarity "A couple examples: Do I need traditional VMs? Well, that maps to Amazon EC2."

"Here're a few examples for better understanding: I need traditional VMs! Oh looks like Amazon EC2 will take care of that need".... some small suggestions for you to consider. 

Also, this sentence looks incomplete: "Amazon ECS, Am I going to use Kubernetes? Then Amazon EKS is the answer."

2023-10-23 18:15 UTC, nivtrips commented
Minor nit: I'd change "First: Decide" to "First, decide"

2023-10-23 18:18 UTC, nivtrips commented
Overall looks great! My other feedback which I thought of providing seems to have been already addressed. The only last comment would be to include a CTA url in each section, so if someone wants to continue reading on the topic, can.

2023-10-25 18:28 UTC, scribwell commented
@cobusbernard Alex's blog post is ready for one-step review.

2023-10-25 18:35 UTC, cobusbernard approved these changes

2023-10-25 18:36 UTC, merged