[New Tutorial] Deploying Amazon EKS Windows managed node groups and Fargate nodes
build-on-aws/content pull request #905
Opened 2023-11-08 14:25 UTC by berry2012

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-08 20:40 UTC, riferrei requested changes
Thanks for providing this tutorial. I have added a set of small request changes. Once those are provided, the tutorial is ready to proceed.

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +Windows Kubernetes containers allow organisations to easily migrate their existing Windows workloads to Amazon EKS.
I like the way you explained how this would work to help builders moving their workload, but it misses the why element. It would be nice if you could share at least one example of a use case where moving Windows workloads to containers will help builders, focusing less on the technical aspects and more on the business case. One example could be explaining about a legacy application written for Windows and dependent on Windows native API calls.

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +While Amazon EKS clusters must contain one or more Linux or Fargate nodes to run core system Pods that only run on Linux, such as CoreDNS, organizations seeking to reduce operational overhead in mana
I think this section doesn't belong here. You can explore it better in the overview section. Here, it sounds very much like a "FYI" type of statement.

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +* **Fargate Profile**: [AWS Fargate](https://aws.amazon.com/fargate/) is a compute engine for EKS that removes the need to configure, manage, and scale EC2 instances. Fargate ensures Availability Zon
Please change the link to Fargate to point to its getting started section in the docs, instead of the product landing page.

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +* **Managed Node groups**: With Amazon EKS managed node groups, you don't need to separately provision or register the Amazon EC2 instances that provide compute capacity to run your Kubernetes applic
> we will create a managed node group using `WINDOWS_FULL_2022_x86_64` AMI

It would be great if you could spend some lines explaining why necessarily this AMI. What does it make so especial?

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +## Step 2: Create the Cluster
Before starting this section, please spend some time walking through the `cluster-config.yaml` file before. It doesn't need to explain every single line, but only the key remarks. For example, why the user the need to flush every single type to CloudWatch, and the usage of the `NoSchedule` taint effect. Anything that is not obvious must be explained, as this tutorial is supposed to be a 200 level.

2023-11-08 20:40 UTC, riferrei commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +## Step 3: Deploy Sample Windows Application
By following the tutorial until the end, I could see that this app is a simple web app reachable via the browser. But it would be nice to provide a quick overview about what this application does, which runtime components it depends on (for instance IIS), etc.

2023-11-14 20:55 UTC, DalM2023 reviewed
1st round edit done. Please review.

2023-11-15 20:14 UTC, berry2012 commented on tutorials/navigating-amazon-eks/eks-cluster-windows-fargate/index.md
> +---
thanks for this feedback

2023-11-16 01:44 UTC, cherbk approved these changes

2023-11-16 01:44 UTC, cherbk approved these changes

2023-11-20 17:31 UTC, DalM2023 reviewed
Final editorial review complete.

2023-11-30 23:04 UTC, damonk10 approved these changes

2023-11-30 23:06 UTC, merged