Create idv idp machine learning solution
build-on-aws/content pull request #906
Opened 2023-11-08 21:57 UTC by kowsalyajaganathan

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-14 15:16 UTC, bketelsen requested changes
This article is technically sound, but has no sample code. In order to make it more useful, please either create the referenced application as a code sample or link to existing tutorials/sample solutions

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - Amazon Rekognition
```suggestion
  - amazon-rekognition
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - Amazon Textract
```suggestion
  - amazon-textract
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - Identity verification
```suggestion
  - identity-verification
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - Intelligent document processing
```suggestion
  - intelligent-document-processing
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - Machien learning
```suggestion
  - machine-learning
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - IDV
```suggestion
  - idv
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +  - IDP
```suggestion
  - idp
```

2023-11-14 15:16 UTC, bketelsen commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +In this blog, we discuss the solution for identity verification and intelligent document processing using  [**Amazon Rekognition**](https://aws.amazon.com/rekognition) and [**Amazon Textract**](https
```suggestion
In this blog, we discuss a solution for identity verification and intelligent document processing using  [**Amazon Rekognition**](https://aws.amazon.com/rekognition) and [**Amazon Textract**](https://aws.amazon.com/textract/). By adopting this solution, financial organizations can transform their mortgage application processes, making them faster, more secure, and ultimately providing a better experience for their customers.
```

2023-11-14 15:18 UTC, bketelsen commented
Please add a clear call to action or next steps for the builder to proceed on this learning path.

2023-11-14 18:55 UTC, cherbk approved these changes

2023-11-14 20:55 UTC, DalM2023 reviewed
1st round edit done. Ready for review.

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +2. API Gateway routes the request to one of the Lambda functions – Start Lending Analysis Lambda function. The Lambda function stores the uploaded document in S3 bucket and invokes the Amazon Textrac
```suggestion
2. API Gateway routes the request to one of the Lambda functions – Start Lending Analysis Lambda function. The Lambda function stores the uploaded document in the S3 bucket and invokes the Amazon Textract [**StratLendingAnalysis**](https://docs.aws.amazon.com/en_us/textract/latest/dg/API_StartLendingAnalysis.html) API to initiate the classification and analysis of an input document. Input for this API includes the lending document S3 URL and [**AWS Simple Notification Service (SNS)**](https://aws.amazon.com/sns/) Topic as NotificationChannel. StartLendingAnalysis API returns a job identifier (JobID) that is used to get the results. JobID can be stored in Amazon DynamoDB for easy retrieval in next steps.
```

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +The JSON response object includes information about the document classification type for a page, the page number, and the fields extracted by Analyze Lending as Key-Value pairs and signatures. You ca
```suggestion
The JSON response object includes information about the document classification type for a page, the page number, and the fields extracted by Analyze Lending as key-value pairs and signatures. You can implement business logic in the Lambda function to extract the required information from the response object. Optionally you can enrich the documents by detecting and redacting PII entities using [**Amazon Comprehend**](https://aws.amazon.com/comprehend/?nc2=h_ql_prod_ml_comp).
```

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +If you want to try your hands into implementing this solution, or read more about Identity Verification and Itelligent Document Processing, have a look at the following resources:
```suggestion
If you want to try your hands into implementing this solution, or read more about identity verification and Intelligent Document Processing, have a look at the following resources:
```

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +title: "How to create a Precise and Cost-Effective Identity Verification and Intelligent Document Processing Solution for Financial Applications"
```suggestion
title: "Create a Precise and Cost-Effective Identity Verification and Intelligent Document Processing Solution for Financial Applications Using Amazon Rekognition and Amazon Textract"
```

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +description: "Learn to design an ML powered solution to automate identity verification and document processing using Amazon Rekognition and Amazon Textract"
Descriptors are tough because they need to be 60 characters or fewer. The sentence can't repeat the messaging on the title or use the same words. It should focus on what solutions the reader gets from reading the piece. I wrote an example but please feel free to rewrite your own: 

```suggestion 
description: "Automate ID verification and document processing with ML solutions."
```

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +tags:
We can only use 5 tags. Please choose the best ones.

2023-11-14 20:55 UTC, DalM2023 commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +---
Hello! 

What an interesting topic! 

Good job opening with the reasons why the mortgage industry would need this information. You addressed the pain points well.  

The structure is good but there are spacing issues. Please make sure spacing is uniform throughout the blog. For ex, some places have the headline of the section followed by a paragraph with no space. But another section has a space between the two. Also make sure the spacing between paragraphs, within sections, is uniformed. 

I also corrected capitalization, title and grammar issues. Please see my noted below. 

Overall, well done! 👍🏼

2023-11-14 23:06 UTC, kowsalyajaganathan commented on concepts/create-idv-idp-machine-learning-solution/index.md
> +---
Thanks for taking time to review. I have made changes as requested!

2023-11-15 22:34 UTC, DalM2023 reviewed
2nd edit completed. Ready for final review.

2023-11-16 01:48 UTC, cherbk approved these changes

2023-11-16 16:05 UTC, damonk10 approved these changes

2023-11-16 17:31 UTC, damonk10 approved these changes

2023-11-16 17:31 UTC, merged