add a new article of "Exploration and Practice of Serverless Architecture Evolution in Microservices"
build-on-aws/content pull request #908
Opened 2023-11-10 04:49 UTC by betty714

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x ] The title of this pull request reflects the title of my content.
- [x ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-10 07:22 UTC, DennisTraub commented
Thank you for your submission.

Question: When finding smaller issues (typos, etc.), do you mind if I directly fix them, or do you prefer to do the fixes yourself?

2023-11-10 08:27 UTC, betty714 commented
Sure, please directly fix them. 😊


Thanks & Best Regards
Betty Zheng
Developer Advocate, GCR DevRel team



From: Dennis Traub ***@***.***>
Reply-To: build-on-aws/content ***@***.***>
Date: Friday, November 10, 2023 at 15:22
To: build-on-aws/content ***@***.***>
Cc: "Zheng, Betty" ***@***.***>, Assign ***@***.***>
Subject: Re: [build-on-aws/content] new post "Exploration and Practice of Serverless Architecture Evolution in Microservices" (PR #908)


Thank you for your submission.

Question: When finding smaller issues (typos, etc.), do you mind if I directly fix them, or do you prefer to do the fixes yourself?

—
Reply to this email directly, view it on GitHub<https://github.com/build-on-aws/content/pull/908#issuecomment-1805222699>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A6U62MFP2423WVY3LZPWN5TYDXI2JAVCNFSM6AAAAAA7FTSOXWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQMBVGIZDENRZHE>.
You are receiving this because you were assigned.Message ID: ***@***.***>

2023-11-16 15:38 UTC, cherbk commented
@betty714 Hi Betty- is this piece still being reviewed by Dennis and Francois?

2023-11-17 02:14 UTC, betty714 commented
> @betty714 Hi Betty- is this piece still being reviewed by Dennis and Francois?

Hi, @cherbk I think so. They are currently focused on preparing the content for re:Invent and they need an additional week for content review.

2023-11-21 10:23 UTC, DennisTraub requested changes
I was only able to review about 50% of the article in the timeframe I allotted for the task. Will revisit later.

In general, the article touches too many different topics and it is unclear to me what it is about. It also seems to make a lot of assumptions about prior knowledge by the reader, including the specifics of the presented use case.

Please consider reducing the scope of the article, clearly introducing the relevant background, and then covering the technical details.

Additionally, the article needs to be reviewed for style, structure, and  correct usage of AWS terms and service names.

2023-11-21 10:23 UTC, DennisTraub commented on tutorials/Exploration-and-Practice-of-Serverless-Architecture-Evolution-in-Microservicesindex/index.md
> +![Load banlancer ](./images/4-ALB%2BLambda.png)
One target is sitting between two target groups. Does that have any significance?

2023-11-21 10:23 UTC, DennisTraub commented on tutorials/Exploration-and-Practice-of-Serverless-Architecture-Evolution-in-Microservicesindex/index.md
> +| Scalable                        | Default 10000 RPS                                            | N/A                                                         | 10 * Lambda's reserved concurrency/sec
Does "N/A" under ALB mean that ALBs are not scalable?

2023-11-21 10:23 UTC, DennisTraub commented on tutorials/Exploration-and-Practice-of-Serverless-Architecture-Evolution-in-Microservicesindex/index.md
> +|  Cost                           | Within 3 billion/month: $1.00/million requests & Over3 billion requests/month: $0.90 p/million requests. | 0.0225 USD/hour +（LCU）0.008 USD/hour              | With
"Within 3 billion/month..." 3 billion what?

Also, is mentioning different price tiers even relevant when you only have 100,000 requests per hour?

2023-11-21 10:23 UTC, DennisTraub commented on tutorials/Exploration-and-Practice-of-Serverless-Architecture-Evolution-in-Microservicesindex/index.md
> +|  Cost                           | Within 3 billion/month: $1.00/million requests & Over3 billion requests/month: $0.90 p/million requests. | 0.0225 USD/hour +（LCU）0.008 USD/hour              | With
What is LCU?

2023-11-21 10:23 UTC, DennisTraub commented on tutorials/Exploration-and-Practice-of-Serverless-Architecture-Evolution-in-Microservicesindex/index.md
> +After creating an empty Lambda, should to upload and deploy the  package. As mentioned above, the service is based on gRPC, and be keeping the business processing part of the code unchanged. the busi
"After creating an empty Lambda, should to upload and deploy the package."

Please check this sentence, I don't understand what it means.

2024-01-08 11:12 UTC, DennisTraub commented
Thank you for your contribution and the effort put into this article. After careful consideration, we've decided to go in a different direction at this time. We appreciate your understanding and look forward to collaborating on future projects. Your involvement in our community is greatly valued.

2024-01-08 11:12 UTC, closed without merging