Sending Events from DynamoDB using Eventbridge Pipes
build-on-aws/content pull request #915
Opened 2023-11-12 21:05 UTC by kaizadwadia

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ x ] The title of this pull request reflects the title of my content.
- [ x ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-14 23:24 UTC, riferrei requested changes

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +EventBridge Pipes provide a no-code way to automatically replicate events between EventBridge buses, SQS/SNS topics, and DynamoDB Streams. A common serverless pattern is to detect DynamoDB table upda
> A common serverless pattern

Is this document somewhere? If so, where are the links?

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +EventBridge Pipes provide a no-code way to automatically replicate events between EventBridge buses, SQS/SNS topics, and DynamoDB Streams. A common serverless pattern is to detect DynamoDB table upda
If there are scenarios where using a custom Lambda function still applies, you need to detail here. The point is not only to sell product features, but to share architecture guidance.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +You can now start inserting items into the table through the console, SDKs, or other AWS services. Make sure the items contain the configured partition key and sort key. The other attributes like Sco
Is it possible to provide the steps of doing this in the tutorial? Maybe using the console?

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +To enable streams on the table, in the DynamoDB console select the "GameScores" table and go to the "Exports and Streams" tab. Scroll all the way down to "DynamoDB stream details" and click "Turn on"
Let the reader know if there are any consequences of doing this. Is there any charges associated? Will it slow it down the table? Detail those things will increase the trust from the reader on your content.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +After going to the next step, click on "All Events" as the event source. This may display a warning but we do want to have visibility into whatever events are sent to the bus. We can leave everything
> This may display a warning

Which warning? Please detail in the tutorial what the reader should expect to see.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +For the target, select "AWS service" and for the target, from the dropdown select "CloudWatch log group". Name the log group "game-events-log". Note that if we use infrastructure as code, we would ad
Tutorial must keep the consistency on what approach they are leading the reader. If everything is being done via the console, you should abstain from mentioning a different approach. This creates more confusion than benefit.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +### Step 3: Creating the pipe
I think this section could use a more detail explanation about the concept of pipe. Maybe something as simple as explaining that the pipe is responsible for the actions that will carry over the events through the buses and apply data mutation operations such as transformations, filtering, etc. Always assume the reader doesn't know everything about the product.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +We have now learned how to transform and filter the inputs. Notice that there is also the Enrichment feature. This is useful if you want to enrich the data using a Lambda function, a Step Function or
This is a great place to lead the reader to consume another content that provides the steps to learn about event enrichment.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +{
It would be beneficial for the reader to explain the syntax of this JSON document. Moreover, provides links that would help the reader to learn more about advanced examples.

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +Through this step-by-step guide, we created an end-to-end serverless event pipeline using Amazon EventBridge Pipes. By simply pointing and clicking in the AWS Management Console, we set up a Pipe tha
> instead of plumbing

I would be careful with the word plumbing. In practice, this is still a lot of plumbing to get things done, just not one that is done programmatically. I would just say: "focus on the application functionality."

2023-11-14 23:24 UTC, riferrei commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +Pipes simplified several key tasks for our use case: capturing DynamoDB events, filtering and transforming the event payload, and routing events to the target EventBridge bus. We also saw how to opti
Did it? I saw the example of filtering and transformation, but not the one about enrichment. You have mentioned is possible, but not necessarily provided an example.

2023-11-15 13:00 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +EventBridge Pipes provide a no-code way to automatically replicate events between EventBridge buses, SQS/SNS topics, and DynamoDB Streams. A common serverless pattern is to detect DynamoDB table upda
It is here: https://aws.amazon.com/blogs/database/dynamodb-streams-use-cases-and-design-patterns/. However, it uses Lambda not Pipes.

> This post describes some common use cases you might encounter, along with their design options and solutions, when migrating data from relational data stores to [Amazon DynamoDB](https://aws.amazon.com/dynamodb/).
We will consider how to manage the following scenarios:
How do you set up a relationship across multiple tables in which, based on the value of an item from one table, you update the item in a second table?
_How do you trigger an event based on a particular item change?_

I changed it to "A common use case for DynamoDB streams..." though to be more specific and hyperlinked it to this post.

2023-11-15 13:09 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +You can now start inserting items into the table through the console, SDKs, or other AWS services. Make sure the items contain the configured partition key and sort key. The other attributes like Sco
Done,

> However, in cases where the desired target is not in the [list of targets supported by Eventbridge Pipes](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-target.html), or more complex operations need to be performed during transformation such as enrichment of the data from other sources, a custom Lambda function is still necessary. That being said, Eventbridge Pipes still allows simple code-free integrations for a range of different services including [but not limited to DynamoDB streams](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-source.html).

2023-11-15 13:17 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +To enable streams on the table, in the DynamoDB console select the "GameScores" table and go to the "Exports and Streams" tab. Scroll all the way down to "DynamoDB stream details" and click "Turn on"
> Keep in mind that enabling streams does not consume any read or write capacity units (RCUs or WCUs), and so will not affect the performance of the table. However, the data in the streams is stored in shards, and this storage is something that is charged seperately from the table charges. You also pay for accessing the stream records. If you enable streams on an on-demand capacity mode table, you pay per request for the stream records. If the table uses provisioned capacity, stream requests are free but you pay for shard storage and data transfer. Stream records are kept for 24 hours by default. So shards will accumulate over time as records expire. Make sure to delete the table when no longer needed to stop incurring shard storage charges.

2023-11-15 13:27 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +After going to the next step, click on "All Events" as the event source. This may display a warning but we do want to have visibility into whatever events are sent to the bus. We can leave everything
The warning is shown in the image. Updated to make it clearer

> 
After going to the next step, click on "All Events" as the event source. This may display a warning (as displayed in the image below) but we do want to have visibility into whatever events are sent to the bus. The warning is shown because rules are generally used to filter events coming into the Event bus, and our rule is doing no filtering. You may create rules that performs filtering but for this example we will perform filtering prior to adding the event to the event bus and  We can leave everything else in this step as is and continue.

2023-11-15 13:40 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +We have now learned how to transform and filter the inputs. Notice that there is also the Enrichment feature. This is useful if you want to enrich the data using a Lambda function, a Step Function or
> We will now create the Eventbridge Pipe. Eventbridge Pipes are a simple, no-code integration service that connects sources to targets. Pipes also supports more advanced capabilities including transformations as well as enrichment using an API, a Step Function or an AWS Lambda function. We will use Pipes to read data from the DynamoDB stream and write it to the custom event bus we created in the last section.

2023-11-15 13:50 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +### Step 3: Creating the pipe
> We will now create the Eventbridge Pipe. Eventbridge Pipes are a simple, no-code integration service that connects sources to targets. Pipes also supports more advanced capabilities including transformations as well as enrichment using an API, a Step Function or an AWS Lambda function. We will use Pipes to read data from the DynamoDB stream and write it to the custom event bus we created in the last section.

2023-11-15 13:54 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +Pipes simplified several key tasks for our use case: capturing DynamoDB events, filtering and transforming the event payload, and routing events to the target EventBridge bus. We also saw how to opti
Removed

>Pipes simplified several key tasks for our use case: capturing DynamoDB events, routing events to the target EventBridge bus, and optionally filtering and transforming the event payload.

2023-11-15 14:00 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +We have now learned how to transform and filter the inputs. Notice that there is also the Enrichment feature. This is useful if you want to enrich the data using a Lambda function, a Step Function or
Removing this part because we don't have another data source so it would essentially just be a transformation. I also don't want to have any custom code here to keep it simple (hence this section also being optional, even though the "transformer" isn't really code)

2023-11-15 14:12 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +Through this step-by-step guide, we created an end-to-end serverless event pipeline using Amazon EventBridge Pipes. By simply pointing and clicking in the AWS Management Console, we set up a Pipe tha
True, removed this

2023-11-15 14:13 UTC, kaizadwadia commented
Thank you for the review Ricardo!

2023-11-15 14:33 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +EventBridge Pipes provide a no-code way to automatically replicate events between EventBridge buses, SQS/SNS topics, and DynamoDB Streams. A common serverless pattern is to detect DynamoDB table upda
Changed it
> However, in cases where the desired target is not in the [list of targets supported by Eventbridge Pipes](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-target.html), or more complex operations need to be performed during transformation such as enrichment of the data from other sources, a custom Lambda function is still necessary. That being said, Eventbridge Pipes still allows simple code-free integrations for a range of different services including [but not limited to DynamoDB streams](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-pipes-event-source.html).

2023-11-15 14:33 UTC, riferrei commented
> Thank you for the review Ricardo!

Thank YOU for accommodating the changes so quickly. Looking good. 👍🏻

2023-11-15 14:34 UTC, riferrei approved these changes

2023-11-15 14:40 UTC, kaizadwadia commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +For the target, select "AWS service" and for the target, from the dropdown select "CloudWatch log group". Name the log group "game-events-log". Note that if we use infrastructure as code, we would ad
Removed that part

2023-11-15 15:19 UTC, cherbk approved these changes

2023-11-15 23:53 UTC, DalM2023 reviewed
1st edit done. Ready for author review.

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +![Eventbridge Rules]( images/rules.png "Eventbridge Rules")
Please make sure it's "EventBridge" as it's a brand name. 

```suggestion
![EventBridge Rules]( images/rules.png "EventBridge Rules")
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +After going to the next step, click on "All Events" as the event source. This may display a warning (as displayed in the image below) but we do want to have visibility into whatever events are sent t
```suggestion
After going to the next step, click on "All Events" as the event source. This may display a warning (as displayed in the image below) but we do want to have visibility into whatever events are sent to the bus. The warning is shown because rules are generally used to filter events coming into the Event bus, and our rule is doing no filtering. You may create rules that performs filtering but for this example we will perform filtering prior to adding the event to the Event bus. This rule is just to have visibility into the Event bus. We can leave everything else in this step as is and continue.
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +### Step 3: Creating the pipe
```suggestion
### Step 3: Creating the Pipe
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +We will now create the Eventbridge Pipe. Eventbridge Pipes are a simple, no-code integration service that connects sources to targets. Pipes also supports more advanced capabilities including transfo
```suggestion
We will now create the Eventbridge Pipe. Eventbridge Pipes are a simple, no-code integration service that connects sources to targets. Pipes also supports more advanced capabilities including transformations as well as enrichments using an API, a Step function or a Lambda function. We will use Pipes to read data from the DynamoDB stream and write it to the custom event bus we created in the last section.
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +### Step 4: Testing the integration
```suggestion
### Step 4: Testing the Integration
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +### Optional: Filtering and transforming the payload
```suggestion
### Optional: Filtering and Transforming the Payload
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +Now that we configured filtering, let's transform the payload using the "Target Input Transformer". To do this, click on the "Target" Icon on the pipe diagram and scroll down. Close to the bottom the
```suggestion
Now that we configured filtering, let's transform the payload using the "Target Input Transformer". To do this, click on the "Target" icon on the pipe diagram and scroll down. Close to the bottom there is a dropdown called "Target Input Transformer", which should be expanded. Paste the following transformer in the middle column:
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +We can now play around with the Table to see how the events get recorded. Navigate to the DynamoDB table and change the fields in the old item we placed in the table, like how we did in the previous
```suggestion
We can now play around with the table to see how the events get recorded. Navigate to the DynamoDB table and change the fields in the old item we placed in the table, like how we did in the previous section. Notice how it got sent because the filtering statement matched the GameId. How about if we create another item with another GameId? We see that gets filtered out. Now any new event that gets sent through Pipes will now get transformed to a format that looks similar to this one, instead of one that looks like the default output of a DynamoDB stream:
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +## Clean-up
```suggestion
## Clean Up
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +To clean-up your AWS account, remember to delete the following:
```suggestion
To clean up your AWS account, remember to delete the following:
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +By leveraging EventBridge Pipes for event ingestion and integration, we can quickly connect various services and data sources without managing complex application code. Pipes provide a no-code way to
Beautiful conclusion! But, we want to invite readers to stay in the blog repository longer. Please add a sentence or two that is apropos of your topic and with 2-3 blog links.  

EX: "To learn more about X, visit (LINK) and (LINK)."

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +tags:
We need 5 tags. Please add 1 more.

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +description: "A no-code integration between Amazon DynamoDB and Eventbridge"
Good job making this descriptor fewer than 50 characters. But, it can't repeat the messaging on the title or use the same phrases, words. It should also focus on what solution the reader gets from reading the piece. I wrote an example below but feel free to rewrite. 

```suggestion
description: "Save time with a manageable no-code integration to replicate events."


```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +title: "Sending Events from DynamoDB using Eventbridge Pipes"
```suggestion
title: "Sending Events From DynamoDB Using EventBridge Pipes"
```

2023-11-15 23:53 UTC, DalM2023 commented on tutorials/ddb-streams-to-eb-pipes/index.md
> +---
Hello! 

Nice opening paragraph of stating the problem, the consequence of the problem and the solution. Well done! The structure, narrative pacing and tone are solid. 

I corrected titles to AP Style and proper names. Please review that all proper names begin with a capital letter. Most notably, “Amazon EventBridge” is sometimes “Amazon Eventbridge”. The former is the correct legal brand name. Please rake through the piece and make the corrections. 

Please see my notes below for more information.

2023-11-16 09:30 UTC, kaizadwadia commented
Thank you for the review! I have addressed the changes.

2023-11-20 17:48 UTC, DalM2023 reviewed
Author revisions requested. Please make final editorial changes.

2023-11-21 19:13 UTC, DalM2023 reviewed
Editorial review complete.

2023-12-06 20:03 UTC, merged