Vector store rag bedrock
build-on-aws/content pull request #921
Opened 2023-11-15 20:42 UTC by debnsuma

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ ] The title of this pull request reflects the title of my content.
- [ ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-17 19:50 UTC, riferrei requested changes

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +So, whether you are a seasoned data engineer, a machine learning enthusiast, or someone curious about the latest trends in AI, join us as we unravel the complexities of vector embeddings and discover
> discover how AWS's advanced capabilities can supercharge them

I loved your strong introduction. But I would remove the above to keep your messaging towards being educational and not sales-y. Unless you think that part is really needed.

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +The advent of **Convolutional Neural Networks (CNNs)**, especially those pre-trained on extensive datasets like [ImageNet](https://www.image-net.org/download.php), has revolutionized the way we under
CNNs don't seem to be a common topic. Would you mind in providing a single-sentence explaining of what it is, or perhaps linking to source?

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Let's see how we can use [Amazon Titan Embeddings model](https://aws.amazon.com/bedrock/titan/) to create an embedding vector using [Amazon Bedrock](https://aws.amazon.com/bedrock/?refid=22360ac0-298
Before moving further, I think it would be great to share here that these distance metrics are heavily used in Vector databases such as OpenSearch. This may help the reader understand that the "cosine" is not just a feature of a product, but something greater.

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector indexing
This section is super interesting, but finishing read it leaves a "but how about in practice this looks like". Would be possible to provide an example? Even a minimal one? I feel there is enough theory baggage in this blog post that can use a periodical practical flush to clear the brain.

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector indexing
This is particularly important because after this section, there will be a considerable amount of theory (LSH, PO) until you reach the Vector Library's section that it is harder to provide practical examples.

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector libraries
I know this may be me asking a lot, but would be possible to provide examples of applications using each library? It's okay if this is too much. The blog post is already awesome AS-IS.

2023-11-17 19:50 UTC, riferrei commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +AWS offers various services for selecting the right vector database, such as **Amazon Kendra** for low-code solutions, **Amazon OpenSearch** Service for NoSQL enthusiasts, and **Amazon RDS/Aurora** P
> for NoSQL enthusiasts

I feel this may sound more negative than positive. OpenSearch can be used by people without heavy NoSQL knowledge.

2023-11-21 18:49 UTC, cherbk approved these changes

2023-11-21 19:00 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +So, whether you are a seasoned data engineer, a machine learning enthusiast, or someone curious about the latest trends in AI, join us as we unravel the complexities of vector embeddings and discover
Thanks Ricardo, makes complete sense. Fixed.

2023-11-21 19:00 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +The advent of **Convolutional Neural Networks (CNNs)**, especially those pre-trained on extensive datasets like [ImageNet](https://www.image-net.org/download.php), has revolutionized the way we under
Thanks Fixed

2023-11-21 19:01 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Let's see how we can use [Amazon Titan Embeddings model](https://aws.amazon.com/bedrock/titan/) to create an embedding vector using [Amazon Bedrock](https://aws.amazon.com/bedrock/?refid=22360ac0-298
Great point, fixed.

2023-11-21 19:02 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector indexing
Yes, i added a practical use case of e-commerce to add some context. Thank you once again.

2023-11-21 19:04 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +AWS offers various services for selecting the right vector database, such as **Amazon Kendra** for low-code solutions, **Amazon OpenSearch** Service for NoSQL enthusiasts, and **Amazon RDS/Aurora** P
Sure, that was our messaging so I didnt change, but your point is very valid, so I removed it.

2023-11-21 19:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector libraries
Yah, this might make the blog lengthy, but I have plans to write some articles on few these libraries, as and when i write, shall add the URL here.

2023-11-21 20:10 UTC, riferrei approved these changes

2023-11-27 18:10 UTC, DalM2023 reviewed
1st editorial review done. Author revision requested.

2023-11-27 18:10 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive int
```suggestion
We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive into part two of this blog series. Here, we'll focus on leveraging different AWS services for storing vector embeddings. This will include an in-depth look at how these services synergize with Large Language Models (LLMs) to enhance AI and machine learning applications.
```

2023-11-27 18:10 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +tags:
We need 5 tags. Please add one more.

2023-11-27 18:10 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +description: "Explore the transformative world of vector embeddings in AI, and learn how Amazon Bedrock, Amazon Aurora, and LangChain revolutionize data handling and machine learning applications."
While this is an excellent description we can't use it as is. The descriptions need to be 60 characters or fewer. They can't repeat the messaging in the title or use the same words. They should focus on what solution the reader gets from reading the piece. I wrote an example below but feel free to rewrite. 

```suggestion
description: "Revolutionize big data handling and machine learning applications."
```

2023-11-27 18:10 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +---
Hello!

This is a well written blog with solid structure and sources.  My edits focus primarily on correcting titles to AP Style and proper name capitalization errors. I made editorial suggestions for the intro based on the requirements of the Community.AWS Editorial Review Process. Please see my notes below. 

Overall, well done. 👍🏼

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +description: "Explore the transformative world of vector embeddings in AI, and learn how Amazon Bedrock, Amazon Aurora, and LangChain revolutionize data handling and machine learning applications."
done

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +tags:
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive int
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector databases
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector libraries
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +In the above example, we connected each new node to the 2 most similar neighbors, but we could have chosen another number of similar neighbors. When building the graph, we need to decide on a metric
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +### Delving Deeper into Vector Storage
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## How can we store embeddings?
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +#### Creating embeddings using LangChain
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +### The versatility of embeddings in applications
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +This marks the beginning of our two-part blog series. In this first installment, we delve into the fundamentals of vector embeddings. We'll explore what embeddings are, why they're crucial in the rea
Thanks, fixed

2023-12-04 18:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +In the rapidly evolving landscape of data engineering and machine learning, the concept of vector embeddings has emerged as a cornerstone for a myriad of innovative applications. As we navigate throu
Thanks fixed.

2023-12-06 19:39 UTC, cherbk approved these changes

2023-12-07 04:59 UTC, DalM2023 reviewed
2nd editorial review complete. Author revisions requested.

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +This marks the beginning of our two-part blog series. In this first installment, we delve into the fundamentals of vector embeddings. We'll explore what embeddings are, why they're crucial in the rea
You can use "LLM" from here on out since the concept and abbreviation was introduced earlier. 

```suggestion
This marks the beginning of our two-part blog series. In this first installment, we delve into the fundamentals of vector embeddings. We'll explore what embeddings are, why they're crucial in the realm of AI, and delve into the methods of storing and indexing them. This foundational understanding sets the stage for part two, where we'll navigate the various vector storage solutions available on AWS. Here, we'll discuss how to effectively store your embeddings and utilize them in conjunction with  LLMs to create robust, AI-powered applications. Additionally, we will introduce and leverage `LangChain`, an [tool](https://python.langchain.com/docs/get_started/introduction) that enhances our journey into the practical application of these concepts, demonstrating how to seamlessly integrate these technologies into real-world AI solutions.
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +When it comes to text analysis, several strategies exist for converting words into vectors. Initially, one of the simpler techniques was the **bag-of-words model**. Here, words within a text are repr
```suggestion
When it comes to text analysis, several strategies exist for converting words into vectors. Initially, one of the simpler techniques was the **bag-of-words model**. Here, words within a text are represented by their frequency of occurrence. [Scikit-learn](https://scikit-learn.org/stable/), a powerful Python Library, encapsulates this method within its `CountVectorizer` tool. For a while, this was the standard—until the introduction of **word2vec**.
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +### The versatility of Embeddings in Applications
```suggestion
### The Versatility of Embeddings in Applications
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## How can we Store Embeddings?
```suggestion
## How Can We Store Embeddings?
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector indexing
```suggestion
## Vector Indexing
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Its a technique that divides the vector space into smaller subspaces and quantizes each subspace separately. This reduces the dimensionality of the vectors and allows for efficient storage and search
Does this need a line between the title and body? The other sections have that uniformity.

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Further, we learned how to create vector embeddings using tools like Amazon Bedrock with Boto3, as well as the open-source library LangChain. This provided us with practical insights into embedding g
```suggestion
Further, we learned how to create vector embeddings using tools like Amazon Bedrock with Boto3, as well as the Open Source Library LangChain. This provided us with practical insights into embedding generation and manipulation.
```

2023-12-07 04:59 UTC, DalM2023 commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive int
```suggestion
We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive into part two of this blog series. Here, we'll focus on leveraging different AWS services for storing vector embeddings. This will include an in-depth look at how these services synergize with LLMs to enhance AI and machine learning applications.
```

2023-12-07 05:04 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +When it comes to text analysis, several strategies exist for converting words into vectors. Initially, one of the simpler techniques was the **bag-of-words model**. Here, words within a text are repr
fixed

2023-12-07 05:04 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +### The versatility of Embeddings in Applications
fixed

2023-12-07 05:04 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## How can we Store Embeddings?
fixed

2023-12-07 05:05 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +## Vector indexing
fixed

2023-12-07 05:06 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Its a technique that divides the vector space into smaller subspaces and quantizes each subspace separately. This reduces the dimensionality of the vectors and allows for efficient storage and search
I didnt want to start the bullet points right after the tile, hence added one line in the middle

2023-12-07 05:07 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +Further, we learned how to create vector embeddings using tools like Amazon Bedrock with Boto3, as well as the open-source library LangChain. This provided us with practical insights into embedding g
Fixed

2023-12-07 05:07 UTC, debnsuma commented on tutorials/vector-embeddings-and-rag-demystified/index.md
> +We also examined various techniques for vector indexing and the use of vector libraries as storage solutions for our embeddings. With these foundational concepts in place, we're now ready to dive int
fixed

2023-12-07 05:08 UTC, debnsuma commented
Pushed all the changes w.r.t to the 2nd review

2023-12-07 19:11 UTC, cherbk approved these changes

2023-12-12 18:24 UTC, damonk10 approved these changes

2023-12-12 18:25 UTC, merged