What is SageMaker?
build-on-aws/content pull request #930
Opened 2023-11-18 12:28 UTC by kaizadwadia

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ x ] The title of this pull request reflects the title of my content.
- [ x ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-12-08 03:05 UTC, abhirockzz requested changes
Thanks for the blog! I have suggested minor updates along with (lots of) spelling corrections :) We should be good to go once these are taken care of

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +## Key Capabilities and features of Amazon Sagemaker
fix spelling Sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +SageMaker makes model building easier by providing pre-built containers and algorithms. You provide an algorithm, training code, and dataset, and train it on the provided infrastructure. In addition
fix spelling sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +You can use sagemaker to easily deploy machine learning models for real-time or batch predictions. Once your model is trained in SageMaker, it can be deployed to create an endpoint. This endpoint is
fix spelling sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +Sagemaker Canvas is a GUI interface that allows you to quickly build, train and deploy machine learning models without writing any code. With Sagemaker Canvas you can drag and drop prebuilt component
fix spellings Sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +### Sagemaker Clarify
fix spelling Sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +Sagemaker Clarify lets you detect bias in models and explains predictions by providing metrics to identify biases against certain groups in training data and models. you can get individual prediction
fix spelling Sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +### Sagemaker Data Wrangler
fix spelling Sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +You can use Sagemaker Ground Truth to create highly accurate training datasets. Ground Truth helps you with data labeling tasks at sacle. And ground truth provides you with tools to verify, analyze a
fix spelling Sagemaker -> SageMaker
fix spelling sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +You can use sagemaker ML Governance to monitor the entire process of your machine learning models from training to deployment. This give you the ability to deploy responsible models by monitoring the
fix spelling sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +Fraud is a major challenge that many companies face today, including [Mastercard](https://aws.amazon.com/solutions/case-studies/mastercard-ai-ml-testimonial). With the rise of online transactions and
fix spelling sagemaker -> SageMaker

2023-12-08 03:05 UTC, abhirockzz commented on concepts/what-is-sagemaker/index.md
> +Sgaemaker MLOps gives you the abilities to deploy ML models at scale by providing CI/CD pipelines for model building and deployment, model monitoring, automated drift detection and retraining, integr
fix spelling Sgaemaker -> SageMaker

2023-12-11 17:27 UTC, cherbk commented
@kaizadwadia The technical review has been completed. Please take a moment to review and incorporate the suggested changes in the PR. Thank you!

2023-12-11 19:43 UTC, kaizadwadia commented
Changes have been made. Thank you for the review!

2023-12-12 15:25 UTC, cherbk approved these changes

2023-12-13 06:50 UTC, DalM2023 reviewed
1st editorial review complete. Author revision requested.

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +## Key Capabilities and features of Amazon SageMaker
```suggestion
## Key Capabilities and Features of Amazon SageMaker
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +SageMaker offers a fully-managed machine learning platform to help engineers and data scientists quickly build, train, and deploy high-quality models at any scale. You need to specify the compute res
```suggestion
SageMaker offers a fully managed machine learning platform to help engineers and data scientists quickly build, train, and deploy high quality models at any scale. You need to specify the compute resources you need like GPU type and number of instances. By using features such as [GPU instances and training compilers](https://aws.amazon.com/sagemaker/faqs), training time and costs can be significantly reduced.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +You can use sagemaker to easily deploy machine learning models for real-time or batch predictions. Once your model is trained in SageMaker, it can be deployed to create an endpoint. This endpoint is
```suggestion
You can use SageMaker to easily deploy machine learning models for real time or batch predictions. Once your model is trained in SageMaker, it can be deployed to create an endpoint. This endpoint is a REST API that receives prediction requests, runs the request through the deployed model, and returns predictions.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Managing machine learning workflows
```suggestion
### Managing Machine Learning Workflows
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Building models
```suggestion
### Building Models
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Training models
```suggestion
### Training Models
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Deploying models
```suggestion
### Deploying Models
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Monitoring models
```suggestion
### Monitoring Models
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +SageMaker Clarify lets you detect bias in models and explains predictions by providing metrics to identify biases against certain groups in training data and models. you can get individual prediction
```suggestion
SageMaker Clarify lets you detect bias in models and explains predictions by providing metrics to identify biases against certain groups in training data and models. You can get individual predictions, which will show you which input features most influenced a specific prediction, which will help in debugging the behaviour of the model.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +You can use this feature to quickly prepare and clean data for machine learning without writing any code. you can also use it to combine datasets, transform data, handle missing values, and perform o
```suggestion
You can use this feature to quickly prepare and clean data for machine learning without writing any code. You can also use it to combine datasets, transform data, handle missing values, and perform other data preparation and feature engineering tasks to get data ready for training machine learning models.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +Amazon SageMaker JumpStart gives you quick access to prebuilt machine learning solutions, sample notebooks, and hosted models that can be customized and deployed with little machine learning expertis
```suggestion
Amazon SageMaker JumpStart gives you quick access to prebuilt machine learning solutions, sample notebooks, and hosted models that can be customized and deployed with little machine learning expertise required. JumpStart allows you to choose from a catalog of solutions like tabular data processing, computer vision, and natural language processing to get started quickly on building and training ML models. Also JumpStart integrates with other SageMaker capabilities. The notebooks leverage features like Clarify, Data Wrangler, Feature Store, and Model Monitor. You can use SageMaker JumpStart to accelerate your machine learning journey through reusable assets, templates, and models.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Deploying machine learning models at scale
```suggestion
### Deploying Machine Learning Models at Scale
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +### Fraud detection
```suggestion
### Fraud Detection
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +It is possible to leverage Amazon SageMaker to build forecasting models that predict future sales, demand, and other metrics. Forecasting takes past data and uses it to predict trends that may reoccu
```suggestion
It is possible to leverage Amazon SageMaker to build forecasting models that predict future sales, demand, and other metrics. Forecasting takes past data and uses it to predict trends that may reoccur in the future. SageMaker provides built-in algorithms like DeepAR that are optimized for time series forecasting. By bringing your historical time series data into SageMaker notebooks, you can train forecasting models that learn patterns and seasonality in the data. These models can then be deployed into production to generate forecasts on an ongoing basis.
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +description: "Leveraging Amazon SageMaker for Scalable and Robust ML Workflows"
```suggestion
description: "Leverage Amazon SageMaker for scalable and robust ML workflows."
```

2023-12-13 06:50 UTC, DalM2023 commented on concepts/what-is-sagemaker/index.md
> +---
Good job on this blog. It has clean structure and good intro highlighting how the productive fits into ML. My edits focus primarily on AP Style corrections. Please see my notes below. 

Overall, great job on this blog!

2023-12-13 15:41 UTC, cherbk commented
@kaizadwadia the first round of editorial review is finished. Kindly review and incorporate the suggested changes in the PR. Thank you!

2023-12-14 08:35 UTC, kaizadwadia commented on concepts/what-is-sagemaker/index.md
> +---
Thank you for the review! I have made the proposed changes!

2023-12-18 22:45 UTC, cherbk approved these changes

2024-01-12 15:13 UTC, cherbk approved these changes

2024-01-12 15:15 UTC, merged