Amazon Search Chaos Engineering Journey initial commit
build-on-aws/content pull request #932
Opened 2023-11-20 09:06 UTC by adhorn

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-11-20 09:08 UTC, adhorn commented
please assign @setheliot  for review. Thanks

2023-11-20 23:47 UTC, setheliot requested changes
Of course I LOVE this piece and want to see it published ASAP

I did not expect to have as many comments as I did, but...I did -- they are almost all around messaging, formatting, and clarity.  One one (maybe two) are content related 

Let me know if you have any questions

NOTE: This piece got moved from one directory to another, causing many of the comments to say "outdated" -- they ARE NOT outdated... please see all the comments.  Please un-hide hidden conversations... sigh....

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +At Amazon, we use tenets to facilitate making hard decisions and trade-offs between our leadership principles. For example, how can we reconcile our Customer Obsession leadership principle with exper
> consensus with the team

not clear which team... Search Resilience team, or the service teams across the Search org?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +With these tenets in mind, we set out to deliver a simple chaos experiment orchestrator starting with a [Cloud Development Kit (CDK)](https://aws.amazon.com/cdk/) library for internal Search teams. W
> to deploy all the essential infrastructure needed for chaos experiments into their AWS accounts using just one CDK statement. 

It would be really impactful to show some code here, even if just the one statement (in context)

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +With these tenets in mind, we set out to deliver a simple chaos experiment orchestrator starting with a [Cloud Development Kit (CDK)](https://aws.amazon.com/cdk/) library for internal Search teams. W
> We can then define experiments in a concise 10–15 lines of YAML

Again, an example would really pop here

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +Next, we used AWS EventBridge [scheduled rules](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) as a “cron in the cloud” to run experiments automatically at a m
Who do have relaxed aws naming requirements, but I think "Amazon Simple Storage Service (S3)" would be clearer

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +Next, we used AWS EventBridge [scheduled rules](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) as a “cron in the cloud” to run experiments automatically at a m
>  safety levers

You decided to not use "andon cord" here?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +![Architecture diagram showing a system for chaos experimentation orchestration across Search](images/figure3.png "Figure 2. A system for chaos experimentation orchestration across Search")
* In the caption you call is "system for chaos experimentation orchestration"
* earlier in this blog you say "Building a chaos experiment orchestrator "
* In my blog I call is "[Amazon Search Chaos Orchestrator](https://community.aws/posts/how-search-uses-chaos-engineering#amazon-search-chaos-orchestrator)"

So why is the title in the diagram "Search Chaos Experiment Service"?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +![Architecture diagram showing a system for chaos experimentation orchestration across Search](images/figure3.png "Figure 2. A system for chaos experimentation orchestration across Search")
Does FIS belong in the box with "Search Chaos Experiment Service"?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We developed an SLO monitoring service and promoted the adoption of SLOs throughout the Search organization. Our goal was to establish a single, authoritative source of truth regarding the expected a
>  If you also use budget burn-rate alarming to page on-call personnel, you can reduce the amount of monitors you need to maintain for both operational incidents and chaos experiments.

Not sure I follow why this is... need some additional explanation

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We developed an SLO monitoring service and promoted the adoption of SLOs throughout the Search organization. Our goal was to establish a single, authoritative source of truth regarding the expected a
> Finally, if a service has already exhausted its error budget, we don’t schedule experiments to prioritize the customer experience.

And perhaps most importantly, we prioritize the customer experience. If a service has already exhausted its error budget, we don’t schedule any experiments.

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We developed an SLO monitoring service and promoted the adoption of SLOs throughout the Search organization. Our goal was to establish a single, authoritative source of truth regarding the expected a
Is it worth discussing how budgets are replenished, using the sliding window?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We developed an SLO monitoring service and promoted the adoption of SLOs throughout the Search organization. Our goal was to establish a single, authoritative source of truth regarding the expected a
[optional] I think a diagram would work really well here.  Something showing the error budget as a bucket being depleted by experiments or deployments and replenished as the window moves.... 

This post can use more visuals

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +How could we scale our relatively small team to create, execute, and maintain hundreds of experiments across all of Search? How could we handle the combinatorial explosion of potential experiments (
>  failure injection types

Shouldn't this be "fault injection types"?

Faults are things that happen to your system.  Faults can cause failures depending on your resilience

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We call these efforts “undifferentiated heavy lifting” because they are duplicate toil across multiple teams and services. While this work benefits the customer in terms of higher availability, it do
> introducing failures

introducing faults?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +1. Experiments that validate the system's resilience to a particular failure: For instance, when we terminate a host, the service seamlessly switches to another host, and the end customer doesn't exp
> resilience to a particular failure

fault?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +2. Experiments where the hypothesis is that the system will recover from the failure without human operator intervention: For example, if a critical dependency experiences an outage, we want to ensur
"failure" is correct here

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +In practice, we assess the burn rate both before and after the experiment and make a comparison. If the two burn rates don't align, we consider the experiment to have failed. This approach helps us d
a graphical representation of this would be really helpful

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +1. Instance Termination: testing the system's resilience when an instance is terminated.
> Instance Termination: testing the system's resilience when an instance is terminated.

Doing a thing: The thing is done  😊

How about...

> Instance Termination: testing the system's resilience to loss of compute resources

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +3. Packet Black-holing: investigating how the system behaves when packets are intentionally dropped.
> Packet Black-holing: investigating how the system behaves when packets are intentionally dropped.

The experiment (simulation) is intentional dropping packets, but the fault being simulated is un-intentional dropping of packets, right?

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +4. Emergency Levers: activation of emergency levers (e.g., load shedding via graceful degradation) to ensure they work without encountering issues when they are most needed.
My problem with the parenthesis is not a stylistic one. It is you are dumping an important and weighty point into parenthesis, assuming the reader will understand.  They will not.   Both the phrases "load shedding" and "graceful degradation" will not be understand by some significant percentage of your audience.  Take it out of parenthesis and explain what it means

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +4. Emergency Levers: activation of emergency levers (e.g., load shedding via graceful degradation) to ensure they work without encountering issues when they are most needed.
you can also link to here to help explain it https://community.aws/posts/how-search-uses-chaos-engineering#a-chaos-experiment-on-amazon-search

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +The second mechanism is an SLO report for leaders that provides insights into the SLOs of all services in their organization. We currently require availability and latency SLOs. We do not separately
> The second mechanism is an SLO report for leaders that provides insights into the SLOs of all services in their organization. 

an anonymized version of this, as a figure, would be awesome - you need more visuals

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +This SLO report has the following KPIs:
What is a KPI?

(I know... but your reader may not)

2023-11-20 23:47 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +This SLO report has the following KPIs:
Also, the three things below are not what I would consider to be KPIs... but if all 4 of you think otherwise, I will not argue.

2023-11-21 08:15 UTC, adhorn commented on posts/amazon-search-chaos-engineering-journey/index.md
> +## The first Search GameDay
We use GameDay since that is the way Jesse Robbins called it.

2023-11-21 08:23 UTC, adhorn commented on posts/amazon-search-chaos-engineering-journey/index.md
> +We performed a [Correction of Errors (COE, aka “postmortem”)](https://aws.amazon.com/blogs/mt/why-you-should-develop-a-correction-of-error-coe/) to deep dive into the problem and identify corrective
It is linked in all my blogs :) Glad you noticed it.

2023-11-21 08:29 UTC, adhorn commented on posts/amazon-search-chaos-engineering-journey/index.md
> +There are dozens of teams building product search, but today we will talk about our Search Resilience team that improves the resilience of Amazon Search by running chaos experiments in production and
It is the former, but not sure that makes a difference tbh. The tool is owned by Search resilience team, but it executes in the 2PT accounts.

2023-11-21 08:51 UTC, adhorn commented on posts/amazon-search-chaos-engineering-journey/index.md
> +As we added production GameDays to our SOPs for peak readiness, Amazon continued growing with new peak events such as [Prime Day](https://aws.amazon.com/blogs/aws/prime-day-2023-powered-by-aws-all-th
Not sure why you think it conflicts. You build a tool (COE action), but no one end up using it (lack of mechanism)

2023-11-21 09:33 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +3. Provisioning infrastructure (e.g., chaos injecting agents, sidecar containers, AWS resources)
why do you hate parentheses?  ;)

2023-11-21 09:41 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We call these efforts “undifferentiated heavy lifting” because they are duplicate toil across multiple teams and services. While this work benefits the customer in terms of higher availability, it do
the previous section was load a scale.. I will try to clarify

2023-11-21 09:44 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We call these efforts “undifferentiated heavy lifting” because they are duplicate toil across multiple teams and services. While this work benefits the customer in terms of higher availability, it do
I will clarify. The journey is from Load testing to chaos engineering

2023-11-21 10:12 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +With these tenets in mind, we set out to deliver a simple chaos experiment orchestrator starting with a [Cloud Development Kit (CDK)](https://aws.amazon.com/cdk/) library for internal Search teams. W
showing code in that context doesnt make sense since it is within a larger framework, so it cant be copy pasted or used by readers.

2023-11-21 10:15 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +Next, we used AWS EventBridge [scheduled rules](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-create-rule-schedule.html) as a “cron in the cloud” to run experiments automatically at a m
yes, Andon cord isnt knon outside of Amazon most of the time and I would need to explain what it is .. thats another story in itself. We also call that safety lever in FIS

2023-11-21 10:15 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +![Architecture diagram showing a system for chaos experimentation orchestration across Search](images/figure3.png "Figure 2. A system for chaos experimentation orchestration across Search")
I will align

2023-11-21 12:34 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +We developed an SLO monitoring service and promoted the adoption of SLOs throughout the Search organization. Our goal was to establish a single, authoritative source of truth regarding the expected a
For visuals, I really dont have a good idea how to represent that and not sure it would add any value to be honest.

2023-11-21 12:38 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +1. Experiments that validate the system's resilience to a particular failure: For instance, when we terminate a host, the service seamlessly switches to another host, and the end customer doesn't exp
in that case it is failure since you are not resilient to a fault, but a failure.

2023-11-21 13:42 UTC, adhorn commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +This SLO report has the following KPIs:
We changed to metrics. Operational metrics to be precise.

2023-11-21 14:19 UTC, adhorn commented
I will close that PR since the change of folder has just messed things up. @setheliot  I did address all the comments, but will do another PR.

2023-11-21 14:20 UTC, closed without merging

2023-11-21 17:51 UTC, setheliot commented on posts/amazon-search-chaos-engineering-journey/index.md
> +There are dozens of teams building product search, but today we will talk about our Search Resilience team that improves the resilience of Amazon Search by running chaos experiments in production and
well, the whole point of my blog was about enablement.  How Search Resilience enables the 2PT to create and run CE experiments.  Is see that the fact that the orchestrator runs it does make "Search Resilience team that improves the resilience of Amazon Search by running chaos experiments in production" but has the potential to be misinterpreted as the Search Resilience team is taking on all the burden of creating and running these, rather than empowering teams to create and run them

2023-11-21 17:52 UTC, setheliot commented on posts/amazon-search-chaos-engineering-journey/index.md
> +As we added production GameDays to our SOPs for peak readiness, Amazon continued growing with new peak events such as [Prime Day](https://aws.amazon.com/blogs/aws/prime-day-2023-powered-by-aws-all-th
ok, got it.

2023-11-21 17:55 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +1. Guard rails to limit blast radius of experiments
I agree it is a valid term used in the industry.  I am the one who worked with the security messaging folks to convince them that use resilience folks should still be able to use it. I am just not sure it applies here.  I can sort of see it -- the guard rails prevent the problem from growing ever bigger, but as I said, blast radius is more commonly used in the context of fault isolation

2023-11-21 17:56 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +3. Provisioning infrastructure (e.g., chaos injecting agents, sidecar containers, AWS resources)
Why do you love them? :-)

2023-11-21 17:56 UTC, setheliot commented on concepts/amazon-search-chaos-engineering-journey/index.md
> +With these tenets in mind, we set out to deliver a simple chaos experiment orchestrator starting with a [Cloud Development Kit (CDK)](https://aws.amazon.com/cdk/) library for internal Search teams. W
ok, I defer to you