[New tutorial] Using GenAI to Generate Custom Amazon IVS Live Stream Backgrounds
build-on-aws/content pull request #948
Opened 2023-11-27 19:06 UTC by tonyv

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [x] The title of this pull request reflects the title of my content.
- [x] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [x] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

Is this pull request linked to a Content Proposal or Idea Suggestion Issue? If so, please link to it below using the number or full link.

```text
Resolves #5

or

Content for https://github.com/build-on-aws/content/issues/5
```

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-12-15 13:46 UTC, recursivecodes requested changes
Some comments above. The banner/demo gif is really low quality and we should include a disclaimer that mentions the edited duration to generate the image to avoid misrepresenting the speed of generating an image with Bedrock.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +I will walk you through a step-by-step process on how to create a web app to replace the background of your web camera’s feed, integrate it with Stable Diffusion XL on Amazon Bedrock to generate a ba
> I will walk you through a

In this article, we'll walk through the...

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +  banner: images/amazon-ivs-real-time-background-replacement-demo.gif
This gif is really low quality - can you regenerate it? Also, it appears to be edited to shorten the duration of how long the image generation process takes. If this is true, you *definitely* want to include a disclaimer that mentions this to avoid the appearance of trying to misrepresent our services.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +- How to replace your background with a custom image using MediaPipe Image Segmenter
How to replace the background of a live stream...

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +- How to create a Lambda function to invoke the Stable Diffusion model via Amazon Bedrock
How to create an AWS Lambda function...

Refer to https://w.amazon.com/bin/view/AWSDocs/editing/service-names

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +The following diagram shows how we will be replacing the background in our camera feed with a custom image. At a high level, we will get the underlying pixels from our custom background image and our
You might want to expand a bit on what Mediapipe Image Segmenter is in parenthesis since this may be a new tool to developers. Something like...

...Mediapipe Image Segmenter (a tool from Google, more on this in just a bit)

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +To replace your background, the first step is to identify which parts of your image are in the background so that you don’t inadvertently replace what’s in the foreground. This is where [Mediapipe Im
Try to stick to the same pronoun. In the previous paragraph, "we" is used (IE: we will get... we also pass...) but in this paragraph "you" is used (IE: your background... your image...). FWIW, I personally prefer "we" because it adds a human element to the author and gives the impression that "we" are on the journey together (the author and the reader/developer) whereas "you" seems more instructional and somehow more cold to me.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +To use MediaPipe Image Segmenter, let's install the @mediapipe/tasks-vision. We will also install Webpack so that we can later bundle our JavaScript.
add inline code formatting: `@mediapipe/tasks-vision`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, create some starter HTML in an index.html file. We will also take this opportunity to include the [IVS real-time streaming Web Broadcast SDK](https://docs.aws.amazon.com/ivs/latest/RealTimeUser
`index.html` - link to docs is redundant - no need for both in the same paragraph

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Let’s now add some crucial HTML elements to our burgeoning HTML file. Add a video element which will contain your live camera feed and will be used as input to the MediaPipe Image Segmenter. Also cre
Add a `<video>` element

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Let’s now add some crucial HTML elements to our burgeoning HTML file. Add a video element which will contain your live camera feed and will be used as input to the MediaPipe Image Segmenter. Also cre
Also create a `<canvas>` element...

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +We will also add buttons to join and leave what is known as a stage in Amazon IVS. A stage is a virtual space where participants can exchange video in real time. In order to join a stage, you also ne
Should expand on this: "you also need a participant token so we have added an input field to specify one" to mention that this is not a "normal" part of a real-time application. Maybe another sentence that says something like "Normally your application would generate this token for the user programmatically via the AWS SDK, but we'll keep things simple in this application.."

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Finally, let’s add a button we can click to send a prompt to Stable Diffusion to generate an image. Clicking this button will bring up a modal to enter a prompt to describe what we want our backgroun
Did we ever explain what Stable Diffusion is? Some developers may not be familiar with it. Wherever the first mention is, it's probably a good idea to add a quick sentence explaining what it is and why we are using it.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +```html
I strongly suggest removing superfluous attributes like `class`, `style`, etc. It makes your code so much readable. I usually do this and put a disclaimer "Note: extraneous attributes have been removed for readability, refer to the GH repo for the full solution..."

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Add a script tag before the closing </body> tag to load a bundled JavaScript file that will contain the code to do the background replacement and publish it to a stage:
add inline code `</body>`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, create a JavaScript file called `app.js` to get the element objects for the canvas and video elements that were created in the HTML page. Additionally, get the elements for our background chang
add inline code styling to `Stage`, `LocalStageStream`, etc...

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, create a JavaScript file called `app.js` to get the element objects for the canvas and video elements that were created in the HTML page. Additionally, get the elements for our background chang
basically any class, function, variable, etc should have `inline` code styling.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +const modal = document.querySelector(".modal");
just a suggestion, but you might want to add id attributes and use `getElementById` instead of `querySelector` on class names (all instances) - it's a cleaner approach

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, create an instance of ImageSegmenter, which will segment the image and return the result as a mask. When creating an instance of an ImageSegmenter, you will use the [selfie segmentation model](
`inline` code styling...

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +const createImageSegmenter = async () => {
I feel like this code block needs more explanation.

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +The first thing we need to do is get the user’s live camera feed. We will later be using the pixel data from this video stream by writing it to a canvas element combined with a custom image to create
`init()`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, in order to publish our video so the audience can see it, let’s capture the MediaStream from our first canvas element and assign it to segmentationStream. For now, this MediaStream will just co
`MediaStream`, `segmentationStream`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +The initBackgroundCanvas function is defined as follows, which is also added to app.js. This function simply loads our image into a canvas. We do this so that we can later copy its individual pixels
`initBackgroundCanvas`, `app.js`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +  img.crossOrigin = "Anonymous";
explain why we're setting `crossOrigin` to `Anonymous`?

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, assign the MediaStream from the local camera to our video element. Additionally, we also invoke a custom callback function every time a camera frame is loaded, which we will name renderVideoToC
`MediaStream`, `renderVideoToCanvas`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, let’s add the logic for the joinStage function. In this function, we’re going to get the MediaStream from the user’s microphone so that we can publish it to the stage. Publishing is the act of
`joinStage`, `MediaStream`, `StageStrategy`, `shouldSubscribeToParticipant`, `shouldPublishParticipant`, and `stageStreamsToPublish`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +First, let’s implement the stageStreamsToPublish function. This function is used to determine what audio and video streams to publish. To do that, it returns an array of [LocalStageStream](https://aw
`stageStreamsToPublish`, `MediaStream`, `segmentationStream`, `LocalStageStream`, `stageStreamsToPublish`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, implement the shouldPublishParticipant by simply returning true. This indicates whether you, the local participant, should publish your media streams.
`shouldPublishParticipant`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Next, implement the [shouldSubscribeToParticipant](https://docs.aws.amazon.com/ivs/latest/RealTimeUserGuide/web-publish-subscribe.html#web-publish-subscribe-concepts-events#web-publish-subscribe-conc
`shouldSubscribeToParticipant`, `SubscribeType.AUDIO_VIDEO`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +To finish up the joinStage function, create a new Stage object passing in the participant token and strategy object we just set up as arguments. The participant token is used to authenticate with the
`joinStage`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +This code uses the AWS SDK for Python to invoke the Stable Diffusion XL model we just added through the Bedrock console. Since the generated image is returned as a base64 encoded string, we need to d
is it 100% necessary to save the image to S3 (also - use the proper AWS [service name](https://w.amazon.com/bin/view/AWSDocs/editing/service-names) for S3)? why not just return the base64 image and [write it directly to the canvas](https://stackoverflow.com/a/4409745/511250)?

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +This code uses the AWS SDK for Python to invoke the Stable Diffusion XL model we just added through the Bedrock console. Since the generated image is returned as a base64 encoded string, we need to d
definitely think you should return the base64 image - it greatly simplifies and removes the need for the CF distribution

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +To replace the background in our camera feed with a new image, let’s now implement the renderVideoToCanvas function we mentioned earlier. This function renders the video feed to the second canvas ele
`renderVideoToCanvas`, `ImageSegmenter`, `segmentforVideo`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +To replace the background in our camera feed with a new image, let’s now implement the renderVideoToCanvas function we mentioned earlier. This function renders the video feed to the second canvas ele
`replaceBackground`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Create the replaceBackground function, which merges the custom background image with the foreground from the camera feed to replace the background. The function first retrieves the underlying pixel d
`replaceBackground`, `ImageSegmenter`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Update your package.json file to run webpack as your JavaScript bundler when you run the build script. Specify webpack.config.js as your Webpack config file.
`package.json`, `webpack.config.js`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Now run your build script from the command line to bundle your JavaScript. Doing so lets us use the import statement within app.js without any issues.
`import`, `app.js`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +Finally, start a simple HTTP server from the directory containing index.html and open localhost:8000 to see the result. You should see a local camera feed with a new background image.
`index.html` `localhost:8000`

2023-12-15 13:46 UTC, recursivecodes commented on tutorials/how-to-use-genai-to-replace-background-amazon-ivs/index.md
> +python3 -m http.server -d ./
Maybe also suggest `http-server` ([link](https://www.npmjs.com/package/http-server)) as an alternative.

2023-12-15 20:50 UTC, cherbk commented
@tonyv The technical review has been completed. Please take a moment to review and incorporate the suggested changes in the PR. Thank you!

2024-01-04 01:20 UTC, tonyv commented
@recursivecodes Thanks for the thorough review and suggestions. I've pushed a commit to address your comments. Let me know if you have any other concerns. cc @cherbk

2024-01-12 15:24 UTC, cherbk approved these changes

2024-01-12 17:18 UTC, cherbk approved these changes

2024-01-12 17:19 UTC, merged