[New Tutorial] Streamline AWS Deployments with GitLab CI and Terraform
build-on-aws/content pull request #965
Opened 2023-12-06 16:55 UTC by kaizadwadia

# Content Pull Request Checklist

Please check to make sure your content submission meets the following requirements by adding an `x` between the brackets:

- [ x ] The title of this pull request reflects the title of my content.
- [ x ] I have reviewed the [Content Review Checklist](https://github.com/build-on-aws/content/blob/main/CONTENT_REVIEW_CHECKLIST.md).
- [ x ] This pull request contains one piece of content (post or page).

**Important: if you are submitting a PR to update existing content, please ensure you [sync'ed your fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) first before you created your branch.**

**By submitting this pull request, I confirm I own this content, have permission to use each image included in this content, and that it will be released under the [CC BY-SA 4.0 SA License](https://github.com/build-on-aws/content/blob/main/LICENSE). Notwithstanding the above, if you provide source code text within your content piece, you are providing such source code under the [MIT-0](https://opensource.org/license/mit-0/) license.**

2023-12-08 04:40 UTC, abhirockzz requested changes
Thanks for the tutorial! I have suggested a few changes.

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +Once you have completely filled out the information, you can click on "Get thumbprint" to retreive the thumbprint from the URL you supplied. [The OIDC thumbprint page in the AWS documentation](https:
spelling correction. update retreive -> retrieve

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +Now whenever inspiration strikes, you can implement and deploy new AWS infrastructure automatically in a fraction of the time. You're ready to use GitLab and Terraform to streamline your cloud deploy
consider removing this line

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +By following these steps, you can take the manual work and errors out of deploying to AWS. Your infrastructure becomes code that can be treated like any other application code.
"you can take the manual work and errors out of deploying to AWS" - reword this part

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +State lock is a mechanic that prevents multiple Terraform commands from accessing and trying to modify the state at the same time. When you run a Terraform command, it will acquire a lock on the stat
"State lock is a mechanic" - did you mean "mechanism"?

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +Make sure that the option for OpenID Connect is selected on the top, this is because OpenID Connect allows you to configure trust relationships with third party accounts including but not limited to
gitlab.com/.well-known/openid-configuration - takes me to an incorrect link

2023-12-08 04:40 UTC, abhirockzz commented on tutorials/gitlab-with-terraform/index.md
> +### Prerequisites
change to H2 - ## Prerequisites

2023-12-08 08:40 UTC, kaizadwadia commented on tutorials/gitlab-with-terraform/index.md
> +By following these steps, you can take the manual work and errors out of deploying to AWS. Your infrastructure becomes code that can be treated like any other application code.
Removed instead, doesn't really add much in hindsight.

2023-12-08 08:47 UTC, kaizadwadia commented
Thank you Abhishek! I have made the changes.

2023-12-08 17:39 UTC, cherbk approved these changes

2023-12-12 07:51 UTC, DalM2023 reviewed
1st editorial review done. Author revision requested.

2023-12-12 07:51 UTC, DalM2023 commented on tutorials/gitlab-with-terraform/index.md
> +## Clean-up
```suggestion
## Clean Up
```

2023-12-12 07:51 UTC, DalM2023 commented on tutorials/gitlab-with-terraform/index.md
> +To clean-up your AWS account, remember to delete the following resources:
```suggestion
To clean up your AWS account, remember to delete the following resources:
```

2023-12-12 07:51 UTC, DalM2023 commented on tutorials/gitlab-with-terraform/index.md
> +Deploying infrastructure to AWS manually can be time-consuming and prone to errors. In this post, we'll go over how to set up a CI/CD pipeline for automated AWS deployments using GitLab and Terraform
This is a good start but super pithy. Consider adding a sentence to tease out the pain pain (time and errors). 

```suggestion
Deploying infrastructure to AWS manually can be time consuming and prone to errors.  MISTAKES CAN EASILY HAPPEN BECAUSE XYZ. In this post, we'll go over how to set up a CI/CD pipeline for automated AWS deployments using GitLab and Terraform. 
```

2023-12-12 07:51 UTC, DalM2023 commented on tutorials/gitlab-with-terraform/index.md
> +description: "A step-by-step guide for deploying infrastructure using CI/CD"
```suggestion
description: "A step-by-step guide for deploying infrastructure using CI/CD."
```

2023-12-12 07:51 UTC, DalM2023 commented on tutorials/gitlab-with-terraform/index.md
> +---
Hello, 

This is a near perfect blog. Good structure, uniformed sections, perfectly written title cases, well written...  Congrats! 

I did some light editing and gave a suggestion for the intro. Please see my notes below. 

Bravo! Well done.

2023-12-12 18:04 UTC, kaizadwadia commented on tutorials/gitlab-with-terraform/index.md
> +---
Thank you for the feedback! I have made the changes. Particularly, the following intro rewrite:

> Deploying infrastructure to AWS manually can be time consuming and prone to errors. Mistakes can easily happen because manual processes rely on humans repeating the same tasks without validation checks, leading to configuration errors, inconsistencies, and drift from the desired state. In this post, we'll go over how to set up a CI/CD pipeline for automating AWS deployments using GitLab and Terraform.

2023-12-13 15:42 UTC, cherbk approved these changes

2023-12-18 17:20 UTC, damonk10 approved these changes

2023-12-18 18:02 UTC, merged